package com.ripplenexus.salespilot.notification.domain;

public enum NotificationType {
    LEAD_ASSIGNED, MEETING_REMINDER, FOLLOWUP_REMINDER,
    COMMISSION_APPROVED, COMMISSION_PAID, COMMISSION_REJECTED,
    TARGET_ACHIEVED, TARGET_WARNING, DEAL_CLOSED,
    TASK_ASSIGNED, TASK_DUE, SYSTEM, OTHER
}
