// Generated by delombok at Fri Jul 24 16:18:04 IST 2026
package com.ripplenexus.salespilot.employee.domain;

import com.ripplenexus.salespilot.auth.domain.User;
import com.ripplenexus.salespilot.core.domain.BaseEntity;
import jakarta.persistence.*;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "employees")
public class Employee extends BaseEntity {
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, unique = true)
    private User user;
    @Column(name = "employee_number", nullable = false, unique = true)
    private String employeeNumber;
    @Column(name = "first_name", nullable = false)
    private String firstName;
    @Column(name = "last_name", nullable = false)
    private String lastName;
    @Column(name = "personal_email")
    private String personalEmail;
    @Column(name = "work_email", nullable = false, unique = true)
    private String workEmail;
    @Column(name = "phone")
    private String phone;
    @Column(name = "whatsapp")
    private String whatsapp;
    @Enumerated(EnumType.STRING)
    @Column(name = "gender")
    private Gender gender;
    @Column(name = "date_of_birth")
    private LocalDate dateOfBirth;
    @Column(name = "address")
    private String address;
    @Column(name = "city")
    private String city;
    @Column(name = "state")
    private String state;
    @Column(name = "country")
    private String country;
    @Column(name = "pincode")
    private String pincode;
    @Column(name = "profile_picture")
    private String profilePicture;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "department_id")
    private Department department;
    @Column(name = "designation")
    private String designation;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "manager_id")
    private Employee manager;
    @Column(name = "joining_date", nullable = false)
    private LocalDate joiningDate;
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private EmploymentStatus status;
    @Column(name = "salary", precision = 12, scale = 2)
    private BigDecimal salary;
    @Column(name = "bank_name")
    private String bankName;
    @Column(name = "bank_account")
    private String bankAccount;
    @Column(name = "bank_ifsc")
    private String bankIfsc;
    @Column(name = "upi_id")
    private String upiId;
    @Column(name = "national_id")
    private String nationalId;
    @Column(name = "country_of_id")
    private String countryOfId;
    @Enumerated(EnumType.STRING)
    @Column(name = "kyc_status", nullable = false)
    private KycStatus kycStatus;
    @Column(name = "kyc_document_path")
    private String kycDocumentPath;
    @Column(name = "kyc_attempts", nullable = false)
    private Integer kycAttempts;
    @Column(name = "emergency_name")
    private String emergencyName;
    @Column(name = "emergency_phone")
    private String emergencyPhone;
    @Column(name = "emergency_rel")
    private String emergencyRelation;
    @Column(name = "performance_rating", precision = 3, scale = 1)
    private BigDecimal performanceRating;
    @Column(name = "notes")
    private String notes;
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "employee_territories", joinColumns = @JoinColumn(name = "employee_id"))
    @Column(name = "country")
    @org.hibernate.annotations.Fetch(org.hibernate.annotations.FetchMode.SUBSELECT)
    private Set<String> territories;
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "employee_industries", joinColumns = @JoinColumn(name = "employee_id"))
    @Column(name = "industry")
    @org.hibernate.annotations.Fetch(org.hibernate.annotations.FetchMode.SUBSELECT)
    private Set<String> industries;
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "employee_services", joinColumns = @JoinColumn(name = "employee_id"))
    @Column(name = "service")
    @org.hibernate.annotations.Fetch(org.hibernate.annotations.FetchMode.SUBSELECT)
    private Set<String> services;
    @Column(name = "end_date")
    private LocalDate endDate;
    @Enumerated(EnumType.STRING)
    @Column(name = "resignation_status")
    private ResignationStatus resignationStatus;
    @Column(name = "resignation_reason")
    private String resignationReason;
    @Column(name = "resignation_submitted_at")
    private java.time.ZonedDateTime resignationSubmittedAt;

    public String getFullName() {
        return firstName + " " + lastName;
    }


    public enum Gender {
        MALE, FEMALE, OTHER, PREFER_NOT_TO_SAY;
    }


    public enum EmploymentStatus {
        ACTIVE, INACTIVE, ON_LEAVE, TERMINATED, PROBATION;
    }


    public enum KycStatus {
        PENDING, SUBMITTED, VERIFIED, REJECTED, CLARIFICATION_NEEDED, FROZEN;
    }


    public enum ResignationStatus {
        SUBMITTED, APPROVED, REJECTED, WITHDRAWN;
    }

    // Explicit Getters and Setters for guaranteed compilation
    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getEmployeeNumber() {
        return employeeNumber;
    }

    public void setEmployeeNumber(String employeeNumber) {
        this.employeeNumber = employeeNumber;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPersonalEmail() {
        return personalEmail;
    }

    public void setPersonalEmail(String personalEmail) {
        this.personalEmail = personalEmail;
    }

    public String getWorkEmail() {
        return workEmail;
    }

    public void setWorkEmail(String workEmail) {
        this.workEmail = workEmail;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getWhatsapp() {
        return whatsapp;
    }

    public void setWhatsapp(String whatsapp) {
        this.whatsapp = whatsapp;
    }

    public Gender getGender() {
        return gender;
    }

    public void setGender(Gender gender) {
        this.gender = gender;
    }

    public LocalDate getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getPincode() {
        return pincode;
    }

    public void setPincode(String pincode) {
        this.pincode = pincode;
    }

    public String getProfilePicture() {
        return profilePicture;
    }

    public void setProfilePicture(String profilePicture) {
        this.profilePicture = profilePicture;
    }

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    public String getDesignation() {
        return designation;
    }

    public void setDesignation(String designation) {
        this.designation = designation;
    }

    public Employee getManager() {
        return manager;
    }

    public void setManager(Employee manager) {
        this.manager = manager;
    }

    public LocalDate getJoiningDate() {
        return joiningDate;
    }

    public void setJoiningDate(LocalDate joiningDate) {
        this.joiningDate = joiningDate;
    }

    public EmploymentStatus getStatus() {
        return status;
    }

    public void setStatus(EmploymentStatus status) {
        this.status = status;
    }

    public BigDecimal getSalary() {
        return salary;
    }

    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    public String getBankName() {
        return bankName;
    }

    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    public String getBankAccount() {
        return bankAccount;
    }

    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount;
    }

    public String getBankIfsc() {
        return bankIfsc;
    }

    public void setBankIfsc(String bankIfsc) {
        this.bankIfsc = bankIfsc;
    }

    public String getUpiId() {
        return upiId;
    }

    public void setUpiId(String upiId) {
        this.upiId = upiId;
    }

    public String getNationalId() {
        return nationalId;
    }

    public void setNationalId(String nationalId) {
        this.nationalId = nationalId;
    }

    public String getCountryOfId() {
        return countryOfId;
    }

    public void setCountryOfId(String countryOfId) {
        this.countryOfId = countryOfId;
    }

    public KycStatus getKycStatus() {
        return kycStatus;
    }

    public void setKycStatus(KycStatus kycStatus) {
        this.kycStatus = kycStatus;
    }

    public String getKycDocumentPath() {
        return kycDocumentPath;
    }

    public void setKycDocumentPath(String kycDocumentPath) {
        this.kycDocumentPath = kycDocumentPath;
    }

    public Integer getKycAttempts() {
        return kycAttempts;
    }

    public void setKycAttempts(Integer kycAttempts) {
        this.kycAttempts = kycAttempts;
    }

    public String getEmergencyName() {
        return emergencyName;
    }

    public void setEmergencyName(String emergencyName) {
        this.emergencyName = emergencyName;
    }

    public String getEmergencyPhone() {
        return emergencyPhone;
    }

    public void setEmergencyPhone(String emergencyPhone) {
        this.emergencyPhone = emergencyPhone;
    }

    public String getEmergencyRelation() {
        return emergencyRelation;
    }

    public void setEmergencyRelation(String emergencyRelation) {
        this.emergencyRelation = emergencyRelation;
    }

    public BigDecimal getPerformanceRating() {
        return performanceRating;
    }

    public void setPerformanceRating(BigDecimal performanceRating) {
        this.performanceRating = performanceRating;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Set<String> getTerritories() {
        return territories;
    }

    public void setTerritories(Set<String> territories) {
        this.territories = territories;
    }

    public Set<String> getIndustries() {
        return industries;
    }

    public void setIndustries(Set<String> industries) {
        this.industries = industries;
    }

    public Set<String> getServices() {
        return services;
    }

    public void setServices(Set<String> services) {
        this.services = services;
    }

    public LocalDate getEndDate() {
        return endDate;
    }

    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    public ResignationStatus getResignationStatus() {
        return resignationStatus;
    }

    public void setResignationStatus(ResignationStatus resignationStatus) {
        this.resignationStatus = resignationStatus;
    }

    public String getResignationReason() {
        return resignationReason;
    }

    public void setResignationReason(String resignationReason) {
        this.resignationReason = resignationReason;
    }

    public java.time.ZonedDateTime getResignationSubmittedAt() {
        return resignationSubmittedAt;
    }

    public void setResignationSubmittedAt(java.time.ZonedDateTime resignationSubmittedAt) {
        this.resignationSubmittedAt = resignationSubmittedAt;
    }

    @java.lang.SuppressWarnings("all")
    
    private static EmploymentStatus $default$status() {
        return EmploymentStatus.ACTIVE;
    }

    @java.lang.SuppressWarnings("all")
    
    private static KycStatus $default$kycStatus() {
        return KycStatus.PENDING;
    }

    @java.lang.SuppressWarnings("all")
    
    private static Integer $default$kycAttempts() {
        return 0;
    }

    @java.lang.SuppressWarnings("all")
    
    private static Set<String> $default$territories() {
        return new HashSet<>();
    }

    @java.lang.SuppressWarnings("all")
    
    private static Set<String> $default$industries() {
        return new HashSet<>();
    }

    @java.lang.SuppressWarnings("all")
    
    private static Set<String> $default$services() {
        return new HashSet<>();
    }


    @java.lang.SuppressWarnings("all")
    
    public static class EmployeeBuilder {
        @java.lang.SuppressWarnings("all")
        
        private User user;
        @java.lang.SuppressWarnings("all")
        
        private String employeeNumber;
        @java.lang.SuppressWarnings("all")
        
        private String firstName;
        @java.lang.SuppressWarnings("all")
        
        private String lastName;
        @java.lang.SuppressWarnings("all")
        
        private String personalEmail;
        @java.lang.SuppressWarnings("all")
        
        private String workEmail;
        @java.lang.SuppressWarnings("all")
        
        private String phone;
        @java.lang.SuppressWarnings("all")
        
        private String whatsapp;
        @java.lang.SuppressWarnings("all")
        
        private Gender gender;
        @java.lang.SuppressWarnings("all")
        
        private LocalDate dateOfBirth;
        @java.lang.SuppressWarnings("all")
        
        private String address;
        @java.lang.SuppressWarnings("all")
        
        private String city;
        @java.lang.SuppressWarnings("all")
        
        private String state;
        @java.lang.SuppressWarnings("all")
        
        private String country;
        @java.lang.SuppressWarnings("all")
        
        private String pincode;
        @java.lang.SuppressWarnings("all")
        
        private String profilePicture;
        @java.lang.SuppressWarnings("all")
        
        private Department department;
        @java.lang.SuppressWarnings("all")
        
        private String designation;
        @java.lang.SuppressWarnings("all")
        
        private Employee manager;
        @java.lang.SuppressWarnings("all")
        
        private LocalDate joiningDate;
        @java.lang.SuppressWarnings("all")
        
        private boolean status$set;
        @java.lang.SuppressWarnings("all")
        
        private EmploymentStatus status$value;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal salary;
        @java.lang.SuppressWarnings("all")
        
        private String bankName;
        @java.lang.SuppressWarnings("all")
        
        private String bankAccount;
        @java.lang.SuppressWarnings("all")
        
        private String bankIfsc;
        @java.lang.SuppressWarnings("all")
        
        private String upiId;
        @java.lang.SuppressWarnings("all")
        
        private String nationalId;
        @java.lang.SuppressWarnings("all")
        
        private String countryOfId;
        @java.lang.SuppressWarnings("all")
        
        private boolean kycStatus$set;
        @java.lang.SuppressWarnings("all")
        
        private KycStatus kycStatus$value;
        @java.lang.SuppressWarnings("all")
        
        private String kycDocumentPath;
        @java.lang.SuppressWarnings("all")
        
        private boolean kycAttempts$set;
        @java.lang.SuppressWarnings("all")
        
        private Integer kycAttempts$value;
        @java.lang.SuppressWarnings("all")
        
        private String emergencyName;
        @java.lang.SuppressWarnings("all")
        
        private String emergencyPhone;
        @java.lang.SuppressWarnings("all")
        
        private String emergencyRelation;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal performanceRating;
        @java.lang.SuppressWarnings("all")
        
        private String notes;
        @java.lang.SuppressWarnings("all")
        
        private boolean territories$set;
        @java.lang.SuppressWarnings("all")
        
        private Set<String> territories$value;
        @java.lang.SuppressWarnings("all")
        
        private boolean industries$set;
        @java.lang.SuppressWarnings("all")
        
        private Set<String> industries$value;
        @java.lang.SuppressWarnings("all")
        
        private boolean services$set;
        @java.lang.SuppressWarnings("all")
        
        private Set<String> services$value;
        @java.lang.SuppressWarnings("all")
        
        private LocalDate endDate;
        @java.lang.SuppressWarnings("all")
        
        private ResignationStatus resignationStatus;
        @java.lang.SuppressWarnings("all")
        
        private String resignationReason;
        @java.lang.SuppressWarnings("all")
        
        private java.time.ZonedDateTime resignationSubmittedAt;

        @java.lang.SuppressWarnings("all")
        
        EmployeeBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder user(final User user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder employeeNumber(final String employeeNumber) {
            this.employeeNumber = employeeNumber;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder firstName(final String firstName) {
            this.firstName = firstName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder lastName(final String lastName) {
            this.lastName = lastName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder personalEmail(final String personalEmail) {
            this.personalEmail = personalEmail;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder workEmail(final String workEmail) {
            this.workEmail = workEmail;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder phone(final String phone) {
            this.phone = phone;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder whatsapp(final String whatsapp) {
            this.whatsapp = whatsapp;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder gender(final Gender gender) {
            this.gender = gender;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder dateOfBirth(final LocalDate dateOfBirth) {
            this.dateOfBirth = dateOfBirth;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder address(final String address) {
            this.address = address;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder city(final String city) {
            this.city = city;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder state(final String state) {
            this.state = state;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder country(final String country) {
            this.country = country;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder pincode(final String pincode) {
            this.pincode = pincode;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder profilePicture(final String profilePicture) {
            this.profilePicture = profilePicture;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder department(final Department department) {
            this.department = department;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder designation(final String designation) {
            this.designation = designation;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder manager(final Employee manager) {
            this.manager = manager;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder joiningDate(final LocalDate joiningDate) {
            this.joiningDate = joiningDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder status(final EmploymentStatus status) {
            this.status$value = status;
            status$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder salary(final BigDecimal salary) {
            this.salary = salary;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder bankName(final String bankName) {
            this.bankName = bankName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder bankAccount(final String bankAccount) {
            this.bankAccount = bankAccount;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder bankIfsc(final String bankIfsc) {
            this.bankIfsc = bankIfsc;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder upiId(final String upiId) {
            this.upiId = upiId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder nationalId(final String nationalId) {
            this.nationalId = nationalId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder countryOfId(final String countryOfId) {
            this.countryOfId = countryOfId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder kycStatus(final KycStatus kycStatus) {
            this.kycStatus$value = kycStatus;
            kycStatus$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder kycDocumentPath(final String kycDocumentPath) {
            this.kycDocumentPath = kycDocumentPath;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder kycAttempts(final Integer kycAttempts) {
            this.kycAttempts$value = kycAttempts;
            kycAttempts$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder emergencyName(final String emergencyName) {
            this.emergencyName = emergencyName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder emergencyPhone(final String emergencyPhone) {
            this.emergencyPhone = emergencyPhone;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder emergencyRelation(final String emergencyRelation) {
            this.emergencyRelation = emergencyRelation;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder performanceRating(final BigDecimal performanceRating) {
            this.performanceRating = performanceRating;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder notes(final String notes) {
            this.notes = notes;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder territories(final Set<String> territories) {
            this.territories$value = territories;
            territories$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder industries(final Set<String> industries) {
            this.industries$value = industries;
            industries$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder services(final Set<String> services) {
            this.services$value = services;
            services$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder endDate(final LocalDate endDate) {
            this.endDate = endDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder resignationStatus(final ResignationStatus resignationStatus) {
            this.resignationStatus = resignationStatus;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder resignationReason(final String resignationReason) {
            this.resignationReason = resignationReason;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Employee.EmployeeBuilder resignationSubmittedAt(final java.time.ZonedDateTime resignationSubmittedAt) {
            this.resignationSubmittedAt = resignationSubmittedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Employee build() {
            EmploymentStatus status$value = this.status$value;
            if (!this.status$set) status$value = Employee.$default$status();
            KycStatus kycStatus$value = this.kycStatus$value;
            if (!this.kycStatus$set) kycStatus$value = Employee.$default$kycStatus();
            Integer kycAttempts$value = this.kycAttempts$value;
            if (!this.kycAttempts$set) kycAttempts$value = Employee.$default$kycAttempts();
            Set<String> territories$value = this.territories$value;
            if (!this.territories$set) territories$value = Employee.$default$territories();
            Set<String> industries$value = this.industries$value;
            if (!this.industries$set) industries$value = Employee.$default$industries();
            Set<String> services$value = this.services$value;
            if (!this.services$set) services$value = Employee.$default$services();
            return new Employee(this.user, this.employeeNumber, this.firstName, this.lastName, this.personalEmail, this.workEmail, this.phone, this.whatsapp, this.gender, this.dateOfBirth, this.address, this.city, this.state, this.country, this.pincode, this.profilePicture, this.department, this.designation, this.manager, this.joiningDate, status$value, this.salary, this.bankName, this.bankAccount, this.bankIfsc, this.upiId, this.nationalId, this.countryOfId, kycStatus$value, this.kycDocumentPath, kycAttempts$value, this.emergencyName, this.emergencyPhone, this.emergencyRelation, this.performanceRating, this.notes, territories$value, industries$value, services$value, this.endDate, this.resignationStatus, this.resignationReason, this.resignationSubmittedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Employee.EmployeeBuilder(user=" + this.user + ", employeeNumber=" + this.employeeNumber + ", firstName=" + this.firstName + ", lastName=" + this.lastName + ", personalEmail=" + this.personalEmail + ", workEmail=" + this.workEmail + ", phone=" + this.phone + ", whatsapp=" + this.whatsapp + ", gender=" + this.gender + ", dateOfBirth=" + this.dateOfBirth + ", address=" + this.address + ", city=" + this.city + ", state=" + this.state + ", country=" + this.country + ", pincode=" + this.pincode + ", profilePicture=" + this.profilePicture + ", department=" + this.department + ", designation=" + this.designation + ", manager=" + this.manager + ", joiningDate=" + this.joiningDate + ", status$value=" + this.status$value + ", salary=" + this.salary + ", bankName=" + this.bankName + ", bankAccount=" + this.bankAccount + ", bankIfsc=" + this.bankIfsc + ", upiId=" + this.upiId + ", nationalId=" + this.nationalId + ", countryOfId=" + this.countryOfId + ", kycStatus$value=" + this.kycStatus$value + ", kycDocumentPath=" + this.kycDocumentPath + ", kycAttempts$value=" + this.kycAttempts$value + ", emergencyName=" + this.emergencyName + ", emergencyPhone=" + this.emergencyPhone + ", emergencyRelation=" + this.emergencyRelation + ", performanceRating=" + this.performanceRating + ", notes=" + this.notes + ", territories$value=" + this.territories$value + ", industries$value=" + this.industries$value + ", services$value=" + this.services$value + ", endDate=" + this.endDate + ", resignationStatus=" + this.resignationStatus + ", resignationReason=" + this.resignationReason + ", resignationSubmittedAt=" + this.resignationSubmittedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static Employee.EmployeeBuilder builder() {
        return new Employee.EmployeeBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Employee() {
        this.status = Employee.$default$status();
        this.kycStatus = Employee.$default$kycStatus();
        this.kycAttempts = Employee.$default$kycAttempts();
        this.territories = Employee.$default$territories();
        this.industries = Employee.$default$industries();
        this.services = Employee.$default$services();
    }

    @java.lang.SuppressWarnings("all")
    
    public Employee(final User user, final String employeeNumber, final String firstName, final String lastName, final String personalEmail, final String workEmail, final String phone, final String whatsapp, final Gender gender, final LocalDate dateOfBirth, final String address, final String city, final String state, final String country, final String pincode, final String profilePicture, final Department department, final String designation, final Employee manager, final LocalDate joiningDate, final EmploymentStatus status, final BigDecimal salary, final String bankName, final String bankAccount, final String bankIfsc, final String upiId, final String nationalId, final String countryOfId, final KycStatus kycStatus, final String kycDocumentPath, final Integer kycAttempts, final String emergencyName, final String emergencyPhone, final String emergencyRelation, final BigDecimal performanceRating, final String notes, final Set<String> territories, final Set<String> industries, final Set<String> services, final LocalDate endDate, final ResignationStatus resignationStatus, final String resignationReason, final java.time.ZonedDateTime resignationSubmittedAt) {
        this.user = user;
        this.employeeNumber = employeeNumber;
        this.firstName = firstName;
        this.lastName = lastName;
        this.personalEmail = personalEmail;
        this.workEmail = workEmail;
        this.phone = phone;
        this.whatsapp = whatsapp;
        this.gender = gender;
        this.dateOfBirth = dateOfBirth;
        this.address = address;
        this.city = city;
        this.state = state;
        this.country = country;
        this.pincode = pincode;
        this.profilePicture = profilePicture;
        this.department = department;
        this.designation = designation;
        this.manager = manager;
        this.joiningDate = joiningDate;
        this.status = status;
        this.salary = salary;
        this.bankName = bankName;
        this.bankAccount = bankAccount;
        this.bankIfsc = bankIfsc;
        this.upiId = upiId;
        this.nationalId = nationalId;
        this.countryOfId = countryOfId;
        this.kycStatus = kycStatus;
        this.kycDocumentPath = kycDocumentPath;
        this.kycAttempts = kycAttempts;
        this.emergencyName = emergencyName;
        this.emergencyPhone = emergencyPhone;
        this.emergencyRelation = emergencyRelation;
        this.performanceRating = performanceRating;
        this.notes = notes;
        this.territories = territories;
        this.industries = industries;
        this.services = services;
        this.endDate = endDate;
        this.resignationStatus = resignationStatus;
        this.resignationReason = resignationReason;
        this.resignationSubmittedAt = resignationSubmittedAt;
    }
}
