// Generated by delombok at Fri Jul 24 16:18:01 IST 2026
package com.ripplenexus.salespilot.auth.domain;

import com.ripplenexus.salespilot.core.domain.BaseEntity;
import jakarta.persistence.*;


@Entity
@Table(name = "permissions")
public class Permission extends BaseEntity {
    @Column(name = "name", nullable = false, unique = true)
    private String name;
    @Column(name = "description")
    private String description;
    @Column(name = "module", nullable = false)
    private String module;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getModule() {
        return module;
    }

    public void setModule(String module) {
        this.module = module;
    }


    @java.lang.SuppressWarnings("all")
    
    public static class PermissionBuilder {
        @java.lang.SuppressWarnings("all")
        
        private String name;
        @java.lang.SuppressWarnings("all")
        
        private String description;
        @java.lang.SuppressWarnings("all")
        
        private String module;

        @java.lang.SuppressWarnings("all")
        
        PermissionBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Permission.PermissionBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Permission.PermissionBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Permission.PermissionBuilder module(final String module) {
            this.module = module;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Permission build() {
            return new Permission(this.name, this.description, this.module);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Permission.PermissionBuilder(name=" + this.name + ", description=" + this.description + ", module=" + this.module + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static Permission.PermissionBuilder builder() {
        return new Permission.PermissionBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Permission() {
    }

    @java.lang.SuppressWarnings("all")
    
    public Permission(final String name, final String description, final String module) {
        this.name = name;
        this.description = description;
        this.module = module;
    }
}
