// Generated by delombok at Fri Jul 24 16:18:01 IST 2026
package com.ripplenexus.salespilot.commission.domain;

import com.ripplenexus.salespilot.core.domain.BaseEntity;
import jakarta.persistence.*;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "commission_rules")
public class CommissionRule extends BaseEntity {
    @Column(name = "name", nullable = false)
    private String name;
    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false)
    private CommissionType type;
    @Column(name = "percentage", precision = 5, scale = 2)
    private BigDecimal percentage;
    @Column(name = "fixed_amount", precision = 12, scale = 2)
    private BigDecimal fixedAmount;
    @Column(name = "description")
    private String description;
    @Column(name = "is_active", nullable = false)
    private boolean isActive = true;
    @OneToMany(mappedBy = "rule", cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("tierOrder ASC")
    private List<CommissionTier> tiers;


    public enum CommissionType {
        PERCENTAGE, FIXED, HYBRID, TIERED;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public CommissionType getType() {
        return type;
    }

    public void setType(CommissionType type) {
        this.type = type;
    }

    public BigDecimal getPercentage() {
        return percentage;
    }

    public void setPercentage(BigDecimal percentage) {
        this.percentage = percentage;
    }

    public BigDecimal getFixedAmount() {
        return fixedAmount;
    }

    public void setFixedAmount(BigDecimal fixedAmount) {
        this.fixedAmount = fixedAmount;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean isActive() {
        return isActive;
    }

    public void setActive(boolean active) {
        isActive = active;
    }

    public List<CommissionTier> getTiers() {
        return tiers;
    }

    public void setTiers(List<CommissionTier> tiers) {
        this.tiers = tiers;
    }

    @java.lang.SuppressWarnings("all")
    
    private static List<CommissionTier> $default$tiers() {
        return new ArrayList<>();
    }


    @java.lang.SuppressWarnings("all")
    
    public static class CommissionRuleBuilder {
        @java.lang.SuppressWarnings("all")
        
        private String name;
        @java.lang.SuppressWarnings("all")
        
        private CommissionType type;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal percentage;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal fixedAmount;
        @java.lang.SuppressWarnings("all")
        
        private String description;
        @java.lang.SuppressWarnings("all")
        
        private boolean isActive;
        @java.lang.SuppressWarnings("all")
        
        private boolean tiers$set;
        @java.lang.SuppressWarnings("all")
        
        private List<CommissionTier> tiers$value;

        @java.lang.SuppressWarnings("all")
        
        CommissionRuleBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public CommissionRule.CommissionRuleBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public CommissionRule.CommissionRuleBuilder type(final CommissionType type) {
            this.type = type;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public CommissionRule.CommissionRuleBuilder percentage(final BigDecimal percentage) {
            this.percentage = percentage;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public CommissionRule.CommissionRuleBuilder fixedAmount(final BigDecimal fixedAmount) {
            this.fixedAmount = fixedAmount;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public CommissionRule.CommissionRuleBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public CommissionRule.CommissionRuleBuilder isActive(final boolean isActive) {
            this.isActive = isActive;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public CommissionRule.CommissionRuleBuilder tiers(final List<CommissionTier> tiers) {
            this.tiers$value = tiers;
            tiers$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public CommissionRule build() {
            List<CommissionTier> tiers$value = this.tiers$value;
            if (!this.tiers$set) tiers$value = CommissionRule.$default$tiers();
            return new CommissionRule(this.name, this.type, this.percentage, this.fixedAmount, this.description, this.isActive, tiers$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "CommissionRule.CommissionRuleBuilder(name=" + this.name + ", type=" + this.type + ", percentage=" + this.percentage + ", fixedAmount=" + this.fixedAmount + ", description=" + this.description + ", isActive=" + this.isActive + ", tiers$value=" + this.tiers$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static CommissionRule.CommissionRuleBuilder builder() {
        return new CommissionRule.CommissionRuleBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public CommissionRule() {
        this.tiers = CommissionRule.$default$tiers();
    }

    @java.lang.SuppressWarnings("all")
    
    public CommissionRule(final String name, final CommissionType type, final BigDecimal percentage, final BigDecimal fixedAmount, final String description, final boolean isActive, final List<CommissionTier> tiers) {
        this.name = name;
        this.type = type;
        this.percentage = percentage;
        this.fixedAmount = fixedAmount;
        this.description = description;
        this.isActive = isActive;
        this.tiers = tiers;
    }
}
