// Generated by delombok at Fri Jul 24 16:18:01 IST 2026
package com.ripplenexus.salespilot.commission.domain;

import com.ripplenexus.salespilot.core.domain.BaseEntity;
import com.ripplenexus.salespilot.deal.domain.Deal;
import com.ripplenexus.salespilot.employee.domain.Employee;
import jakarta.persistence.*;

import java.math.BigDecimal;
import java.time.Instant;

@Entity
@Table(name = "commissions")
public class Commission extends BaseEntity {
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "deal_id", nullable = false)
    private Deal deal;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "employee_id", nullable = false)
    private Employee employee;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rule_id")
    private CommissionRule rule;
    @Column(name = "deal_value", nullable = false, precision = 15, scale = 2)
    private BigDecimal dealValue;
    @Column(name = "commission_amount", nullable = false, precision = 12, scale = 2)
    private BigDecimal commissionAmount;
    @Column(name = "currency", nullable = false)
    private String currency = "INR";
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private CommissionStatus status = CommissionStatus.PENDING;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "approved_by")
    private Employee approvedBy;
    @Column(name = "approved_at")
    private Instant approvedAt;
    @Column(name = "rejection_reason")
    private String rejectionReason;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "paid_by")
    private Employee paidBy;
    @Column(name = "paid_at")
    private Instant paidAt;
    @Column(name = "payment_ref")
    private String paymentRef;
    @Column(name = "notes")
    private String notes;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "payout_id")
    private Payout payout;


    public enum CommissionStatus {
        PENDING, APPROVED, REJECTED, PAID, CANCELLED;
    }

    public Deal getDeal() {
        return deal;
    }

    public void setDeal(Deal deal) {
        this.deal = deal;
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public CommissionRule getRule() {
        return rule;
    }

    public void setRule(CommissionRule rule) {
        this.rule = rule;
    }

    public BigDecimal getDealValue() {
        return dealValue;
    }

    public void setDealValue(BigDecimal dealValue) {
        this.dealValue = dealValue;
    }

    public BigDecimal getCommissionAmount() {
        return commissionAmount;
    }

    public void setCommissionAmount(BigDecimal commissionAmount) {
        this.commissionAmount = commissionAmount;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public CommissionStatus getStatus() {
        return status;
    }

    public void setStatus(CommissionStatus status) {
        this.status = status;
    }

    public Employee getApprovedBy() {
        return approvedBy;
    }

    public void setApprovedBy(Employee approvedBy) {
        this.approvedBy = approvedBy;
    }

    public Instant getApprovedAt() {
        return approvedAt;
    }

    public void setApprovedAt(Instant approvedAt) {
        this.approvedAt = approvedAt;
    }

    public String getRejectionReason() {
        return rejectionReason;
    }

    public void setRejectionReason(String rejectionReason) {
        this.rejectionReason = rejectionReason;
    }

    public Employee getPaidBy() {
        return paidBy;
    }

    public void setPaidBy(Employee paidBy) {
        this.paidBy = paidBy;
    }

    public Instant getPaidAt() {
        return paidAt;
    }

    public void setPaidAt(Instant paidAt) {
        this.paidAt = paidAt;
    }

    public String getPaymentRef() {
        return paymentRef;
    }

    public void setPaymentRef(String paymentRef) {
        this.paymentRef = paymentRef;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Payout getPayout() {
        return payout;
    }

    public void setPayout(Payout payout) {
        this.payout = payout;
    }


    @java.lang.SuppressWarnings("all")
    
    public static class CommissionBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Deal deal;
        @java.lang.SuppressWarnings("all")
        
        private Employee employee;
        @java.lang.SuppressWarnings("all")
        
        private CommissionRule rule;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal dealValue;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal commissionAmount;
        @java.lang.SuppressWarnings("all")
        
        private String currency;
        @java.lang.SuppressWarnings("all")
        
        private CommissionStatus status;
        @java.lang.SuppressWarnings("all")
        
        private Employee approvedBy;
        @java.lang.SuppressWarnings("all")
        
        private Instant approvedAt;
        @java.lang.SuppressWarnings("all")
        
        private String rejectionReason;
        @java.lang.SuppressWarnings("all")
        
        private Employee paidBy;
        @java.lang.SuppressWarnings("all")
        
        private Instant paidAt;
        @java.lang.SuppressWarnings("all")
        
        private String paymentRef;
        @java.lang.SuppressWarnings("all")
        
        private String notes;
        @java.lang.SuppressWarnings("all")
        
        private Payout payout;

        @java.lang.SuppressWarnings("all")
        
        CommissionBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Commission.CommissionBuilder deal(final Deal deal) {
            this.deal = deal;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Commission.CommissionBuilder employee(final Employee employee) {
            this.employee = employee;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Commission.CommissionBuilder rule(final CommissionRule rule) {
            this.rule = rule;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Commission.CommissionBuilder dealValue(final BigDecimal dealValue) {
            this.dealValue = dealValue;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Commission.CommissionBuilder commissionAmount(final BigDecimal commissionAmount) {
            this.commissionAmount = commissionAmount;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Commission.CommissionBuilder currency(final String currency) {
            this.currency = currency;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Commission.CommissionBuilder status(final CommissionStatus status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Commission.CommissionBuilder approvedBy(final Employee approvedBy) {
            this.approvedBy = approvedBy;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Commission.CommissionBuilder approvedAt(final Instant approvedAt) {
            this.approvedAt = approvedAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Commission.CommissionBuilder rejectionReason(final String rejectionReason) {
            this.rejectionReason = rejectionReason;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Commission.CommissionBuilder paidBy(final Employee paidBy) {
            this.paidBy = paidBy;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Commission.CommissionBuilder paidAt(final Instant paidAt) {
            this.paidAt = paidAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Commission.CommissionBuilder paymentRef(final String paymentRef) {
            this.paymentRef = paymentRef;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Commission.CommissionBuilder notes(final String notes) {
            this.notes = notes;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Commission.CommissionBuilder payout(final Payout payout) {
            this.payout = payout;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Commission build() {
            return new Commission(this.deal, this.employee, this.rule, this.dealValue, this.commissionAmount, this.currency, this.status, this.approvedBy, this.approvedAt, this.rejectionReason, this.paidBy, this.paidAt, this.paymentRef, this.notes, this.payout);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Commission.CommissionBuilder(deal=" + this.deal + ", employee=" + this.employee + ", rule=" + this.rule + ", dealValue=" + this.dealValue + ", commissionAmount=" + this.commissionAmount + ", currency=" + this.currency + ", status=" + this.status + ", approvedBy=" + this.approvedBy + ", approvedAt=" + this.approvedAt + ", rejectionReason=" + this.rejectionReason + ", paidBy=" + this.paidBy + ", paidAt=" + this.paidAt + ", paymentRef=" + this.paymentRef + ", notes=" + this.notes + ", payout=" + this.payout + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static Commission.CommissionBuilder builder() {
        return new Commission.CommissionBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Commission() {
    }

    @java.lang.SuppressWarnings("all")
    
    public Commission(final Deal deal, final Employee employee, final CommissionRule rule, final BigDecimal dealValue, final BigDecimal commissionAmount, final String currency, final CommissionStatus status, final Employee approvedBy, final Instant approvedAt, final String rejectionReason, final Employee paidBy, final Instant paidAt, final String paymentRef, final String notes, final Payout payout) {
        this.deal = deal;
        this.employee = employee;
        this.rule = rule;
        this.dealValue = dealValue;
        this.commissionAmount = commissionAmount;
        this.currency = currency;
        this.status = status;
        this.approvedBy = approvedBy;
        this.approvedAt = approvedAt;
        this.rejectionReason = rejectionReason;
        this.paidBy = paidBy;
        this.paidAt = paidAt;
        this.paymentRef = paymentRef;
        this.notes = notes;
        this.payout = payout;
    }
}
