// Generated by delombok at Fri Jul 24 16:18:01 IST 2026
package com.ripplenexus.salespilot.commission.domain;

import jakarta.persistence.*;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

@Entity
@Table(name = "commission_tiers")
public class CommissionTier {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rule_id", nullable = false)
    private CommissionRule rule;
    @Column(name = "min_amount", nullable = false, precision = 15, scale = 2)
    private BigDecimal minAmount;
    @Column(name = "max_amount", precision = 15, scale = 2)
    private BigDecimal maxAmount;
    @Column(name = "percentage", precision = 5, scale = 2)
    private BigDecimal percentage;
    @Column(name = "fixed_amount", precision = 12, scale = 2)
    private BigDecimal fixedAmount;
    @Column(name = "tier_order", nullable = false)
    private int tierOrder;
    @Column(name = "created_at", nullable = false)
    private Instant createdAt = Instant.now();

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public CommissionRule getRule() {
        return rule;
    }

    public void setRule(CommissionRule rule) {
        this.rule = rule;
    }

    public BigDecimal getMinAmount() {
        return minAmount;
    }

    public void setMinAmount(BigDecimal minAmount) {
        this.minAmount = minAmount;
    }

    public BigDecimal getMaxAmount() {
        return maxAmount;
    }

    public void setMaxAmount(BigDecimal maxAmount) {
        this.maxAmount = maxAmount;
    }

    public BigDecimal getPercentage() {
        return percentage;
    }

    public void setPercentage(BigDecimal percentage) {
        this.percentage = percentage;
    }

    public BigDecimal getFixedAmount() {
        return fixedAmount;
    }

    public void setFixedAmount(BigDecimal fixedAmount) {
        this.fixedAmount = fixedAmount;
    }

    public int getTierOrder() {
        return tierOrder;
    }

    public void setTierOrder(int tierOrder) {
        this.tierOrder = tierOrder;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }


    @java.lang.SuppressWarnings("all")
    
    public static class CommissionTierBuilder {
        @java.lang.SuppressWarnings("all")
        
        private UUID id;
        @java.lang.SuppressWarnings("all")
        
        private CommissionRule rule;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal minAmount;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal maxAmount;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal percentage;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal fixedAmount;
        @java.lang.SuppressWarnings("all")
        
        private int tierOrder;
        @java.lang.SuppressWarnings("all")
        
        private Instant createdAt;

        @java.lang.SuppressWarnings("all")
        
        CommissionTierBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public CommissionTier.CommissionTierBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public CommissionTier.CommissionTierBuilder rule(final CommissionRule rule) {
            this.rule = rule;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public CommissionTier.CommissionTierBuilder minAmount(final BigDecimal minAmount) {
            this.minAmount = minAmount;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public CommissionTier.CommissionTierBuilder maxAmount(final BigDecimal maxAmount) {
            this.maxAmount = maxAmount;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public CommissionTier.CommissionTierBuilder percentage(final BigDecimal percentage) {
            this.percentage = percentage;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public CommissionTier.CommissionTierBuilder fixedAmount(final BigDecimal fixedAmount) {
            this.fixedAmount = fixedAmount;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public CommissionTier.CommissionTierBuilder tierOrder(final int tierOrder) {
            this.tierOrder = tierOrder;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public CommissionTier.CommissionTierBuilder createdAt(final Instant createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public CommissionTier build() {
            return new CommissionTier(this.id, this.rule, this.minAmount, this.maxAmount, this.percentage, this.fixedAmount, this.tierOrder, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "CommissionTier.CommissionTierBuilder(id=" + this.id + ", rule=" + this.rule + ", minAmount=" + this.minAmount + ", maxAmount=" + this.maxAmount + ", percentage=" + this.percentage + ", fixedAmount=" + this.fixedAmount + ", tierOrder=" + this.tierOrder + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static CommissionTier.CommissionTierBuilder builder() {
        return new CommissionTier.CommissionTierBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public CommissionTier() {
    }

    @java.lang.SuppressWarnings("all")
    
    public CommissionTier(final UUID id, final CommissionRule rule, final BigDecimal minAmount, final BigDecimal maxAmount, final BigDecimal percentage, final BigDecimal fixedAmount, final int tierOrder, final Instant createdAt) {
        this.id = id;
        this.rule = rule;
        this.minAmount = minAmount;
        this.maxAmount = maxAmount;
        this.percentage = percentage;
        this.fixedAmount = fixedAmount;
        this.tierOrder = tierOrder;
        this.createdAt = createdAt;
    }
}
