// Generated by delombok at Fri Jul 24 16:18:01 IST 2026
package com.ripplenexus.salespilot.commission.domain;

import com.ripplenexus.salespilot.employee.domain.Employee;
import jakarta.persistence.*;

import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

@Entity
@Table(name = "employee_commission_plans")
public class EmployeeCommissionPlan {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "employee_id", nullable = false)
    private Employee employee;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rule_id", nullable = false)
    private CommissionRule rule;
    @Column(name = "effective_from", nullable = false)
    private LocalDate effectiveFrom;
    @Column(name = "effective_to")
    private LocalDate effectiveTo;
    @Column(name = "is_active", nullable = false)
    private boolean isActive = true;
    @Column(name = "created_at", nullable = false)
    private Instant createdAt = Instant.now();
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt = Instant.now();

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public CommissionRule getRule() {
        return rule;
    }

    public void setRule(CommissionRule rule) {
        this.rule = rule;
    }

    public LocalDate getEffectiveFrom() {
        return effectiveFrom;
    }

    public void setEffectiveFrom(LocalDate effectiveFrom) {
        this.effectiveFrom = effectiveFrom;
    }

    public LocalDate getEffectiveTo() {
        return effectiveTo;
    }

    public void setEffectiveTo(LocalDate effectiveTo) {
        this.effectiveTo = effectiveTo;
    }

    public boolean isActive() {
        return isActive;
    }

    public void setActive(boolean active) {
        isActive = active;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }


    @java.lang.SuppressWarnings("all")
    
    public static class EmployeeCommissionPlanBuilder {
        @java.lang.SuppressWarnings("all")
        
        private UUID id;
        @java.lang.SuppressWarnings("all")
        
        private Employee employee;
        @java.lang.SuppressWarnings("all")
        
        private CommissionRule rule;
        @java.lang.SuppressWarnings("all")
        
        private LocalDate effectiveFrom;
        @java.lang.SuppressWarnings("all")
        
        private LocalDate effectiveTo;
        @java.lang.SuppressWarnings("all")
        
        private boolean isActive;
        @java.lang.SuppressWarnings("all")
        
        private Instant createdAt;
        @java.lang.SuppressWarnings("all")
        
        private Instant updatedAt;

        @java.lang.SuppressWarnings("all")
        
        EmployeeCommissionPlanBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public EmployeeCommissionPlan.EmployeeCommissionPlanBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public EmployeeCommissionPlan.EmployeeCommissionPlanBuilder employee(final Employee employee) {
            this.employee = employee;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public EmployeeCommissionPlan.EmployeeCommissionPlanBuilder rule(final CommissionRule rule) {
            this.rule = rule;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public EmployeeCommissionPlan.EmployeeCommissionPlanBuilder effectiveFrom(final LocalDate effectiveFrom) {
            this.effectiveFrom = effectiveFrom;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public EmployeeCommissionPlan.EmployeeCommissionPlanBuilder effectiveTo(final LocalDate effectiveTo) {
            this.effectiveTo = effectiveTo;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public EmployeeCommissionPlan.EmployeeCommissionPlanBuilder isActive(final boolean isActive) {
            this.isActive = isActive;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public EmployeeCommissionPlan.EmployeeCommissionPlanBuilder createdAt(final Instant createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public EmployeeCommissionPlan.EmployeeCommissionPlanBuilder updatedAt(final Instant updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public EmployeeCommissionPlan build() {
            return new EmployeeCommissionPlan(this.id, this.employee, this.rule, this.effectiveFrom, this.effectiveTo, this.isActive, this.createdAt, this.updatedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "EmployeeCommissionPlan.EmployeeCommissionPlanBuilder(id=" + this.id + ", employee=" + this.employee + ", rule=" + this.rule + ", effectiveFrom=" + this.effectiveFrom + ", effectiveTo=" + this.effectiveTo + ", isActive=" + this.isActive + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static EmployeeCommissionPlan.EmployeeCommissionPlanBuilder builder() {
        return new EmployeeCommissionPlan.EmployeeCommissionPlanBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public EmployeeCommissionPlan() {
    }

    @java.lang.SuppressWarnings("all")
    
    public EmployeeCommissionPlan(final UUID id, final Employee employee, final CommissionRule rule, final LocalDate effectiveFrom, final LocalDate effectiveTo, final boolean isActive, final Instant createdAt, final Instant updatedAt) {
        this.id = id;
        this.employee = employee;
        this.rule = rule;
        this.effectiveFrom = effectiveFrom;
        this.effectiveTo = effectiveTo;
        this.isActive = isActive;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
