// Generated by delombok at Fri Jul 24 16:18:01 IST 2026
package com.ripplenexus.salespilot.commission.domain;

import com.ripplenexus.salespilot.core.domain.BaseEntity;
import com.ripplenexus.salespilot.employee.domain.Employee;
import jakarta.persistence.*;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.ZonedDateTime;

@Entity
@Table(name = "payouts")
public class Payout extends BaseEntity {
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "employee_id", nullable = false)
    private Employee employee;
    @Column(name = "amount", nullable = false, precision = 12, scale = 2)
    private BigDecimal amount;
    @Column(name = "base_salary", precision = 12, scale = 2)
    private BigDecimal baseSalary;
    @Column(name = "total_commission", precision = 12, scale = 2)
    private BigDecimal totalCommission;
    @Column(name = "payout_period", nullable = false)
    private String payoutPeriod;
    @Column(name = "payout_date", nullable = false)
    private LocalDate payoutDate;
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private Commission.CommissionStatus status;
    @Column(name = "bank_name")
    private String bankName;
    @Column(name = "bank_account")
    private String bankAccount;
    @Column(name = "bank_ifsc")
    private String bankIfsc;
    @Column(name = "paid_at")
    private ZonedDateTime paidAt;
    @Column(name = "payment_ref")
    private String paymentRef;
    @Column(name = "notes")
    private String notes;

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public BigDecimal getBaseSalary() {
        return baseSalary;
    }

    public void setBaseSalary(BigDecimal baseSalary) {
        this.baseSalary = baseSalary;
    }

    public BigDecimal getTotalCommission() {
        return totalCommission;
    }

    public void setTotalCommission(BigDecimal totalCommission) {
        this.totalCommission = totalCommission;
    }

    public String getPayoutPeriod() {
        return payoutPeriod;
    }

    public void setPayoutPeriod(String payoutPeriod) {
        this.payoutPeriod = payoutPeriod;
    }

    public LocalDate getPayoutDate() {
        return payoutDate;
    }

    public void setPayoutDate(LocalDate payoutDate) {
        this.payoutDate = payoutDate;
    }

    public Commission.CommissionStatus getStatus() {
        return status;
    }

    public void setStatus(Commission.CommissionStatus status) {
        this.status = status;
    }

    public String getBankName() {
        return bankName;
    }

    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    public String getBankAccount() {
        return bankAccount;
    }

    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount;
    }

    public String getBankIfsc() {
        return bankIfsc;
    }

    public void setBankIfsc(String bankIfsc) {
        this.bankIfsc = bankIfsc;
    }

    public ZonedDateTime getPaidAt() {
        return paidAt;
    }

    public void setPaidAt(ZonedDateTime paidAt) {
        this.paidAt = paidAt;
    }

    public String getPaymentRef() {
        return paymentRef;
    }

    public void setPaymentRef(String paymentRef) {
        this.paymentRef = paymentRef;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    @java.lang.SuppressWarnings("all")
    
    private static BigDecimal $default$baseSalary() {
        return BigDecimal.ZERO;
    }

    @java.lang.SuppressWarnings("all")
    
    private static BigDecimal $default$totalCommission() {
        return BigDecimal.ZERO;
    }

    @java.lang.SuppressWarnings("all")
    
    private static Commission.CommissionStatus $default$status() {
        return Commission.CommissionStatus.PENDING;
    }


    @java.lang.SuppressWarnings("all")
    
    public static class PayoutBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Employee employee;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal amount;
        @java.lang.SuppressWarnings("all")
        
        private boolean baseSalary$set;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal baseSalary$value;
        @java.lang.SuppressWarnings("all")
        
        private boolean totalCommission$set;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal totalCommission$value;
        @java.lang.SuppressWarnings("all")
        
        private String payoutPeriod;
        @java.lang.SuppressWarnings("all")
        
        private LocalDate payoutDate;
        @java.lang.SuppressWarnings("all")
        
        private boolean status$set;
        @java.lang.SuppressWarnings("all")
        
        private Commission.CommissionStatus status$value;
        @java.lang.SuppressWarnings("all")
        
        private String bankName;
        @java.lang.SuppressWarnings("all")
        
        private String bankAccount;
        @java.lang.SuppressWarnings("all")
        
        private String bankIfsc;
        @java.lang.SuppressWarnings("all")
        
        private ZonedDateTime paidAt;
        @java.lang.SuppressWarnings("all")
        
        private String paymentRef;
        @java.lang.SuppressWarnings("all")
        
        private String notes;

        @java.lang.SuppressWarnings("all")
        
        PayoutBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Payout.PayoutBuilder employee(final Employee employee) {
            this.employee = employee;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Payout.PayoutBuilder amount(final BigDecimal amount) {
            this.amount = amount;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Payout.PayoutBuilder baseSalary(final BigDecimal baseSalary) {
            this.baseSalary$value = baseSalary;
            baseSalary$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Payout.PayoutBuilder totalCommission(final BigDecimal totalCommission) {
            this.totalCommission$value = totalCommission;
            totalCommission$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Payout.PayoutBuilder payoutPeriod(final String payoutPeriod) {
            this.payoutPeriod = payoutPeriod;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Payout.PayoutBuilder payoutDate(final LocalDate payoutDate) {
            this.payoutDate = payoutDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Payout.PayoutBuilder status(final Commission.CommissionStatus status) {
            this.status$value = status;
            status$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Payout.PayoutBuilder bankName(final String bankName) {
            this.bankName = bankName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Payout.PayoutBuilder bankAccount(final String bankAccount) {
            this.bankAccount = bankAccount;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Payout.PayoutBuilder bankIfsc(final String bankIfsc) {
            this.bankIfsc = bankIfsc;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Payout.PayoutBuilder paidAt(final ZonedDateTime paidAt) {
            this.paidAt = paidAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Payout.PayoutBuilder paymentRef(final String paymentRef) {
            this.paymentRef = paymentRef;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Payout.PayoutBuilder notes(final String notes) {
            this.notes = notes;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Payout build() {
            BigDecimal baseSalary$value = this.baseSalary$value;
            if (!this.baseSalary$set) baseSalary$value = Payout.$default$baseSalary();
            BigDecimal totalCommission$value = this.totalCommission$value;
            if (!this.totalCommission$set) totalCommission$value = Payout.$default$totalCommission();
            Commission.CommissionStatus status$value = this.status$value;
            if (!this.status$set) status$value = Payout.$default$status();
            return new Payout(this.employee, this.amount, baseSalary$value, totalCommission$value, this.payoutPeriod, this.payoutDate, status$value, this.bankName, this.bankAccount, this.bankIfsc, this.paidAt, this.paymentRef, this.notes);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Payout.PayoutBuilder(employee=" + this.employee + ", amount=" + this.amount + ", baseSalary$value=" + this.baseSalary$value + ", totalCommission$value=" + this.totalCommission$value + ", payoutPeriod=" + this.payoutPeriod + ", payoutDate=" + this.payoutDate + ", status$value=" + this.status$value + ", bankName=" + this.bankName + ", bankAccount=" + this.bankAccount + ", bankIfsc=" + this.bankIfsc + ", paidAt=" + this.paidAt + ", paymentRef=" + this.paymentRef + ", notes=" + this.notes + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static Payout.PayoutBuilder builder() {
        return new Payout.PayoutBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Payout() {
        this.baseSalary = Payout.$default$baseSalary();
        this.totalCommission = Payout.$default$totalCommission();
        this.status = Payout.$default$status();
    }

    @java.lang.SuppressWarnings("all")
    
    public Payout(final Employee employee, final BigDecimal amount, final BigDecimal baseSalary, final BigDecimal totalCommission, final String payoutPeriod, final LocalDate payoutDate, final Commission.CommissionStatus status, final String bankName, final String bankAccount, final String bankIfsc, final ZonedDateTime paidAt, final String paymentRef, final String notes) {
        this.employee = employee;
        this.amount = amount;
        this.baseSalary = baseSalary;
        this.totalCommission = totalCommission;
        this.payoutPeriod = payoutPeriod;
        this.payoutDate = payoutDate;
        this.status = status;
        this.bankName = bankName;
        this.bankAccount = bankAccount;
        this.bankIfsc = bankIfsc;
        this.paidAt = paidAt;
        this.paymentRef = paymentRef;
        this.notes = notes;
    }
}
