// Generated by delombok at Fri Jul 24 16:18:05 IST 2026
package com.ripplenexus.salespilot.lead.domain;

import com.ripplenexus.salespilot.core.domain.BaseEntity;
import jakarta.persistence.*;

import java.math.BigDecimal;

@Entity
@Table(name = "companies")
public class Company extends BaseEntity {
    @Column(name = "name", nullable = false)
    private String name;
    @Column(name = "website")
    private String website;
    @Column(name = "industry")
    private String industry;
    @Column(name = "employee_count")
    private Integer employeeCount;
    @Column(name = "annual_revenue")
    private BigDecimal annualRevenue;
    @Column(name = "country")
    private String country;
    @Column(name = "city")
    private String city;
    @Column(name = "address", columnDefinition = "TEXT")
    private String address;
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getWebsite() {
        return website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    public String getIndustry() {
        return industry;
    }

    public void setIndustry(String industry) {
        this.industry = industry;
    }

    public Integer getEmployeeCount() {
        return employeeCount;
    }

    public void setEmployeeCount(Integer employeeCount) {
        this.employeeCount = employeeCount;
    }

    public BigDecimal getAnnualRevenue() {
        return annualRevenue;
    }

    public void setAnnualRevenue(BigDecimal annualRevenue) {
        this.annualRevenue = annualRevenue;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }


    @java.lang.SuppressWarnings("all")
    
    public static class CompanyBuilder {
        @java.lang.SuppressWarnings("all")
        
        private String name;
        @java.lang.SuppressWarnings("all")
        
        private String website;
        @java.lang.SuppressWarnings("all")
        
        private String industry;
        @java.lang.SuppressWarnings("all")
        
        private Integer employeeCount;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal annualRevenue;
        @java.lang.SuppressWarnings("all")
        
        private String country;
        @java.lang.SuppressWarnings("all")
        
        private String city;
        @java.lang.SuppressWarnings("all")
        
        private String address;
        @java.lang.SuppressWarnings("all")
        
        private String notes;

        @java.lang.SuppressWarnings("all")
        
        CompanyBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Company.CompanyBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Company.CompanyBuilder website(final String website) {
            this.website = website;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Company.CompanyBuilder industry(final String industry) {
            this.industry = industry;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Company.CompanyBuilder employeeCount(final Integer employeeCount) {
            this.employeeCount = employeeCount;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Company.CompanyBuilder annualRevenue(final BigDecimal annualRevenue) {
            this.annualRevenue = annualRevenue;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Company.CompanyBuilder country(final String country) {
            this.country = country;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Company.CompanyBuilder city(final String city) {
            this.city = city;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Company.CompanyBuilder address(final String address) {
            this.address = address;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Company.CompanyBuilder notes(final String notes) {
            this.notes = notes;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Company build() {
            return new Company(this.name, this.website, this.industry, this.employeeCount, this.annualRevenue, this.country, this.city, this.address, this.notes);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Company.CompanyBuilder(name=" + this.name + ", website=" + this.website + ", industry=" + this.industry + ", employeeCount=" + this.employeeCount + ", annualRevenue=" + this.annualRevenue + ", country=" + this.country + ", city=" + this.city + ", address=" + this.address + ", notes=" + this.notes + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static Company.CompanyBuilder builder() {
        return new Company.CompanyBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Company() {
    }

    @java.lang.SuppressWarnings("all")
    
    public Company(final String name, final String website, final String industry, final Integer employeeCount, final BigDecimal annualRevenue, final String country, final String city, final String address, final String notes) {
        this.name = name;
        this.website = website;
        this.industry = industry;
        this.employeeCount = employeeCount;
        this.annualRevenue = annualRevenue;
        this.country = country;
        this.city = city;
        this.address = address;
        this.notes = notes;
    }
}
