// Generated by delombok at Fri Jul 24 16:18:05 IST 2026
package com.ripplenexus.salespilot.lead.domain;

import com.ripplenexus.salespilot.core.domain.BaseEntity;
import jakarta.persistence.*;


@Entity
@Table(name = "contacts")
public class Contact extends BaseEntity {
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id")
    private Company company;
    @Column(name = "first_name", nullable = false)
    private String firstName;
    @Column(name = "last_name")
    private String lastName;
    @Column(name = "designation")
    private String designation;
    @Column(name = "email")
    private String email;
    @Column(name = "phone")
    private String phone;
    @Column(name = "whatsapp")
    private String whatsapp;
    @Column(name = "linkedin_url")
    private String linkedinUrl;
    @Column(name = "country")
    private String country;
    @Column(name = "city")
    private String city;
    @Column(name = "is_decision_maker", nullable = false)
    private boolean isDecisionMaker = false;
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getDesignation() {
        return designation;
    }

    public void setDesignation(String designation) {
        this.designation = designation;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getWhatsapp() {
        return whatsapp;
    }

    public void setWhatsapp(String whatsapp) {
        this.whatsapp = whatsapp;
    }

    public String getLinkedinUrl() {
        return linkedinUrl;
    }

    public void setLinkedinUrl(String linkedinUrl) {
        this.linkedinUrl = linkedinUrl;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public boolean isDecisionMaker() {
        return isDecisionMaker;
    }

    public void setDecisionMaker(boolean decisionMaker) {
        isDecisionMaker = decisionMaker;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }


    @java.lang.SuppressWarnings("all")
    
    public static class ContactBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Company company;
        @java.lang.SuppressWarnings("all")
        
        private String firstName;
        @java.lang.SuppressWarnings("all")
        
        private String lastName;
        @java.lang.SuppressWarnings("all")
        
        private String designation;
        @java.lang.SuppressWarnings("all")
        
        private String email;
        @java.lang.SuppressWarnings("all")
        
        private String phone;
        @java.lang.SuppressWarnings("all")
        
        private String whatsapp;
        @java.lang.SuppressWarnings("all")
        
        private String linkedinUrl;
        @java.lang.SuppressWarnings("all")
        
        private String country;
        @java.lang.SuppressWarnings("all")
        
        private String city;
        @java.lang.SuppressWarnings("all")
        
        private boolean isDecisionMaker;
        @java.lang.SuppressWarnings("all")
        
        private String notes;

        @java.lang.SuppressWarnings("all")
        
        ContactBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Contact.ContactBuilder company(final Company company) {
            this.company = company;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Contact.ContactBuilder firstName(final String firstName) {
            this.firstName = firstName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Contact.ContactBuilder lastName(final String lastName) {
            this.lastName = lastName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Contact.ContactBuilder designation(final String designation) {
            this.designation = designation;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Contact.ContactBuilder email(final String email) {
            this.email = email;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Contact.ContactBuilder phone(final String phone) {
            this.phone = phone;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Contact.ContactBuilder whatsapp(final String whatsapp) {
            this.whatsapp = whatsapp;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Contact.ContactBuilder linkedinUrl(final String linkedinUrl) {
            this.linkedinUrl = linkedinUrl;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Contact.ContactBuilder country(final String country) {
            this.country = country;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Contact.ContactBuilder city(final String city) {
            this.city = city;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Contact.ContactBuilder isDecisionMaker(final boolean isDecisionMaker) {
            this.isDecisionMaker = isDecisionMaker;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Contact.ContactBuilder notes(final String notes) {
            this.notes = notes;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Contact build() {
            return new Contact(this.company, this.firstName, this.lastName, this.designation, this.email, this.phone, this.whatsapp, this.linkedinUrl, this.country, this.city, this.isDecisionMaker, this.notes);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Contact.ContactBuilder(company=" + this.company + ", firstName=" + this.firstName + ", lastName=" + this.lastName + ", designation=" + this.designation + ", email=" + this.email + ", phone=" + this.phone + ", whatsapp=" + this.whatsapp + ", linkedinUrl=" + this.linkedinUrl + ", country=" + this.country + ", city=" + this.city + ", isDecisionMaker=" + this.isDecisionMaker + ", notes=" + this.notes + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static Contact.ContactBuilder builder() {
        return new Contact.ContactBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Contact() {
    }

    @java.lang.SuppressWarnings("all")
    
    public Contact(final Company company, final String firstName, final String lastName, final String designation, final String email, final String phone, final String whatsapp, final String linkedinUrl, final String country, final String city, final boolean isDecisionMaker, final String notes) {
        this.company = company;
        this.firstName = firstName;
        this.lastName = lastName;
        this.designation = designation;
        this.email = email;
        this.phone = phone;
        this.whatsapp = whatsapp;
        this.linkedinUrl = linkedinUrl;
        this.country = country;
        this.city = city;
        this.isDecisionMaker = isDecisionMaker;
        this.notes = notes;
    }
}
