// Generated by delombok at Fri Jul 24 16:18:05 IST 2026
package com.ripplenexus.salespilot.lead.domain;

import com.ripplenexus.salespilot.core.domain.BaseEntity;
import jakarta.persistence.*;

import java.math.BigDecimal;
import java.util.List;

@Entity
@Table(name = "icps")
public class IdealCustomerProfile extends BaseEntity {
    @Column(name = "name", nullable = false)
    private String name;
    @Column(name = "industry")
    private String industry;
    @Column(name = "company_size_min")
    private Integer companySizeMin;
    @Column(name = "company_size_max")
    private Integer companySizeMax;
    @Column(name = "revenue_min", precision = 15, scale = 2)
    private BigDecimal revenueMin;
    @Column(name = "revenue_max", precision = 15, scale = 2)
    private BigDecimal revenueMax;
    @org.hibernate.annotations.JdbcTypeCode(org.hibernate.type.SqlTypes.ARRAY)
    @Column(name = "decision_makers")
    private List<String> decisionMakers;
    @org.hibernate.annotations.JdbcTypeCode(org.hibernate.type.SqlTypes.ARRAY)
    @Column(name = "pain_points")
    private List<String> painPoints;
    @org.hibernate.annotations.JdbcTypeCode(org.hibernate.type.SqlTypes.ARRAY)
    @Column(name = "interested_services")
    private List<String> interestedServices;
    @Enumerated(EnumType.STRING)
    @Column(name = "priority", nullable = false)
    private IcpPriority priority;
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;
    @Column(name = "is_active", nullable = false)
    private Boolean isActive;


    public enum IcpPriority {
        LOW, MEDIUM, HIGH, URGENT;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIndustry() {
        return industry;
    }

    public void setIndustry(String industry) {
        this.industry = industry;
    }

    public Integer getCompanySizeMin() {
        return companySizeMin;
    }

    public void setCompanySizeMin(Integer companySizeMin) {
        this.companySizeMin = companySizeMin;
    }

    public Integer getCompanySizeMax() {
        return companySizeMax;
    }

    public void setCompanySizeMax(Integer companySizeMax) {
        this.companySizeMax = companySizeMax;
    }

    public BigDecimal getRevenueMin() {
        return revenueMin;
    }

    public void setRevenueMin(BigDecimal revenueMin) {
        this.revenueMin = revenueMin;
    }

    public BigDecimal getRevenueMax() {
        return revenueMax;
    }

    public void setRevenueMax(BigDecimal revenueMax) {
        this.revenueMax = revenueMax;
    }

    public List<String> getDecisionMakers() {
        return decisionMakers;
    }

    public void setDecisionMakers(List<String> decisionMakers) {
        this.decisionMakers = decisionMakers;
    }

    public List<String> getPainPoints() {
        return painPoints;
    }

    public void setPainPoints(List<String> painPoints) {
        this.painPoints = painPoints;
    }

    public List<String> getInterestedServices() {
        return interestedServices;
    }

    public void setInterestedServices(List<String> interestedServices) {
        this.interestedServices = interestedServices;
    }

    public IcpPriority getPriority() {
        return priority;
    }

    public void setPriority(IcpPriority priority) {
        this.priority = priority;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Boolean getIsActive() {
        return isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    @java.lang.SuppressWarnings("all")
    
    private static IcpPriority $default$priority() {
        return IcpPriority.MEDIUM;
    }

    @java.lang.SuppressWarnings("all")
    
    private static Boolean $default$isActive() {
        return true;
    }


    @java.lang.SuppressWarnings("all")
    
    public static class IdealCustomerProfileBuilder {
        @java.lang.SuppressWarnings("all")
        
        private String name;
        @java.lang.SuppressWarnings("all")
        
        private String industry;
        @java.lang.SuppressWarnings("all")
        
        private Integer companySizeMin;
        @java.lang.SuppressWarnings("all")
        
        private Integer companySizeMax;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal revenueMin;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal revenueMax;
        @java.lang.SuppressWarnings("all")
        
        private List<String> decisionMakers;
        @java.lang.SuppressWarnings("all")
        
        private List<String> painPoints;
        @java.lang.SuppressWarnings("all")
        
        private List<String> interestedServices;
        @java.lang.SuppressWarnings("all")
        
        private boolean priority$set;
        @java.lang.SuppressWarnings("all")
        
        private IcpPriority priority$value;
        @java.lang.SuppressWarnings("all")
        
        private String description;
        @java.lang.SuppressWarnings("all")
        
        private boolean isActive$set;
        @java.lang.SuppressWarnings("all")
        
        private Boolean isActive$value;

        @java.lang.SuppressWarnings("all")
        
        IdealCustomerProfileBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public IdealCustomerProfile.IdealCustomerProfileBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public IdealCustomerProfile.IdealCustomerProfileBuilder industry(final String industry) {
            this.industry = industry;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public IdealCustomerProfile.IdealCustomerProfileBuilder companySizeMin(final Integer companySizeMin) {
            this.companySizeMin = companySizeMin;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public IdealCustomerProfile.IdealCustomerProfileBuilder companySizeMax(final Integer companySizeMax) {
            this.companySizeMax = companySizeMax;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public IdealCustomerProfile.IdealCustomerProfileBuilder revenueMin(final BigDecimal revenueMin) {
            this.revenueMin = revenueMin;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public IdealCustomerProfile.IdealCustomerProfileBuilder revenueMax(final BigDecimal revenueMax) {
            this.revenueMax = revenueMax;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public IdealCustomerProfile.IdealCustomerProfileBuilder decisionMakers(final List<String> decisionMakers) {
            this.decisionMakers = decisionMakers;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public IdealCustomerProfile.IdealCustomerProfileBuilder painPoints(final List<String> painPoints) {
            this.painPoints = painPoints;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public IdealCustomerProfile.IdealCustomerProfileBuilder interestedServices(final List<String> interestedServices) {
            this.interestedServices = interestedServices;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public IdealCustomerProfile.IdealCustomerProfileBuilder priority(final IcpPriority priority) {
            this.priority$value = priority;
            priority$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public IdealCustomerProfile.IdealCustomerProfileBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public IdealCustomerProfile.IdealCustomerProfileBuilder isActive(final Boolean isActive) {
            this.isActive$value = isActive;
            isActive$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public IdealCustomerProfile build() {
            IcpPriority priority$value = this.priority$value;
            if (!this.priority$set) priority$value = IdealCustomerProfile.$default$priority();
            Boolean isActive$value = this.isActive$value;
            if (!this.isActive$set) isActive$value = IdealCustomerProfile.$default$isActive();
            return new IdealCustomerProfile(this.name, this.industry, this.companySizeMin, this.companySizeMax, this.revenueMin, this.revenueMax, this.decisionMakers, this.painPoints, this.interestedServices, priority$value, this.description, isActive$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "IdealCustomerProfile.IdealCustomerProfileBuilder(name=" + this.name + ", industry=" + this.industry + ", companySizeMin=" + this.companySizeMin + ", companySizeMax=" + this.companySizeMax + ", revenueMin=" + this.revenueMin + ", revenueMax=" + this.revenueMax + ", decisionMakers=" + this.decisionMakers + ", painPoints=" + this.painPoints + ", interestedServices=" + this.interestedServices + ", priority$value=" + this.priority$value + ", description=" + this.description + ", isActive$value=" + this.isActive$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static IdealCustomerProfile.IdealCustomerProfileBuilder builder() {
        return new IdealCustomerProfile.IdealCustomerProfileBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public IdealCustomerProfile() {
        this.priority = IdealCustomerProfile.$default$priority();
        this.isActive = IdealCustomerProfile.$default$isActive();
    }

    @java.lang.SuppressWarnings("all")
    
    public IdealCustomerProfile(final String name, final String industry, final Integer companySizeMin, final Integer companySizeMax, final BigDecimal revenueMin, final BigDecimal revenueMax, final List<String> decisionMakers, final List<String> painPoints, final List<String> interestedServices, final IcpPriority priority, final String description, final Boolean isActive) {
        this.name = name;
        this.industry = industry;
        this.companySizeMin = companySizeMin;
        this.companySizeMax = companySizeMax;
        this.revenueMin = revenueMin;
        this.revenueMax = revenueMax;
        this.decisionMakers = decisionMakers;
        this.painPoints = painPoints;
        this.interestedServices = interestedServices;
        this.priority = priority;
        this.description = description;
        this.isActive = isActive;
    }
}
