// Generated by delombok at Fri Jul 24 16:18:05 IST 2026
package com.ripplenexus.salespilot.lead.domain;

import jakarta.persistence.*;

import java.time.Instant;
import java.util.UUID;

@Entity
@Table(name = "lead_sources")
public class LeadSource {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;
    @Column(name = "name", nullable = false, unique = true)
    private String name;
    @Column(name = "is_active", nullable = false)
    private boolean isActive = true;
    @Column(name = "created_at", nullable = false)
    private Instant createdAt = Instant.now();

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public boolean isActive() {
        return isActive;
    }

    public void setActive(boolean active) {
        isActive = active;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }


    @java.lang.SuppressWarnings("all")
    
    public static class LeadSourceBuilder {
        @java.lang.SuppressWarnings("all")
        
        private UUID id;
        @java.lang.SuppressWarnings("all")
        
        private String name;
        @java.lang.SuppressWarnings("all")
        
        private boolean isActive;
        @java.lang.SuppressWarnings("all")
        
        private Instant createdAt;

        @java.lang.SuppressWarnings("all")
        
        LeadSourceBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadSource.LeadSourceBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadSource.LeadSourceBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadSource.LeadSourceBuilder isActive(final boolean isActive) {
            this.isActive = isActive;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadSource.LeadSourceBuilder createdAt(final Instant createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public LeadSource build() {
            return new LeadSource(this.id, this.name, this.isActive, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "LeadSource.LeadSourceBuilder(id=" + this.id + ", name=" + this.name + ", isActive=" + this.isActive + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static LeadSource.LeadSourceBuilder builder() {
        return new LeadSource.LeadSourceBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public LeadSource() {
    }

    @java.lang.SuppressWarnings("all")
    
    public LeadSource(final UUID id, final String name, final boolean isActive, final Instant createdAt) {
        this.id = id;
        this.name = name;
        this.isActive = isActive;
        this.createdAt = createdAt;
    }
}
