// Generated by delombok at Fri Jul 24 16:18:04 IST 2026
package com.ripplenexus.salespilot.deal.domain;

import com.ripplenexus.salespilot.core.domain.BaseEntity;
import com.ripplenexus.salespilot.employee.domain.Employee;
import com.ripplenexus.salespilot.lead.domain.Lead;
import jakarta.persistence.*;

import java.math.BigDecimal;
import java.time.Instant;

@Entity
@Table(name = "deals")
public class Deal extends BaseEntity {
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "lead_id", nullable = false, unique = true)
    private Lead lead;
    @Column(name = "deal_number", nullable = false, unique = true)
    private String dealNumber;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "employee_id", nullable = false)
    private Employee employee;
    @Column(name = "deal_value", nullable = false, precision = 15, scale = 2)
    private BigDecimal dealValue;
    @Column(name = "currency", nullable = false)
    private String currency = "INR";
    @Column(name = "invoice_number")
    private String invoiceNumber;
    @Column(name = "closed_at", nullable = false)
    private Instant closedAt;
    @Column(name = "notes")
    private String notes;

    public Lead getLead() {
        return lead;
    }

    public void setLead(Lead lead) {
        this.lead = lead;
    }

    public String getDealNumber() {
        return dealNumber;
    }

    public void setDealNumber(String dealNumber) {
        this.dealNumber = dealNumber;
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public BigDecimal getDealValue() {
        return dealValue;
    }

    public void setDealValue(BigDecimal dealValue) {
        this.dealValue = dealValue;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    public void setInvoiceNumber(String invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
    }

    public Instant getClosedAt() {
        return closedAt;
    }

    public void setClosedAt(Instant closedAt) {
        this.closedAt = closedAt;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    @java.lang.SuppressWarnings("all")
    
    private static Instant $default$closedAt() {
        return Instant.now();
    }


    @java.lang.SuppressWarnings("all")
    
    public static class DealBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Lead lead;
        @java.lang.SuppressWarnings("all")
        
        private String dealNumber;
        @java.lang.SuppressWarnings("all")
        
        private Employee employee;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal dealValue;
        @java.lang.SuppressWarnings("all")
        
        private String currency;
        @java.lang.SuppressWarnings("all")
        
        private String invoiceNumber;
        @java.lang.SuppressWarnings("all")
        
        private boolean closedAt$set;
        @java.lang.SuppressWarnings("all")
        
        private Instant closedAt$value;
        @java.lang.SuppressWarnings("all")
        
        private String notes;

        @java.lang.SuppressWarnings("all")
        
        DealBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Deal.DealBuilder lead(final Lead lead) {
            this.lead = lead;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Deal.DealBuilder dealNumber(final String dealNumber) {
            this.dealNumber = dealNumber;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Deal.DealBuilder employee(final Employee employee) {
            this.employee = employee;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Deal.DealBuilder dealValue(final BigDecimal dealValue) {
            this.dealValue = dealValue;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Deal.DealBuilder currency(final String currency) {
            this.currency = currency;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Deal.DealBuilder invoiceNumber(final String invoiceNumber) {
            this.invoiceNumber = invoiceNumber;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Deal.DealBuilder closedAt(final Instant closedAt) {
            this.closedAt$value = closedAt;
            closedAt$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Deal.DealBuilder notes(final String notes) {
            this.notes = notes;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Deal build() {
            Instant closedAt$value = this.closedAt$value;
            if (!this.closedAt$set) closedAt$value = Deal.$default$closedAt();
            return new Deal(this.lead, this.dealNumber, this.employee, this.dealValue, this.currency, this.invoiceNumber, closedAt$value, this.notes);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Deal.DealBuilder(lead=" + this.lead + ", dealNumber=" + this.dealNumber + ", employee=" + this.employee + ", dealValue=" + this.dealValue + ", currency=" + this.currency + ", invoiceNumber=" + this.invoiceNumber + ", closedAt$value=" + this.closedAt$value + ", notes=" + this.notes + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static Deal.DealBuilder builder() {
        return new Deal.DealBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Deal() {
        this.closedAt = Deal.$default$closedAt();
    }

    @java.lang.SuppressWarnings("all")
    
    public Deal(final Lead lead, final String dealNumber, final Employee employee, final BigDecimal dealValue, final String currency, final String invoiceNumber, final Instant closedAt, final String notes) {
        this.lead = lead;
        this.dealNumber = dealNumber;
        this.employee = employee;
        this.dealValue = dealValue;
        this.currency = currency;
        this.invoiceNumber = invoiceNumber;
        this.closedAt = closedAt;
        this.notes = notes;
    }
}
