// Generated by delombok at Fri Jul 24 16:18:04 IST 2026
package com.ripplenexus.salespilot.deal.domain;

import com.ripplenexus.salespilot.core.domain.BaseEntity;
import jakarta.persistence.*;

import java.math.BigDecimal;
import java.time.Instant;

@Entity
@Table(name = "payments")
public class Payment extends BaseEntity {
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "deal_id", nullable = false)
    private Deal deal;
    @Column(name = "amount", nullable = false, precision = 15, scale = 2)
    private BigDecimal amount;
    @Column(name = "currency", nullable = false)
    private String currency = "INR";
    @Column(name = "payment_date", nullable = false)
    private java.time.LocalDate paymentDate;
    @Enumerated(EnumType.STRING)
    @Column(name = "payment_method")
    private PaymentMethod paymentMethod;
    @Column(name = "transaction_ref")
    private String transactionRef;
    @Column(name = "is_received", nullable = false)
    private Boolean isReceived;
    @Column(name = "remarks", columnDefinition = "TEXT")
    private String remarks;


    public enum PaymentMethod {
        BANK_TRANSFER, CREDIT_CARD, CASH, CHEQUE, ONLINE_GATEWAY;
    }

    public Deal getDeal() {
        return deal;
    }

    public void setDeal(Deal deal) {
        this.deal = deal;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public java.time.LocalDate getPaymentDate() {
        return paymentDate;
    }

    public void setPaymentDate(java.time.LocalDate paymentDate) {
        this.paymentDate = paymentDate;
    }

    public PaymentMethod getPaymentMethod() {
        return paymentMethod;
    }

    public void setPaymentMethod(PaymentMethod paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public String getTransactionRef() {
        return transactionRef;
    }

    public void setTransactionRef(String transactionRef) {
        this.transactionRef = transactionRef;
    }

    public Boolean getIsReceived() {
        return isReceived;
    }

    public void setIsReceived(Boolean isReceived) {
        this.isReceived = isReceived;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @java.lang.SuppressWarnings("all")
    
    private static Boolean $default$isReceived() {
        return true;
    }


    @java.lang.SuppressWarnings("all")
    
    public static class PaymentBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Deal deal;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal amount;
        @java.lang.SuppressWarnings("all")
        
        private String currency;
        @java.lang.SuppressWarnings("all")
        
        private java.time.LocalDate paymentDate;
        @java.lang.SuppressWarnings("all")
        
        private PaymentMethod paymentMethod;
        @java.lang.SuppressWarnings("all")
        
        private String transactionRef;
        @java.lang.SuppressWarnings("all")
        
        private boolean isReceived$set;
        @java.lang.SuppressWarnings("all")
        
        private Boolean isReceived$value;
        @java.lang.SuppressWarnings("all")
        
        private String remarks;

        @java.lang.SuppressWarnings("all")
        
        PaymentBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Payment.PaymentBuilder deal(final Deal deal) {
            this.deal = deal;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Payment.PaymentBuilder amount(final BigDecimal amount) {
            this.amount = amount;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Payment.PaymentBuilder currency(final String currency) {
            this.currency = currency;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Payment.PaymentBuilder paymentDate(final java.time.LocalDate paymentDate) {
            this.paymentDate = paymentDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Payment.PaymentBuilder paymentMethod(final PaymentMethod paymentMethod) {
            this.paymentMethod = paymentMethod;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Payment.PaymentBuilder transactionRef(final String transactionRef) {
            this.transactionRef = transactionRef;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Payment.PaymentBuilder isReceived(final Boolean isReceived) {
            this.isReceived$value = isReceived;
            isReceived$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Payment.PaymentBuilder remarks(final String remarks) {
            this.remarks = remarks;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Payment build() {
            Boolean isReceived$value = this.isReceived$value;
            if (!this.isReceived$set) isReceived$value = Payment.$default$isReceived();
            return new Payment(this.deal, this.amount, this.currency, this.paymentDate, this.paymentMethod, this.transactionRef, isReceived$value, this.remarks);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Payment.PaymentBuilder(deal=" + this.deal + ", amount=" + this.amount + ", currency=" + this.currency + ", paymentDate=" + this.paymentDate + ", paymentMethod=" + this.paymentMethod + ", transactionRef=" + this.transactionRef + ", isReceived$value=" + this.isReceived$value + ", remarks=" + this.remarks + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static Payment.PaymentBuilder builder() {
        return new Payment.PaymentBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Payment() {
        this.isReceived = Payment.$default$isReceived();
    }

    @java.lang.SuppressWarnings("all")
    
    public Payment(final Deal deal, final BigDecimal amount, final String currency, final java.time.LocalDate paymentDate, final PaymentMethod paymentMethod, final String transactionRef, final Boolean isReceived, final String remarks) {
        this.deal = deal;
        this.amount = amount;
        this.currency = currency;
        this.paymentDate = paymentDate;
        this.paymentMethod = paymentMethod;
        this.transactionRef = transactionRef;
        this.isReceived = isReceived;
        this.remarks = remarks;
    }
}
