// Generated by delombok at Fri Jul 24 16:18:04 IST 2026
package com.ripplenexus.salespilot.deal.domain;

import com.ripplenexus.salespilot.core.domain.BaseEntity;
import com.ripplenexus.salespilot.employee.domain.Employee;
import com.ripplenexus.salespilot.lead.domain.Lead;
import jakarta.persistence.*;

import java.math.BigDecimal;
import java.time.Instant;

@Entity
@Table(name = "proposals")
public class Proposal extends BaseEntity {
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "lead_id", nullable = false)
    private Lead lead;
    @Column(name = "type", nullable = false)
    private String type = "PROPOSAL";
    @Column(name = "title", nullable = false)
    private String title;
    @Column(name = "file_name", nullable = false)
    private String fileName;
    @Column(name = "file_path", nullable = false)
    private String filePath;
    @Column(name = "file_size")
    private Long fileSize;
    @Column(name = "mime_type")
    private String mimeType;
    @Column(name = "amount", precision = 15, scale = 2)
    private BigDecimal amount;
    @Column(name = "currency", nullable = false)
    private String currency;
    @Column(name = "version", nullable = false)
    private Integer version;
    @Enumerated(EnumType.STRING)
    @Column(name = "approval_status", nullable = false)
    private ProposalStatus approvalStatus;
    @Column(name = "valid_until")
    private java.time.LocalDate validUntil;
    @Column(name = "notes")
    private String notes;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "uploaded_by")
    private Employee uploadedBy;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "approved_by")
    private Employee approvedBy;
    @Column(name = "approved_at")
    private Instant approvedAt;


    public enum ProposalStatus {
        PENDING, APPROVED, REJECTED;
    }

    public Lead getLead() {
        return lead;
    }

    public void setLead(Lead lead) {
        this.lead = lead;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    public String getMimeType() {
        return mimeType;
    }

    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public ProposalStatus getApprovalStatus() {
        return approvalStatus;
    }

    public void setApprovalStatus(ProposalStatus approvalStatus) {
        this.approvalStatus = approvalStatus;
    }

    public java.time.LocalDate getValidUntil() {
        return validUntil;
    }

    public void setValidUntil(java.time.LocalDate validUntil) {
        this.validUntil = validUntil;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Employee getUploadedBy() {
        return uploadedBy;
    }

    public void setUploadedBy(Employee uploadedBy) {
        this.uploadedBy = uploadedBy;
    }

    public Employee getApprovedBy() {
        return approvedBy;
    }

    public void setApprovedBy(Employee approvedBy) {
        this.approvedBy = approvedBy;
    }

    public Instant getApprovedAt() {
        return approvedAt;
    }

    public void setApprovedAt(Instant approvedAt) {
        this.approvedAt = approvedAt;
    }

    @java.lang.SuppressWarnings("all")
    
    private static String $default$currency() {
        return "INR";
    }

    @java.lang.SuppressWarnings("all")
    
    private static Integer $default$version() {
        return 1;
    }

    @java.lang.SuppressWarnings("all")
    
    private static ProposalStatus $default$approvalStatus() {
        return ProposalStatus.PENDING;
    }


    @java.lang.SuppressWarnings("all")
    
    public static class ProposalBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Lead lead;
        @java.lang.SuppressWarnings("all")
        
        private String type;
        @java.lang.SuppressWarnings("all")
        
        private String title;
        @java.lang.SuppressWarnings("all")
        
        private String fileName;
        @java.lang.SuppressWarnings("all")
        
        private String filePath;
        @java.lang.SuppressWarnings("all")
        
        private Long fileSize;
        @java.lang.SuppressWarnings("all")
        
        private String mimeType;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal amount;
        @java.lang.SuppressWarnings("all")
        
        private boolean currency$set;
        @java.lang.SuppressWarnings("all")
        
        private String currency$value;
        @java.lang.SuppressWarnings("all")
        
        private boolean version$set;
        @java.lang.SuppressWarnings("all")
        
        private Integer version$value;
        @java.lang.SuppressWarnings("all")
        
        private boolean approvalStatus$set;
        @java.lang.SuppressWarnings("all")
        
        private ProposalStatus approvalStatus$value;
        @java.lang.SuppressWarnings("all")
        
        private java.time.LocalDate validUntil;
        @java.lang.SuppressWarnings("all")
        
        private String notes;
        @java.lang.SuppressWarnings("all")
        
        private Employee uploadedBy;
        @java.lang.SuppressWarnings("all")
        
        private Employee approvedBy;
        @java.lang.SuppressWarnings("all")
        
        private Instant approvedAt;

        @java.lang.SuppressWarnings("all")
        
        ProposalBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Proposal.ProposalBuilder lead(final Lead lead) {
            this.lead = lead;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Proposal.ProposalBuilder type(final String type) {
            this.type = type;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Proposal.ProposalBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Proposal.ProposalBuilder fileName(final String fileName) {
            this.fileName = fileName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Proposal.ProposalBuilder filePath(final String filePath) {
            this.filePath = filePath;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Proposal.ProposalBuilder fileSize(final Long fileSize) {
            this.fileSize = fileSize;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Proposal.ProposalBuilder mimeType(final String mimeType) {
            this.mimeType = mimeType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Proposal.ProposalBuilder amount(final BigDecimal amount) {
            this.amount = amount;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Proposal.ProposalBuilder currency(final String currency) {
            this.currency$value = currency;
            currency$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Proposal.ProposalBuilder version(final Integer version) {
            this.version$value = version;
            version$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Proposal.ProposalBuilder approvalStatus(final ProposalStatus approvalStatus) {
            this.approvalStatus$value = approvalStatus;
            approvalStatus$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Proposal.ProposalBuilder validUntil(final java.time.LocalDate validUntil) {
            this.validUntil = validUntil;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Proposal.ProposalBuilder notes(final String notes) {
            this.notes = notes;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Proposal.ProposalBuilder uploadedBy(final Employee uploadedBy) {
            this.uploadedBy = uploadedBy;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Proposal.ProposalBuilder approvedBy(final Employee approvedBy) {
            this.approvedBy = approvedBy;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Proposal.ProposalBuilder approvedAt(final Instant approvedAt) {
            this.approvedAt = approvedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Proposal build() {
            String currency$value = this.currency$value;
            if (!this.currency$set) currency$value = Proposal.$default$currency();
            Integer version$value = this.version$value;
            if (!this.version$set) version$value = Proposal.$default$version();
            ProposalStatus approvalStatus$value = this.approvalStatus$value;
            if (!this.approvalStatus$set) approvalStatus$value = Proposal.$default$approvalStatus();
            return new Proposal(this.lead, this.type, this.title, this.fileName, this.filePath, this.fileSize, this.mimeType, this.amount, currency$value, version$value, approvalStatus$value, this.validUntil, this.notes, this.uploadedBy, this.approvedBy, this.approvedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Proposal.ProposalBuilder(lead=" + this.lead + ", type=" + this.type + ", title=" + this.title + ", fileName=" + this.fileName + ", filePath=" + this.filePath + ", fileSize=" + this.fileSize + ", mimeType=" + this.mimeType + ", amount=" + this.amount + ", currency$value=" + this.currency$value + ", version$value=" + this.version$value + ", approvalStatus$value=" + this.approvalStatus$value + ", validUntil=" + this.validUntil + ", notes=" + this.notes + ", uploadedBy=" + this.uploadedBy + ", approvedBy=" + this.approvedBy + ", approvedAt=" + this.approvedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static Proposal.ProposalBuilder builder() {
        return new Proposal.ProposalBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Proposal() {
        this.currency = Proposal.$default$currency();
        this.version = Proposal.$default$version();
        this.approvalStatus = Proposal.$default$approvalStatus();
    }

    @java.lang.SuppressWarnings("all")
    
    public Proposal(final Lead lead, final String type, final String title, final String fileName, final String filePath, final Long fileSize, final String mimeType, final BigDecimal amount, final String currency, final Integer version, final ProposalStatus approvalStatus, final java.time.LocalDate validUntil, final String notes, final Employee uploadedBy, final Employee approvedBy, final Instant approvedAt) {
        this.lead = lead;
        this.type = type;
        this.title = title;
        this.fileName = fileName;
        this.filePath = filePath;
        this.fileSize = fileSize;
        this.mimeType = mimeType;
        this.amount = amount;
        this.currency = currency;
        this.version = version;
        this.approvalStatus = approvalStatus;
        this.validUntil = validUntil;
        this.notes = notes;
        this.uploadedBy = uploadedBy;
        this.approvedBy = approvedBy;
        this.approvedAt = approvedAt;
    }
}
