// Generated by delombok at Fri Jul 24 16:18:05 IST 2026
package com.ripplenexus.salespilot.lead.domain;

import com.ripplenexus.salespilot.core.domain.BaseEntity;
import com.ripplenexus.salespilot.employee.domain.Employee;
import jakarta.persistence.*;

import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "leads")
public class Lead extends BaseEntity {
    @Column(name = "lead_number", nullable = false, unique = true)
    private String leadNumber;
    @Column(name = "contact_name")
    private String contactName;
    @Column(name = "contact_designation")
    private String contactDesignation;
    @Column(name = "contact_email")
    private String contactEmail;
    @Column(name = "contact_phone")
    private String contactPhone;
    @Column(name = "contact_whatsapp")
    private String contactWhatsapp;
    @Column(name = "contact_linkedin")
    private String contactLinkedin;
    @Column(name = "company_name")
    private String companyName;
    @Column(name = "company_website")
    private String companyWebsite;
    @Column(name = "industry")
    private String industry;
    @Column(name = "country")
    private String country;
    @Column(name = "budget", precision = 15, scale = 2)
    private BigDecimal budget;
    @Column(name = "currency")
    private String currency = "INR";
    @JdbcTypeCode(SqlTypes.ARRAY)
    @Column(name = "interested_services", columnDefinition = "text[]")
    private String[] interestedServices;
    @Enumerated(EnumType.STRING)
    @org.hibernate.annotations.JdbcTypeCode(org.hibernate.type.SqlTypes.NAMED_ENUM)
    @Column(name = "priority", nullable = false)
    private LeadPriority priority = LeadPriority.MEDIUM;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "source_id")
    private LeadSource source;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assigned_to")
    private Employee assignedTo;
    @Enumerated(EnumType.STRING)
    @org.hibernate.annotations.JdbcTypeCode(org.hibernate.type.SqlTypes.NAMED_ENUM)
    @Column(name = "status", nullable = false)
    private LeadStatus status = LeadStatus.NEW;
    @Column(name = "expected_close_date")
    private LocalDate expectedCloseDate;
    @Column(name = "probability")
    private Integer probability;
    @Column(name = "deal_value", precision = 15, scale = 2)
    private BigDecimal dealValue;
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;
    @OneToMany(mappedBy = "lead", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<LeadAttachment> attachments;


    public enum LeadStatus {
        NEW, CONTACTED, QUALIFIED, MEETING_SCHEDULED, DEMO, PROPOSAL_SENT, NEGOTIATION, WON, LOST, ON_HOLD;
    }


    public enum LeadPriority {
        LOW, MEDIUM, HIGH, CRITICAL;
    }

    public String getContactName() {
        return contactName;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    public String getContactDesignation() {
        return contactDesignation;
    }

    public void setContactDesignation(String contactDesignation) {
        this.contactDesignation = contactDesignation;
    }

    public String getContactEmail() {
        return contactEmail;
    }

    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }

    public String getContactPhone() {
        return contactPhone;
    }

    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }

    public String getContactWhatsapp() {
        return contactWhatsapp;
    }

    public void setContactWhatsapp(String contactWhatsapp) {
        this.contactWhatsapp = contactWhatsapp;
    }

    public String getContactLinkedin() {
        return contactLinkedin;
    }

    public void setContactLinkedin(String contactLinkedin) {
        this.contactLinkedin = contactLinkedin;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getCompanyWebsite() {
        return companyWebsite;
    }

    public void setCompanyWebsite(String companyWebsite) {
        this.companyWebsite = companyWebsite;
    }

    public String getIndustry() {
        return industry;
    }

    public void setIndustry(String industry) {
        this.industry = industry;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public BigDecimal getBudget() {
        return budget;
    }

    public void setBudget(BigDecimal budget) {
        this.budget = budget;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String[] getInterestedServices() {
        return interestedServices;
    }

    public void setInterestedServices(String[] interestedServices) {
        this.interestedServices = interestedServices;
    }

    public LeadPriority getPriority() {
        return priority;
    }

    public void setPriority(LeadPriority priority) {
        this.priority = priority;
    }

    public LeadSource getSource() {
        return source;
    }

    public void setSource(LeadSource source) {
        this.source = source;
    }

    public String getLeadNumber() {
        return leadNumber;
    }

    public void setLeadNumber(String leadNumber) {
        this.leadNumber = leadNumber;
    }

    public Employee getAssignedTo() {
        return assignedTo;
    }

    public void setAssignedTo(Employee assignedTo) {
        this.assignedTo = assignedTo;
    }

    public LeadStatus getStatus() {
        return status;
    }

    public void setStatus(LeadStatus status) {
        this.status = status;
    }

    public LocalDate getExpectedCloseDate() {
        return expectedCloseDate;
    }

    public void setExpectedCloseDate(LocalDate expectedCloseDate) {
        this.expectedCloseDate = expectedCloseDate;
    }

    public Integer getProbability() {
        return probability;
    }

    public void setProbability(Integer probability) {
        this.probability = probability;
    }

    public BigDecimal getDealValue() {
        return dealValue;
    }

    public void setDealValue(BigDecimal dealValue) {
        this.dealValue = dealValue;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public List<LeadAttachment> getAttachments() {
        return attachments;
    }

    public void setAttachments(List<LeadAttachment> attachments) {
        this.attachments = attachments;
    }

    @java.lang.SuppressWarnings("all")
    
    private static List<LeadAttachment> $default$attachments() {
        return new ArrayList<>();
    }


    @java.lang.SuppressWarnings("all")
    
    public static class LeadBuilder {
        @java.lang.SuppressWarnings("all")
        
        private String leadNumber;
        @java.lang.SuppressWarnings("all")
        
        private String contactName;
        @java.lang.SuppressWarnings("all")
        
        private String contactDesignation;
        @java.lang.SuppressWarnings("all")
        
        private String contactEmail;
        @java.lang.SuppressWarnings("all")
        
        private String contactPhone;
        @java.lang.SuppressWarnings("all")
        
        private String contactWhatsapp;
        @java.lang.SuppressWarnings("all")
        
        private String contactLinkedin;
        @java.lang.SuppressWarnings("all")
        
        private String companyName;
        @java.lang.SuppressWarnings("all")
        
        private String companyWebsite;
        @java.lang.SuppressWarnings("all")
        
        private String industry;
        @java.lang.SuppressWarnings("all")
        
        private String country;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal budget;
        @java.lang.SuppressWarnings("all")
        
        private String currency;
        @java.lang.SuppressWarnings("all")
        
        private String[] interestedServices;
        @java.lang.SuppressWarnings("all")
        
        private LeadPriority priority;
        @java.lang.SuppressWarnings("all")
        
        private LeadSource source;
        @java.lang.SuppressWarnings("all")
        
        private Employee assignedTo;
        @java.lang.SuppressWarnings("all")
        
        private LeadStatus status;
        @java.lang.SuppressWarnings("all")
        
        private LocalDate expectedCloseDate;
        @java.lang.SuppressWarnings("all")
        
        private Integer probability;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal dealValue;
        @java.lang.SuppressWarnings("all")
        
        private String notes;
        @java.lang.SuppressWarnings("all")
        
        private boolean attachments$set;
        @java.lang.SuppressWarnings("all")
        
        private List<LeadAttachment> attachments$value;

        @java.lang.SuppressWarnings("all")
        
        LeadBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Lead.LeadBuilder leadNumber(final String leadNumber) {
            this.leadNumber = leadNumber;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Lead.LeadBuilder contactName(final String contactName) {
            this.contactName = contactName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Lead.LeadBuilder contactDesignation(final String contactDesignation) {
            this.contactDesignation = contactDesignation;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Lead.LeadBuilder contactEmail(final String contactEmail) {
            this.contactEmail = contactEmail;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Lead.LeadBuilder contactPhone(final String contactPhone) {
            this.contactPhone = contactPhone;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Lead.LeadBuilder contactWhatsapp(final String contactWhatsapp) {
            this.contactWhatsapp = contactWhatsapp;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Lead.LeadBuilder contactLinkedin(final String contactLinkedin) {
            this.contactLinkedin = contactLinkedin;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Lead.LeadBuilder companyName(final String companyName) {
            this.companyName = companyName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Lead.LeadBuilder companyWebsite(final String companyWebsite) {
            this.companyWebsite = companyWebsite;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Lead.LeadBuilder industry(final String industry) {
            this.industry = industry;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Lead.LeadBuilder country(final String country) {
            this.country = country;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Lead.LeadBuilder budget(final BigDecimal budget) {
            this.budget = budget;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Lead.LeadBuilder currency(final String currency) {
            this.currency = currency;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Lead.LeadBuilder interestedServices(final String[] interestedServices) {
            this.interestedServices = interestedServices;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Lead.LeadBuilder priority(final LeadPriority priority) {
            this.priority = priority;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Lead.LeadBuilder source(final LeadSource source) {
            this.source = source;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Lead.LeadBuilder assignedTo(final Employee assignedTo) {
            this.assignedTo = assignedTo;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Lead.LeadBuilder status(final LeadStatus status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Lead.LeadBuilder expectedCloseDate(final LocalDate expectedCloseDate) {
            this.expectedCloseDate = expectedCloseDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Lead.LeadBuilder probability(final Integer probability) {
            this.probability = probability;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Lead.LeadBuilder dealValue(final BigDecimal dealValue) {
            this.dealValue = dealValue;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Lead.LeadBuilder notes(final String notes) {
            this.notes = notes;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Lead.LeadBuilder attachments(final List<LeadAttachment> attachments) {
            this.attachments$value = attachments;
            attachments$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Lead build() {
            List<LeadAttachment> attachments$value = this.attachments$value;
            if (!this.attachments$set) attachments$value = Lead.$default$attachments();
            return new Lead(this.leadNumber, this.contactName, this.contactDesignation, this.contactEmail, this.contactPhone, this.contactWhatsapp, this.contactLinkedin, this.companyName, this.companyWebsite, this.industry, this.country, this.budget, this.currency, this.interestedServices, this.priority, this.source, this.assignedTo, this.status, this.expectedCloseDate, this.probability, this.dealValue, this.notes, attachments$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Lead.LeadBuilder(leadNumber=" + this.leadNumber + ", contactName=" + this.contactName + ", contactDesignation=" + this.contactDesignation + ", contactEmail=" + this.contactEmail + ", contactPhone=" + this.contactPhone + ", contactWhatsapp=" + this.contactWhatsapp + ", contactLinkedin=" + this.contactLinkedin + ", companyName=" + this.companyName + ", companyWebsite=" + this.companyWebsite + ", industry=" + this.industry + ", country=" + this.country + ", budget=" + this.budget + ", currency=" + this.currency + ", interestedServices=" + java.util.Arrays.deepToString(this.interestedServices) + ", priority=" + this.priority + ", source=" + this.source + ", assignedTo=" + this.assignedTo + ", status=" + this.status + ", expectedCloseDate=" + this.expectedCloseDate + ", probability=" + this.probability + ", dealValue=" + this.dealValue + ", notes=" + this.notes + ", attachments$value=" + this.attachments$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static Lead.LeadBuilder builder() {
        return new Lead.LeadBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Lead() {
        this.attachments = Lead.$default$attachments();
    }

    @java.lang.SuppressWarnings("all")
    
    public Lead(final String leadNumber, final String contactName, final String contactDesignation, final String contactEmail, final String contactPhone, final String contactWhatsapp, final String contactLinkedin, final String companyName, final String companyWebsite, final String industry, final String country, final BigDecimal budget, final String currency, final String[] interestedServices, final LeadPriority priority, final LeadSource source, final Employee assignedTo, final LeadStatus status, final LocalDate expectedCloseDate, final Integer probability, final BigDecimal dealValue, final String notes, final List<LeadAttachment> attachments) {
        this.leadNumber = leadNumber;
        this.contactName = contactName;
        this.contactDesignation = contactDesignation;
        this.contactEmail = contactEmail;
        this.contactPhone = contactPhone;
        this.contactWhatsapp = contactWhatsapp;
        this.contactLinkedin = contactLinkedin;
        this.companyName = companyName;
        this.companyWebsite = companyWebsite;
        this.industry = industry;
        this.country = country;
        this.budget = budget;
        this.currency = currency;
        this.interestedServices = interestedServices;
        this.priority = priority;
        this.source = source;
        this.assignedTo = assignedTo;
        this.status = status;
        this.expectedCloseDate = expectedCloseDate;
        this.probability = probability;
        this.dealValue = dealValue;
        this.notes = notes;
        this.attachments = attachments;
    }
}
