// Generated by delombok at Fri Jul 24 16:18:06 IST 2026
package com.ripplenexus.salespilot.pipeline.domain;

import com.ripplenexus.salespilot.lead.domain.Lead;
import jakarta.persistence.*;

import java.time.Instant;

@Entity
@Table(name = "pipeline_entries")
@EntityListeners(org.springframework.data.jpa.domain.support.AuditingEntityListener.class)
public class PipelineEntry {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private java.util.UUID id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "lead_id", nullable = false)
    private Lead lead;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stage_id", nullable = false)
    private PipelineStage stage;
    @Column(name = "entered_at", nullable = false)
    private Instant enteredAt;
    @Column(name = "position", nullable = false)
    private Integer position;
    @Column(name = "last_moved_at")
    private Instant lastMovedAt;
    @Column(name = "days_in_stage")
    private Integer daysInStage;
    @org.springframework.data.annotation.CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;
    @org.springframework.data.annotation.LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    public java.util.UUID getId() {
        return id;
    }

    public void setId(java.util.UUID id) {
        this.id = id;
    }

    public Lead getLead() {
        return lead;
    }

    public void setLead(Lead lead) {
        this.lead = lead;
    }

    public PipelineStage getStage() {
        return stage;
    }

    public void setStage(PipelineStage stage) {
        this.stage = stage;
    }

    public Instant getEnteredAt() {
        return enteredAt;
    }

    public void setEnteredAt(Instant enteredAt) {
        this.enteredAt = enteredAt;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    public Instant getLastMovedAt() {
        return lastMovedAt;
    }

    public void setLastMovedAt(Instant lastMovedAt) {
        this.lastMovedAt = lastMovedAt;
    }

    public Integer getDaysInStage() {
        return daysInStage;
    }

    public void setDaysInStage(Integer daysInStage) {
        this.daysInStage = daysInStage;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    
    private static Integer $default$position() {
        return 0;
    }

    @java.lang.SuppressWarnings("all")
    
    private static Integer $default$daysInStage() {
        return 0;
    }


    @java.lang.SuppressWarnings("all")
    
    public static class PipelineEntryBuilder {
        @java.lang.SuppressWarnings("all")
        
        private java.util.UUID id;
        @java.lang.SuppressWarnings("all")
        
        private Lead lead;
        @java.lang.SuppressWarnings("all")
        
        private PipelineStage stage;
        @java.lang.SuppressWarnings("all")
        
        private Instant enteredAt;
        @java.lang.SuppressWarnings("all")
        
        private boolean position$set;
        @java.lang.SuppressWarnings("all")
        
        private Integer position$value;
        @java.lang.SuppressWarnings("all")
        
        private Instant lastMovedAt;
        @java.lang.SuppressWarnings("all")
        
        private boolean daysInStage$set;
        @java.lang.SuppressWarnings("all")
        
        private Integer daysInStage$value;
        @java.lang.SuppressWarnings("all")
        
        private Instant createdAt;
        @java.lang.SuppressWarnings("all")
        
        private Instant updatedAt;

        @java.lang.SuppressWarnings("all")
        
        PipelineEntryBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public PipelineEntry.PipelineEntryBuilder id(final java.util.UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public PipelineEntry.PipelineEntryBuilder lead(final Lead lead) {
            this.lead = lead;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public PipelineEntry.PipelineEntryBuilder stage(final PipelineStage stage) {
            this.stage = stage;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public PipelineEntry.PipelineEntryBuilder enteredAt(final Instant enteredAt) {
            this.enteredAt = enteredAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public PipelineEntry.PipelineEntryBuilder position(final Integer position) {
            this.position$value = position;
            position$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public PipelineEntry.PipelineEntryBuilder lastMovedAt(final Instant lastMovedAt) {
            this.lastMovedAt = lastMovedAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public PipelineEntry.PipelineEntryBuilder daysInStage(final Integer daysInStage) {
            this.daysInStage$value = daysInStage;
            daysInStage$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public PipelineEntry.PipelineEntryBuilder createdAt(final Instant createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public PipelineEntry.PipelineEntryBuilder updatedAt(final Instant updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public PipelineEntry build() {
            Integer position$value = this.position$value;
            if (!this.position$set) position$value = PipelineEntry.$default$position();
            Integer daysInStage$value = this.daysInStage$value;
            if (!this.daysInStage$set) daysInStage$value = PipelineEntry.$default$daysInStage();
            return new PipelineEntry(this.id, this.lead, this.stage, this.enteredAt, position$value, this.lastMovedAt, daysInStage$value, this.createdAt, this.updatedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "PipelineEntry.PipelineEntryBuilder(id=" + this.id + ", lead=" + this.lead + ", stage=" + this.stage + ", enteredAt=" + this.enteredAt + ", position$value=" + this.position$value + ", lastMovedAt=" + this.lastMovedAt + ", daysInStage$value=" + this.daysInStage$value + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static PipelineEntry.PipelineEntryBuilder builder() {
        return new PipelineEntry.PipelineEntryBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public PipelineEntry() {
        this.position = PipelineEntry.$default$position();
        this.daysInStage = PipelineEntry.$default$daysInStage();
    }

    @java.lang.SuppressWarnings("all")
    
    public PipelineEntry(final java.util.UUID id, final Lead lead, final PipelineStage stage, final Instant enteredAt, final Integer position, final Instant lastMovedAt, final Integer daysInStage, final Instant createdAt, final Instant updatedAt) {
        this.id = id;
        this.lead = lead;
        this.stage = stage;
        this.enteredAt = enteredAt;
        this.position = position;
        this.lastMovedAt = lastMovedAt;
        this.daysInStage = daysInStage;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
