// Generated by delombok at Fri Jul 24 16:18:06 IST 2026
package com.ripplenexus.salespilot.pipeline.domain;

import com.ripplenexus.salespilot.core.domain.BaseEntity;
import jakarta.persistence.*;


@Entity
@Table(name = "pipeline_stages")
public class PipelineStage extends BaseEntity {
    @Column(name = "name", nullable = false)
    private String name;
    @Column(name = "slug", nullable = false, unique = true)
    private String slug;
    @Column(name = "color", nullable = false)
    private String color;
    @Column(name = "display_order", nullable = false)
    private Integer displayOrder;
    @Column(name = "description")
    private String description;
    @Column(name = "is_won_stage", nullable = false)
    private Boolean isWonStage;
    @Column(name = "is_lost_stage", nullable = false)
    private Boolean isLostStage;
    @Column(name = "is_active", nullable = false)
    private Boolean isActive;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public Integer getDisplayOrder() {
        return displayOrder;
    }

    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Boolean getIsWonStage() {
        return isWonStage;
    }

    public void setIsWonStage(Boolean isWonStage) {
        this.isWonStage = isWonStage;
    }

    public Boolean getIsLostStage() {
        return isLostStage;
    }

    public void setIsLostStage(Boolean isLostStage) {
        this.isLostStage = isLostStage;
    }

    public Boolean getIsActive() {
        return isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    @java.lang.SuppressWarnings("all")
    
    private static String $default$color() {
        return "#6366f1";
    }

    @java.lang.SuppressWarnings("all")
    
    private static Boolean $default$isWonStage() {
        return false;
    }

    @java.lang.SuppressWarnings("all")
    
    private static Boolean $default$isLostStage() {
        return false;
    }

    @java.lang.SuppressWarnings("all")
    
    private static Boolean $default$isActive() {
        return true;
    }


    @java.lang.SuppressWarnings("all")
    
    public static class PipelineStageBuilder {
        @java.lang.SuppressWarnings("all")
        
        private String name;
        @java.lang.SuppressWarnings("all")
        
        private String slug;
        @java.lang.SuppressWarnings("all")
        
        private boolean color$set;
        @java.lang.SuppressWarnings("all")
        
        private String color$value;
        @java.lang.SuppressWarnings("all")
        
        private Integer displayOrder;
        @java.lang.SuppressWarnings("all")
        
        private String description;
        @java.lang.SuppressWarnings("all")
        
        private boolean isWonStage$set;
        @java.lang.SuppressWarnings("all")
        
        private Boolean isWonStage$value;
        @java.lang.SuppressWarnings("all")
        
        private boolean isLostStage$set;
        @java.lang.SuppressWarnings("all")
        
        private Boolean isLostStage$value;
        @java.lang.SuppressWarnings("all")
        
        private boolean isActive$set;
        @java.lang.SuppressWarnings("all")
        
        private Boolean isActive$value;

        @java.lang.SuppressWarnings("all")
        
        PipelineStageBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public PipelineStage.PipelineStageBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public PipelineStage.PipelineStageBuilder slug(final String slug) {
            this.slug = slug;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public PipelineStage.PipelineStageBuilder color(final String color) {
            this.color$value = color;
            color$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public PipelineStage.PipelineStageBuilder displayOrder(final Integer displayOrder) {
            this.displayOrder = displayOrder;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public PipelineStage.PipelineStageBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public PipelineStage.PipelineStageBuilder isWonStage(final Boolean isWonStage) {
            this.isWonStage$value = isWonStage;
            isWonStage$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public PipelineStage.PipelineStageBuilder isLostStage(final Boolean isLostStage) {
            this.isLostStage$value = isLostStage;
            isLostStage$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public PipelineStage.PipelineStageBuilder isActive(final Boolean isActive) {
            this.isActive$value = isActive;
            isActive$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public PipelineStage build() {
            String color$value = this.color$value;
            if (!this.color$set) color$value = PipelineStage.$default$color();
            Boolean isWonStage$value = this.isWonStage$value;
            if (!this.isWonStage$set) isWonStage$value = PipelineStage.$default$isWonStage();
            Boolean isLostStage$value = this.isLostStage$value;
            if (!this.isLostStage$set) isLostStage$value = PipelineStage.$default$isLostStage();
            Boolean isActive$value = this.isActive$value;
            if (!this.isActive$set) isActive$value = PipelineStage.$default$isActive();
            return new PipelineStage(this.name, this.slug, color$value, this.displayOrder, this.description, isWonStage$value, isLostStage$value, isActive$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "PipelineStage.PipelineStageBuilder(name=" + this.name + ", slug=" + this.slug + ", color$value=" + this.color$value + ", displayOrder=" + this.displayOrder + ", description=" + this.description + ", isWonStage$value=" + this.isWonStage$value + ", isLostStage$value=" + this.isLostStage$value + ", isActive$value=" + this.isActive$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static PipelineStage.PipelineStageBuilder builder() {
        return new PipelineStage.PipelineStageBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public PipelineStage() {
        this.color = PipelineStage.$default$color();
        this.isWonStage = PipelineStage.$default$isWonStage();
        this.isLostStage = PipelineStage.$default$isLostStage();
        this.isActive = PipelineStage.$default$isActive();
    }

    @java.lang.SuppressWarnings("all")
    
    public PipelineStage(final String name, final String slug, final String color, final Integer displayOrder, final String description, final Boolean isWonStage, final Boolean isLostStage, final Boolean isActive) {
        this.name = name;
        this.slug = slug;
        this.color = color;
        this.displayOrder = displayOrder;
        this.description = description;
        this.isWonStage = isWonStage;
        this.isLostStage = isLostStage;
        this.isActive = isActive;
    }
}
