// Generated by delombok at Fri Jul 24 16:18:03 IST 2026
package com.ripplenexus.salespilot.core.storage;

import jakarta.persistence.*;

import org.hibernate.annotations.CreationTimestamp;
import java.time.Instant;
import java.util.UUID;

@Entity
@Table(name = "file_storage")
public class DatabaseFileEntity {
    @Id
    private UUID id;
    @Column(nullable = false)
    private String filename;
    @Column(nullable = false)
    private String contentType;
    @Column(nullable = false)
    private String folder;
    @Lob
    @Basic(fetch = FetchType.LAZY)
    @Column(nullable = false)
    private byte[] data;
    @CreationTimestamp
    @Column(updatable = false)
    private Instant createdAt;

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public String getFolder() {
        return folder;
    }

    public void setFolder(String folder) {
        this.folder = folder;
    }

    public byte[] getData() {
        return data;
    }

    public void setData(byte[] data) {
        this.data = data;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }


    @java.lang.SuppressWarnings("all")
    
    public static class DatabaseFileEntityBuilder {
        @java.lang.SuppressWarnings("all")
        
        private UUID id;
        @java.lang.SuppressWarnings("all")
        
        private String filename;
        @java.lang.SuppressWarnings("all")
        
        private String contentType;
        @java.lang.SuppressWarnings("all")
        
        private String folder;
        @java.lang.SuppressWarnings("all")
        
        private byte[] data;
        @java.lang.SuppressWarnings("all")
        
        private Instant createdAt;

        @java.lang.SuppressWarnings("all")
        
        DatabaseFileEntityBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public DatabaseFileEntity.DatabaseFileEntityBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public DatabaseFileEntity.DatabaseFileEntityBuilder filename(final String filename) {
            this.filename = filename;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public DatabaseFileEntity.DatabaseFileEntityBuilder contentType(final String contentType) {
            this.contentType = contentType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public DatabaseFileEntity.DatabaseFileEntityBuilder folder(final String folder) {
            this.folder = folder;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public DatabaseFileEntity.DatabaseFileEntityBuilder data(final byte[] data) {
            this.data = data;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public DatabaseFileEntity.DatabaseFileEntityBuilder createdAt(final Instant createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public DatabaseFileEntity build() {
            return new DatabaseFileEntity(this.id, this.filename, this.contentType, this.folder, this.data, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "DatabaseFileEntity.DatabaseFileEntityBuilder(id=" + this.id + ", filename=" + this.filename + ", contentType=" + this.contentType + ", folder=" + this.folder + ", data=" + java.util.Arrays.toString(this.data) + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static DatabaseFileEntity.DatabaseFileEntityBuilder builder() {
        return new DatabaseFileEntity.DatabaseFileEntityBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public DatabaseFileEntity() {
    }

    @java.lang.SuppressWarnings("all")
    
    public DatabaseFileEntity(final UUID id, final String filename, final String contentType, final String folder, final byte[] data, final Instant createdAt) {
        this.id = id;
        this.filename = filename;
        this.contentType = contentType;
        this.folder = folder;
        this.data = data;
        this.createdAt = createdAt;
    }
}
