// Generated by delombok at Fri Jul 24 16:18:04 IST 2026
package com.ripplenexus.salespilot.employee.presentation.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;

public class CreateEmployeeRequest {
    @NotBlank(message = "First name is required")
    private String firstName;
    @NotBlank(message = "Last name is required")
    private String lastName;
    @NotBlank(message = "Work email is required")
    @Email(message = "Invalid email format")
    private String workEmail;
    @Email(message = "Invalid personal email format")
    private String personalEmail;
    private String phone;
    private String whatsapp;
    @NotBlank(message = "Designation is required")
    private String designation;
    private UUID departmentId;
    private UUID managerId;
    @NotNull(message = "Joining date is required")
    private LocalDate joiningDate;
    private String role = "SALES_EMPLOYEE";
    private BigDecimal salary;
    private String notes;

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getWorkEmail() {
        return workEmail;
    }

    public void setWorkEmail(String workEmail) {
        this.workEmail = workEmail;
    }

    public String getPersonalEmail() {
        return personalEmail;
    }

    public void setPersonalEmail(String personalEmail) {
        this.personalEmail = personalEmail;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getWhatsapp() {
        return whatsapp;
    }

    public void setWhatsapp(String whatsapp) {
        this.whatsapp = whatsapp;
    }

    public String getDesignation() {
        return designation;
    }

    public void setDesignation(String designation) {
        this.designation = designation;
    }

    public UUID getDepartmentId() {
        return departmentId;
    }

    public void setDepartmentId(UUID departmentId) {
        this.departmentId = departmentId;
    }

    public UUID getManagerId() {
        return managerId;
    }

    public void setManagerId(UUID managerId) {
        this.managerId = managerId;
    }

    public LocalDate getJoiningDate() {
        return joiningDate;
    }

    public void setJoiningDate(LocalDate joiningDate) {
        this.joiningDate = joiningDate;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public BigDecimal getSalary() {
        return salary;
    }

    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    @java.lang.SuppressWarnings("all")
    
    public CreateEmployeeRequest() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CreateEmployeeRequest)) return false;
        final CreateEmployeeRequest other = (CreateEmployeeRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$firstName = this.getFirstName();
        final java.lang.Object other$firstName = other.getFirstName();
        if (this$firstName == null ? other$firstName != null : !this$firstName.equals(other$firstName)) return false;
        final java.lang.Object this$lastName = this.getLastName();
        final java.lang.Object other$lastName = other.getLastName();
        if (this$lastName == null ? other$lastName != null : !this$lastName.equals(other$lastName)) return false;
        final java.lang.Object this$workEmail = this.getWorkEmail();
        final java.lang.Object other$workEmail = other.getWorkEmail();
        if (this$workEmail == null ? other$workEmail != null : !this$workEmail.equals(other$workEmail)) return false;
        final java.lang.Object this$personalEmail = this.getPersonalEmail();
        final java.lang.Object other$personalEmail = other.getPersonalEmail();
        if (this$personalEmail == null ? other$personalEmail != null : !this$personalEmail.equals(other$personalEmail)) return false;
        final java.lang.Object this$phone = this.getPhone();
        final java.lang.Object other$phone = other.getPhone();
        if (this$phone == null ? other$phone != null : !this$phone.equals(other$phone)) return false;
        final java.lang.Object this$whatsapp = this.getWhatsapp();
        final java.lang.Object other$whatsapp = other.getWhatsapp();
        if (this$whatsapp == null ? other$whatsapp != null : !this$whatsapp.equals(other$whatsapp)) return false;
        final java.lang.Object this$designation = this.getDesignation();
        final java.lang.Object other$designation = other.getDesignation();
        if (this$designation == null ? other$designation != null : !this$designation.equals(other$designation)) return false;
        final java.lang.Object this$departmentId = this.getDepartmentId();
        final java.lang.Object other$departmentId = other.getDepartmentId();
        if (this$departmentId == null ? other$departmentId != null : !this$departmentId.equals(other$departmentId)) return false;
        final java.lang.Object this$managerId = this.getManagerId();
        final java.lang.Object other$managerId = other.getManagerId();
        if (this$managerId == null ? other$managerId != null : !this$managerId.equals(other$managerId)) return false;
        final java.lang.Object this$joiningDate = this.getJoiningDate();
        final java.lang.Object other$joiningDate = other.getJoiningDate();
        if (this$joiningDate == null ? other$joiningDate != null : !this$joiningDate.equals(other$joiningDate)) return false;
        final java.lang.Object this$role = this.getRole();
        final java.lang.Object other$role = other.getRole();
        if (this$role == null ? other$role != null : !this$role.equals(other$role)) return false;
        final java.lang.Object this$salary = this.getSalary();
        final java.lang.Object other$salary = other.getSalary();
        if (this$salary == null ? other$salary != null : !this$salary.equals(other$salary)) return false;
        final java.lang.Object this$notes = this.getNotes();
        final java.lang.Object other$notes = other.getNotes();
        if (this$notes == null ? other$notes != null : !this$notes.equals(other$notes)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CreateEmployeeRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $firstName = this.getFirstName();
        result = result * PRIME + ($firstName == null ? 43 : $firstName.hashCode());
        final java.lang.Object $lastName = this.getLastName();
        result = result * PRIME + ($lastName == null ? 43 : $lastName.hashCode());
        final java.lang.Object $workEmail = this.getWorkEmail();
        result = result * PRIME + ($workEmail == null ? 43 : $workEmail.hashCode());
        final java.lang.Object $personalEmail = this.getPersonalEmail();
        result = result * PRIME + ($personalEmail == null ? 43 : $personalEmail.hashCode());
        final java.lang.Object $phone = this.getPhone();
        result = result * PRIME + ($phone == null ? 43 : $phone.hashCode());
        final java.lang.Object $whatsapp = this.getWhatsapp();
        result = result * PRIME + ($whatsapp == null ? 43 : $whatsapp.hashCode());
        final java.lang.Object $designation = this.getDesignation();
        result = result * PRIME + ($designation == null ? 43 : $designation.hashCode());
        final java.lang.Object $departmentId = this.getDepartmentId();
        result = result * PRIME + ($departmentId == null ? 43 : $departmentId.hashCode());
        final java.lang.Object $managerId = this.getManagerId();
        result = result * PRIME + ($managerId == null ? 43 : $managerId.hashCode());
        final java.lang.Object $joiningDate = this.getJoiningDate();
        result = result * PRIME + ($joiningDate == null ? 43 : $joiningDate.hashCode());
        final java.lang.Object $role = this.getRole();
        result = result * PRIME + ($role == null ? 43 : $role.hashCode());
        final java.lang.Object $salary = this.getSalary();
        result = result * PRIME + ($salary == null ? 43 : $salary.hashCode());
        final java.lang.Object $notes = this.getNotes();
        result = result * PRIME + ($notes == null ? 43 : $notes.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public java.lang.String toString() {
        return "CreateEmployeeRequest(firstName=" + this.getFirstName() + ", lastName=" + this.getLastName() + ", workEmail=" + this.getWorkEmail() + ", personalEmail=" + this.getPersonalEmail() + ", phone=" + this.getPhone() + ", whatsapp=" + this.getWhatsapp() + ", designation=" + this.getDesignation() + ", departmentId=" + this.getDepartmentId() + ", managerId=" + this.getManagerId() + ", joiningDate=" + this.getJoiningDate() + ", role=" + this.getRole() + ", salary=" + this.getSalary() + ", notes=" + this.getNotes() + ")";
    }
}
