// Generated by delombok at Fri Jul 24 16:18:04 IST 2026
package com.ripplenexus.salespilot.employee.presentation.dto;

import jakarta.validation.constraints.NotBlank;

public class KycSubmissionRequest {
    @NotBlank(message = "Country is required")
    private String countryOfId;
    @NotBlank(message = "National ID number is required")
    private String nationalId;
    @NotBlank(message = "KYC Document is required")
    private String kycDocumentPath;
    @NotBlank(message = "UPI ID is required")
    private String upiId;
    @NotBlank(message = "Bank Name is required")
    private String bankName;
    @NotBlank(message = "Bank Account number is required")
    private String bankAccount;
    @NotBlank(message = "Bank IFSC code is required")
    private String bankIfsc;

    public String getCountryOfId() {
        return countryOfId;
    }

    public void setCountryOfId(String countryOfId) {
        this.countryOfId = countryOfId;
    }

    public String getNationalId() {
        return nationalId;
    }

    public void setNationalId(String nationalId) {
        this.nationalId = nationalId;
    }

    public String getKycDocumentPath() {
        return kycDocumentPath;
    }

    public void setKycDocumentPath(String kycDocumentPath) {
        this.kycDocumentPath = kycDocumentPath;
    }

    public String getUpiId() {
        return upiId;
    }

    public void setUpiId(String upiId) {
        this.upiId = upiId;
    }

    public String getBankName() {
        return bankName;
    }

    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    public String getBankAccount() {
        return bankAccount;
    }

    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount;
    }

    public String getBankIfsc() {
        return bankIfsc;
    }

    public void setBankIfsc(String bankIfsc) {
        this.bankIfsc = bankIfsc;
    }

    @java.lang.SuppressWarnings("all")
    
    public KycSubmissionRequest() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof KycSubmissionRequest)) return false;
        final KycSubmissionRequest other = (KycSubmissionRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$countryOfId = this.getCountryOfId();
        final java.lang.Object other$countryOfId = other.getCountryOfId();
        if (this$countryOfId == null ? other$countryOfId != null : !this$countryOfId.equals(other$countryOfId)) return false;
        final java.lang.Object this$nationalId = this.getNationalId();
        final java.lang.Object other$nationalId = other.getNationalId();
        if (this$nationalId == null ? other$nationalId != null : !this$nationalId.equals(other$nationalId)) return false;
        final java.lang.Object this$kycDocumentPath = this.getKycDocumentPath();
        final java.lang.Object other$kycDocumentPath = other.getKycDocumentPath();
        if (this$kycDocumentPath == null ? other$kycDocumentPath != null : !this$kycDocumentPath.equals(other$kycDocumentPath)) return false;
        final java.lang.Object this$upiId = this.getUpiId();
        final java.lang.Object other$upiId = other.getUpiId();
        if (this$upiId == null ? other$upiId != null : !this$upiId.equals(other$upiId)) return false;
        final java.lang.Object this$bankName = this.getBankName();
        final java.lang.Object other$bankName = other.getBankName();
        if (this$bankName == null ? other$bankName != null : !this$bankName.equals(other$bankName)) return false;
        final java.lang.Object this$bankAccount = this.getBankAccount();
        final java.lang.Object other$bankAccount = other.getBankAccount();
        if (this$bankAccount == null ? other$bankAccount != null : !this$bankAccount.equals(other$bankAccount)) return false;
        final java.lang.Object this$bankIfsc = this.getBankIfsc();
        final java.lang.Object other$bankIfsc = other.getBankIfsc();
        if (this$bankIfsc == null ? other$bankIfsc != null : !this$bankIfsc.equals(other$bankIfsc)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof KycSubmissionRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $countryOfId = this.getCountryOfId();
        result = result * PRIME + ($countryOfId == null ? 43 : $countryOfId.hashCode());
        final java.lang.Object $nationalId = this.getNationalId();
        result = result * PRIME + ($nationalId == null ? 43 : $nationalId.hashCode());
        final java.lang.Object $kycDocumentPath = this.getKycDocumentPath();
        result = result * PRIME + ($kycDocumentPath == null ? 43 : $kycDocumentPath.hashCode());
        final java.lang.Object $upiId = this.getUpiId();
        result = result * PRIME + ($upiId == null ? 43 : $upiId.hashCode());
        final java.lang.Object $bankName = this.getBankName();
        result = result * PRIME + ($bankName == null ? 43 : $bankName.hashCode());
        final java.lang.Object $bankAccount = this.getBankAccount();
        result = result * PRIME + ($bankAccount == null ? 43 : $bankAccount.hashCode());
        final java.lang.Object $bankIfsc = this.getBankIfsc();
        result = result * PRIME + ($bankIfsc == null ? 43 : $bankIfsc.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public java.lang.String toString() {
        return "KycSubmissionRequest(countryOfId=" + this.getCountryOfId() + ", nationalId=" + this.getNationalId() + ", kycDocumentPath=" + this.getKycDocumentPath() + ", upiId=" + this.getUpiId() + ", bankName=" + this.getBankName() + ", bankAccount=" + this.getBankAccount() + ", bankIfsc=" + this.getBankIfsc() + ")";
    }
}
