// Generated by delombok at Fri Jul 24 16:18:04 IST 2026
package com.ripplenexus.salespilot.employee.presentation.dto;

public class UpdateEmployeeProfileRequest {
    private String firstName;
    private String lastName;
    private String phone;
    private String whatsapp;
    private String address;
    private String city;
    private String state;
    private String country;
    private String pincode;
    private String emergencyName;
    private String emergencyPhone;
    private String emergencyRelation;
    private String profilePicture;

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getWhatsapp() {
        return whatsapp;
    }

    public void setWhatsapp(String whatsapp) {
        this.whatsapp = whatsapp;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getPincode() {
        return pincode;
    }

    public void setPincode(String pincode) {
        this.pincode = pincode;
    }

    public String getEmergencyName() {
        return emergencyName;
    }

    public void setEmergencyName(String emergencyName) {
        this.emergencyName = emergencyName;
    }

    public String getEmergencyPhone() {
        return emergencyPhone;
    }

    public void setEmergencyPhone(String emergencyPhone) {
        this.emergencyPhone = emergencyPhone;
    }

    public String getEmergencyRelation() {
        return emergencyRelation;
    }

    public void setEmergencyRelation(String emergencyRelation) {
        this.emergencyRelation = emergencyRelation;
    }

    public String getProfilePicture() {
        return profilePicture;
    }

    public void setProfilePicture(String profilePicture) {
        this.profilePicture = profilePicture;
    }

    @java.lang.SuppressWarnings("all")
    
    public UpdateEmployeeProfileRequest() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof UpdateEmployeeProfileRequest)) return false;
        final UpdateEmployeeProfileRequest other = (UpdateEmployeeProfileRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$firstName = this.getFirstName();
        final java.lang.Object other$firstName = other.getFirstName();
        if (this$firstName == null ? other$firstName != null : !this$firstName.equals(other$firstName)) return false;
        final java.lang.Object this$lastName = this.getLastName();
        final java.lang.Object other$lastName = other.getLastName();
        if (this$lastName == null ? other$lastName != null : !this$lastName.equals(other$lastName)) return false;
        final java.lang.Object this$phone = this.getPhone();
        final java.lang.Object other$phone = other.getPhone();
        if (this$phone == null ? other$phone != null : !this$phone.equals(other$phone)) return false;
        final java.lang.Object this$whatsapp = this.getWhatsapp();
        final java.lang.Object other$whatsapp = other.getWhatsapp();
        if (this$whatsapp == null ? other$whatsapp != null : !this$whatsapp.equals(other$whatsapp)) return false;
        final java.lang.Object this$address = this.getAddress();
        final java.lang.Object other$address = other.getAddress();
        if (this$address == null ? other$address != null : !this$address.equals(other$address)) return false;
        final java.lang.Object this$city = this.getCity();
        final java.lang.Object other$city = other.getCity();
        if (this$city == null ? other$city != null : !this$city.equals(other$city)) return false;
        final java.lang.Object this$state = this.getState();
        final java.lang.Object other$state = other.getState();
        if (this$state == null ? other$state != null : !this$state.equals(other$state)) return false;
        final java.lang.Object this$country = this.getCountry();
        final java.lang.Object other$country = other.getCountry();
        if (this$country == null ? other$country != null : !this$country.equals(other$country)) return false;
        final java.lang.Object this$pincode = this.getPincode();
        final java.lang.Object other$pincode = other.getPincode();
        if (this$pincode == null ? other$pincode != null : !this$pincode.equals(other$pincode)) return false;
        final java.lang.Object this$emergencyName = this.getEmergencyName();
        final java.lang.Object other$emergencyName = other.getEmergencyName();
        if (this$emergencyName == null ? other$emergencyName != null : !this$emergencyName.equals(other$emergencyName)) return false;
        final java.lang.Object this$emergencyPhone = this.getEmergencyPhone();
        final java.lang.Object other$emergencyPhone = other.getEmergencyPhone();
        if (this$emergencyPhone == null ? other$emergencyPhone != null : !this$emergencyPhone.equals(other$emergencyPhone)) return false;
        final java.lang.Object this$emergencyRelation = this.getEmergencyRelation();
        final java.lang.Object other$emergencyRelation = other.getEmergencyRelation();
        if (this$emergencyRelation == null ? other$emergencyRelation != null : !this$emergencyRelation.equals(other$emergencyRelation)) return false;
        final java.lang.Object this$profilePicture = this.getProfilePicture();
        final java.lang.Object other$profilePicture = other.getProfilePicture();
        if (this$profilePicture == null ? other$profilePicture != null : !this$profilePicture.equals(other$profilePicture)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof UpdateEmployeeProfileRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $firstName = this.getFirstName();
        result = result * PRIME + ($firstName == null ? 43 : $firstName.hashCode());
        final java.lang.Object $lastName = this.getLastName();
        result = result * PRIME + ($lastName == null ? 43 : $lastName.hashCode());
        final java.lang.Object $phone = this.getPhone();
        result = result * PRIME + ($phone == null ? 43 : $phone.hashCode());
        final java.lang.Object $whatsapp = this.getWhatsapp();
        result = result * PRIME + ($whatsapp == null ? 43 : $whatsapp.hashCode());
        final java.lang.Object $address = this.getAddress();
        result = result * PRIME + ($address == null ? 43 : $address.hashCode());
        final java.lang.Object $city = this.getCity();
        result = result * PRIME + ($city == null ? 43 : $city.hashCode());
        final java.lang.Object $state = this.getState();
        result = result * PRIME + ($state == null ? 43 : $state.hashCode());
        final java.lang.Object $country = this.getCountry();
        result = result * PRIME + ($country == null ? 43 : $country.hashCode());
        final java.lang.Object $pincode = this.getPincode();
        result = result * PRIME + ($pincode == null ? 43 : $pincode.hashCode());
        final java.lang.Object $emergencyName = this.getEmergencyName();
        result = result * PRIME + ($emergencyName == null ? 43 : $emergencyName.hashCode());
        final java.lang.Object $emergencyPhone = this.getEmergencyPhone();
        result = result * PRIME + ($emergencyPhone == null ? 43 : $emergencyPhone.hashCode());
        final java.lang.Object $emergencyRelation = this.getEmergencyRelation();
        result = result * PRIME + ($emergencyRelation == null ? 43 : $emergencyRelation.hashCode());
        final java.lang.Object $profilePicture = this.getProfilePicture();
        result = result * PRIME + ($profilePicture == null ? 43 : $profilePicture.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public java.lang.String toString() {
        return "UpdateEmployeeProfileRequest(firstName=" + this.getFirstName() + ", lastName=" + this.getLastName() + ", phone=" + this.getPhone() + ", whatsapp=" + this.getWhatsapp() + ", address=" + this.getAddress() + ", city=" + this.getCity() + ", state=" + this.getState() + ", country=" + this.getCountry() + ", pincode=" + this.getPincode() + ", emergencyName=" + this.getEmergencyName() + ", emergencyPhone=" + this.getEmergencyPhone() + ", emergencyRelation=" + this.getEmergencyRelation() + ", profilePicture=" + this.getProfilePicture() + ")";
    }
}
