// Generated by delombok at Fri Jul 24 16:18:04 IST 2026
package com.ripplenexus.salespilot.incentive.domain;

import com.ripplenexus.salespilot.core.domain.BaseEntity;
import jakarta.persistence.*;

import java.math.BigDecimal;

@Entity
@Table(name = "incentives")
public class Incentive extends BaseEntity {
    @Column(name = "title", nullable = false)
    private String title;
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;
    @Enumerated(EnumType.STRING)
    @Column(name = "target_type", nullable = false)
    private TargetType targetType;
    @Column(name = "target_value", nullable = false, precision = 12, scale = 2)
    private BigDecimal targetValue;
    @Column(name = "reward_amount", nullable = false, precision = 12, scale = 2)
    private BigDecimal rewardAmount;
    @Column(name = "badge_name")
    private String badgeName;
    @Column(name = "badge_icon")
    private String badgeIcon;
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private Status status;


    public enum TargetType {
        DEAL_REVENUE, DEALS_CLOSED, LEADS_CONVERTED;
    }


    public enum Status {
        ACTIVE, INACTIVE, EXPIRED;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public TargetType getTargetType() {
        return targetType;
    }

    public void setTargetType(TargetType targetType) {
        this.targetType = targetType;
    }

    public BigDecimal getTargetValue() {
        return targetValue;
    }

    public void setTargetValue(BigDecimal targetValue) {
        this.targetValue = targetValue;
    }

    public BigDecimal getRewardAmount() {
        return rewardAmount;
    }

    public void setRewardAmount(BigDecimal rewardAmount) {
        this.rewardAmount = rewardAmount;
    }

    public String getBadgeName() {
        return badgeName;
    }

    public void setBadgeName(String badgeName) {
        this.badgeName = badgeName;
    }

    public String getBadgeIcon() {
        return badgeIcon;
    }

    public void setBadgeIcon(String badgeIcon) {
        this.badgeIcon = badgeIcon;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    
    private static Status $default$status() {
        return Status.ACTIVE;
    }


    @java.lang.SuppressWarnings("all")
    
    public static class IncentiveBuilder {
        @java.lang.SuppressWarnings("all")
        
        private String title;
        @java.lang.SuppressWarnings("all")
        
        private String description;
        @java.lang.SuppressWarnings("all")
        
        private TargetType targetType;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal targetValue;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal rewardAmount;
        @java.lang.SuppressWarnings("all")
        
        private String badgeName;
        @java.lang.SuppressWarnings("all")
        
        private String badgeIcon;
        @java.lang.SuppressWarnings("all")
        
        private boolean status$set;
        @java.lang.SuppressWarnings("all")
        
        private Status status$value;

        @java.lang.SuppressWarnings("all")
        
        IncentiveBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Incentive.IncentiveBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Incentive.IncentiveBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Incentive.IncentiveBuilder targetType(final TargetType targetType) {
            this.targetType = targetType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Incentive.IncentiveBuilder targetValue(final BigDecimal targetValue) {
            this.targetValue = targetValue;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Incentive.IncentiveBuilder rewardAmount(final BigDecimal rewardAmount) {
            this.rewardAmount = rewardAmount;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Incentive.IncentiveBuilder badgeName(final String badgeName) {
            this.badgeName = badgeName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Incentive.IncentiveBuilder badgeIcon(final String badgeIcon) {
            this.badgeIcon = badgeIcon;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Incentive.IncentiveBuilder status(final Status status) {
            this.status$value = status;
            status$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Incentive build() {
            Status status$value = this.status$value;
            if (!this.status$set) status$value = Incentive.$default$status();
            return new Incentive(this.title, this.description, this.targetType, this.targetValue, this.rewardAmount, this.badgeName, this.badgeIcon, status$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Incentive.IncentiveBuilder(title=" + this.title + ", description=" + this.description + ", targetType=" + this.targetType + ", targetValue=" + this.targetValue + ", rewardAmount=" + this.rewardAmount + ", badgeName=" + this.badgeName + ", badgeIcon=" + this.badgeIcon + ", status$value=" + this.status$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static Incentive.IncentiveBuilder builder() {
        return new Incentive.IncentiveBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Incentive() {
        this.status = Incentive.$default$status();
    }

    @java.lang.SuppressWarnings("all")
    
    public Incentive(final String title, final String description, final TargetType targetType, final BigDecimal targetValue, final BigDecimal rewardAmount, final String badgeName, final String badgeIcon, final Status status) {
        this.title = title;
        this.description = description;
        this.targetType = targetType;
        this.targetValue = targetValue;
        this.rewardAmount = rewardAmount;
        this.badgeName = badgeName;
        this.badgeIcon = badgeIcon;
        this.status = status;
    }
}
