// Generated by delombok at Fri Jul 24 16:18:01 IST 2026
package com.ripplenexus.salespilot.auth.presentation;

import com.ripplenexus.salespilot.auth.application.AdminUserService;
import com.ripplenexus.salespilot.core.dto.ApiResponse;
import com.ripplenexus.salespilot.employee.domain.Employee;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/admin/users")
public class AdminUserController {
    private final AdminUserService adminUserService;

    @PostMapping("/onboard")
    @PreAuthorize("hasRole(\'ADMIN\')")
    public ResponseEntity<ApiResponse<Employee>> onboardUser(@jakarta.validation.Valid @RequestBody OnboardUserRequest request) {
        Employee employee = adminUserService.onboardNewUser(request.getEmail(), request.getFirstName(), request.getLastName(), request.getRoleName());
        return ResponseEntity.ok(ApiResponse.success(employee));
    }


    public static class OnboardUserRequest {
        @jakarta.validation.constraints.Email
        @jakarta.validation.constraints.NotBlank
        private String email;
        @jakarta.validation.constraints.NotBlank
        private String firstName;
        @jakarta.validation.constraints.NotBlank
        private String lastName;
        @jakarta.validation.constraints.NotBlank
        private String roleName;

        public String getEmail() {
            return email;
        }

        public void setEmail(String email) {
            this.email = email;
        }

        public String getFirstName() {
            return firstName;
        }

        public void setFirstName(String firstName) {
            this.firstName = firstName;
        }

        public String getLastName() {
            return lastName;
        }

        public void setLastName(String lastName) {
            this.lastName = lastName;
        }

        public String getRoleName() {
            return roleName;
        }

        public void setRoleName(String roleName) {
            this.roleName = roleName;
        }

        @java.lang.SuppressWarnings("all")
        
        public OnboardUserRequest() {
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof AdminUserController.OnboardUserRequest)) return false;
            final AdminUserController.OnboardUserRequest other = (AdminUserController.OnboardUserRequest) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$email = this.getEmail();
            final java.lang.Object other$email = other.getEmail();
            if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
            final java.lang.Object this$firstName = this.getFirstName();
            final java.lang.Object other$firstName = other.getFirstName();
            if (this$firstName == null ? other$firstName != null : !this$firstName.equals(other$firstName)) return false;
            final java.lang.Object this$lastName = this.getLastName();
            final java.lang.Object other$lastName = other.getLastName();
            if (this$lastName == null ? other$lastName != null : !this$lastName.equals(other$lastName)) return false;
            final java.lang.Object this$roleName = this.getRoleName();
            final java.lang.Object other$roleName = other.getRoleName();
            if (this$roleName == null ? other$roleName != null : !this$roleName.equals(other$roleName)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof AdminUserController.OnboardUserRequest;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $email = this.getEmail();
            result = result * PRIME + ($email == null ? 43 : $email.hashCode());
            final java.lang.Object $firstName = this.getFirstName();
            result = result * PRIME + ($firstName == null ? 43 : $firstName.hashCode());
            final java.lang.Object $lastName = this.getLastName();
            result = result * PRIME + ($lastName == null ? 43 : $lastName.hashCode());
            final java.lang.Object $roleName = this.getRoleName();
            result = result * PRIME + ($roleName == null ? 43 : $roleName.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "AdminUserController.OnboardUserRequest(email=" + this.getEmail() + ", firstName=" + this.getFirstName() + ", lastName=" + this.getLastName() + ", roleName=" + this.getRoleName() + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public AdminUserController(final AdminUserService adminUserService) {
        this.adminUserService = adminUserService;
    }
}
