// Generated by delombok at Fri Jul 24 16:18:05 IST 2026
package com.ripplenexus.salespilot.lead.presentation.dto;

import com.ripplenexus.salespilot.lead.domain.Lead;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

public class LeadDto {
    private UUID id;
    private String leadNumber;
    private String contactName;
    private String contactDesignation;
    private String contactEmail;
    private String contactPhone;
    private String contactWhatsapp;
    private String contactLinkedin;
    private String companyName;
    private String companyWebsite;
    private String industry;
    private String country;
    private BigDecimal budget;
    private String currency;
    private String[] interestedServices;
    private String priority;
    private String sourceName;
    private UUID sourceId;
    private String assignedToName;
    private UUID assignedToId;
    private String status;
    private LocalDate expectedCloseDate;
    private Integer probability;
    private BigDecimal dealValue;
    private String notes;
    private int attachmentsCount;
    private Instant createdAt;
    private Instant updatedAt;
    private String createdBy;

    public static LeadDto from(Lead l) {
        LeadDto dto = new LeadDto();
        dto.setId(l.getId());
        dto.setLeadNumber(l.getLeadNumber());
        dto.setContactName(l.getContactName());
        dto.setContactDesignation(l.getContactDesignation());
        dto.setContactEmail(l.getContactEmail());
        dto.setContactPhone(l.getContactPhone());
        dto.setContactWhatsapp(l.getContactWhatsapp());
        dto.setContactLinkedin(l.getContactLinkedin());
        dto.setCompanyName(l.getCompanyName());
        dto.setCompanyWebsite(l.getCompanyWebsite());
        dto.setIndustry(l.getIndustry());
        dto.setCountry(l.getCountry());
        dto.setBudget(l.getBudget());
        dto.setCurrency(l.getCurrency());
        dto.setInterestedServices(l.getInterestedServices());
        dto.setPriority(l.getPriority().name());
        dto.setSourceName(l.getSource() != null ? l.getSource().getName() : null);
        dto.setSourceId(l.getSource() != null ? l.getSource().getId() : null);
        dto.setAssignedToName(l.getAssignedTo() != null ? l.getAssignedTo().getFullName() : null);
        dto.setAssignedToId(l.getAssignedTo() != null ? l.getAssignedTo().getId() : null);
        dto.setStatus(l.getStatus().name());
        dto.setExpectedCloseDate(l.getExpectedCloseDate());
        dto.setProbability(l.getProbability());
        dto.setDealValue(l.getDealValue());
        dto.setNotes(l.getNotes());
        dto.setAttachmentsCount(l.getAttachments() != null ? l.getAttachments().size() : 0);
        dto.setCreatedAt(l.getCreatedAt());
        dto.setUpdatedAt(l.getUpdatedAt());
        dto.setCreatedBy(l.getCreatedBy());
        return dto;
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getLeadNumber() {
        return leadNumber;
    }

    public void setLeadNumber(String leadNumber) {
        this.leadNumber = leadNumber;
    }

    public String getContactName() {
        return contactName;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    public String getContactDesignation() {
        return contactDesignation;
    }

    public void setContactDesignation(String contactDesignation) {
        this.contactDesignation = contactDesignation;
    }

    public String getContactEmail() {
        return contactEmail;
    }

    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }

    public String getContactPhone() {
        return contactPhone;
    }

    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }

    public String getContactWhatsapp() {
        return contactWhatsapp;
    }

    public void setContactWhatsapp(String contactWhatsapp) {
        this.contactWhatsapp = contactWhatsapp;
    }

    public String getContactLinkedin() {
        return contactLinkedin;
    }

    public void setContactLinkedin(String contactLinkedin) {
        this.contactLinkedin = contactLinkedin;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getCompanyWebsite() {
        return companyWebsite;
    }

    public void setCompanyWebsite(String companyWebsite) {
        this.companyWebsite = companyWebsite;
    }

    public String getIndustry() {
        return industry;
    }

    public void setIndustry(String industry) {
        this.industry = industry;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public BigDecimal getBudget() {
        return budget;
    }

    public void setBudget(BigDecimal budget) {
        this.budget = budget;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String[] getInterestedServices() {
        return interestedServices;
    }

    public void setInterestedServices(String[] interestedServices) {
        this.interestedServices = interestedServices;
    }

    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public String getSourceName() {
        return sourceName;
    }

    public void setSourceName(String sourceName) {
        this.sourceName = sourceName;
    }

    public UUID getSourceId() {
        return sourceId;
    }

    public void setSourceId(UUID sourceId) {
        this.sourceId = sourceId;
    }

    public String getAssignedToName() {
        return assignedToName;
    }

    public void setAssignedToName(String assignedToName) {
        this.assignedToName = assignedToName;
    }

    public UUID getAssignedToId() {
        return assignedToId;
    }

    public void setAssignedToId(UUID assignedToId) {
        this.assignedToId = assignedToId;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDate getExpectedCloseDate() {
        return expectedCloseDate;
    }

    public void setExpectedCloseDate(LocalDate expectedCloseDate) {
        this.expectedCloseDate = expectedCloseDate;
    }

    public Integer getProbability() {
        return probability;
    }

    public void setProbability(Integer probability) {
        this.probability = probability;
    }

    public BigDecimal getDealValue() {
        return dealValue;
    }

    public void setDealValue(BigDecimal dealValue) {
        this.dealValue = dealValue;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public int getAttachmentsCount() {
        return attachmentsCount;
    }

    public void setAttachmentsCount(int attachmentsCount) {
        this.attachmentsCount = attachmentsCount;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @java.lang.SuppressWarnings("all")
    
    LeadDto(final UUID id, final String leadNumber, final String contactName, final String contactDesignation, final String contactEmail, final String contactPhone, final String contactWhatsapp, final String contactLinkedin, final String companyName, final String companyWebsite, final String industry, final String country, final BigDecimal budget, final String currency, final String[] interestedServices, final String priority, final String sourceName, final UUID sourceId, final String assignedToName, final UUID assignedToId, final String status, final LocalDate expectedCloseDate, final Integer probability, final BigDecimal dealValue, final String notes, final int attachmentsCount, final Instant createdAt, final Instant updatedAt, final String createdBy) {
        this.id = id;
        this.leadNumber = leadNumber;
        this.contactName = contactName;
        this.contactDesignation = contactDesignation;
        this.contactEmail = contactEmail;
        this.contactPhone = contactPhone;
        this.contactWhatsapp = contactWhatsapp;
        this.contactLinkedin = contactLinkedin;
        this.companyName = companyName;
        this.companyWebsite = companyWebsite;
        this.industry = industry;
        this.country = country;
        this.budget = budget;
        this.currency = currency;
        this.interestedServices = interestedServices;
        this.priority = priority;
        this.sourceName = sourceName;
        this.sourceId = sourceId;
        this.assignedToName = assignedToName;
        this.assignedToId = assignedToId;
        this.status = status;
        this.expectedCloseDate = expectedCloseDate;
        this.probability = probability;
        this.dealValue = dealValue;
        this.notes = notes;
        this.attachmentsCount = attachmentsCount;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.createdBy = createdBy;
    }


    @java.lang.SuppressWarnings("all")
    
    public static class LeadDtoBuilder {
        @java.lang.SuppressWarnings("all")
        
        private UUID id;
        @java.lang.SuppressWarnings("all")
        
        private String leadNumber;
        @java.lang.SuppressWarnings("all")
        
        private String contactName;
        @java.lang.SuppressWarnings("all")
        
        private String contactDesignation;
        @java.lang.SuppressWarnings("all")
        
        private String contactEmail;
        @java.lang.SuppressWarnings("all")
        
        private String contactPhone;
        @java.lang.SuppressWarnings("all")
        
        private String contactWhatsapp;
        @java.lang.SuppressWarnings("all")
        
        private String contactLinkedin;
        @java.lang.SuppressWarnings("all")
        
        private String companyName;
        @java.lang.SuppressWarnings("all")
        
        private String companyWebsite;
        @java.lang.SuppressWarnings("all")
        
        private String industry;
        @java.lang.SuppressWarnings("all")
        
        private String country;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal budget;
        @java.lang.SuppressWarnings("all")
        
        private String currency;
        @java.lang.SuppressWarnings("all")
        
        private String[] interestedServices;
        @java.lang.SuppressWarnings("all")
        
        private String priority;
        @java.lang.SuppressWarnings("all")
        
        private String sourceName;
        @java.lang.SuppressWarnings("all")
        
        private UUID sourceId;
        @java.lang.SuppressWarnings("all")
        
        private String assignedToName;
        @java.lang.SuppressWarnings("all")
        
        private UUID assignedToId;
        @java.lang.SuppressWarnings("all")
        
        private String status;
        @java.lang.SuppressWarnings("all")
        
        private LocalDate expectedCloseDate;
        @java.lang.SuppressWarnings("all")
        
        private Integer probability;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal dealValue;
        @java.lang.SuppressWarnings("all")
        
        private String notes;
        @java.lang.SuppressWarnings("all")
        
        private int attachmentsCount;
        @java.lang.SuppressWarnings("all")
        
        private Instant createdAt;
        @java.lang.SuppressWarnings("all")
        
        private Instant updatedAt;
        @java.lang.SuppressWarnings("all")
        
        private String createdBy;

        @java.lang.SuppressWarnings("all")
        
        LeadDtoBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder id(final UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder leadNumber(final String leadNumber) {
            this.leadNumber = leadNumber;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder contactName(final String contactName) {
            this.contactName = contactName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder contactDesignation(final String contactDesignation) {
            this.contactDesignation = contactDesignation;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder contactEmail(final String contactEmail) {
            this.contactEmail = contactEmail;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder contactPhone(final String contactPhone) {
            this.contactPhone = contactPhone;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder contactWhatsapp(final String contactWhatsapp) {
            this.contactWhatsapp = contactWhatsapp;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder contactLinkedin(final String contactLinkedin) {
            this.contactLinkedin = contactLinkedin;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder companyName(final String companyName) {
            this.companyName = companyName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder companyWebsite(final String companyWebsite) {
            this.companyWebsite = companyWebsite;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder industry(final String industry) {
            this.industry = industry;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder country(final String country) {
            this.country = country;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder budget(final BigDecimal budget) {
            this.budget = budget;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder currency(final String currency) {
            this.currency = currency;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder interestedServices(final String[] interestedServices) {
            this.interestedServices = interestedServices;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder priority(final String priority) {
            this.priority = priority;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder sourceName(final String sourceName) {
            this.sourceName = sourceName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder sourceId(final UUID sourceId) {
            this.sourceId = sourceId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder assignedToName(final String assignedToName) {
            this.assignedToName = assignedToName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder assignedToId(final UUID assignedToId) {
            this.assignedToId = assignedToId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder status(final String status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder expectedCloseDate(final LocalDate expectedCloseDate) {
            this.expectedCloseDate = expectedCloseDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder probability(final Integer probability) {
            this.probability = probability;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder dealValue(final BigDecimal dealValue) {
            this.dealValue = dealValue;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder notes(final String notes) {
            this.notes = notes;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder attachmentsCount(final int attachmentsCount) {
            this.attachmentsCount = attachmentsCount;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder createdAt(final Instant createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder updatedAt(final Instant updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public LeadDto.LeadDtoBuilder createdBy(final String createdBy) {
            this.createdBy = createdBy;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public LeadDto build() {
            return new LeadDto(this.id, this.leadNumber, this.contactName, this.contactDesignation, this.contactEmail, this.contactPhone, this.contactWhatsapp, this.contactLinkedin, this.companyName, this.companyWebsite, this.industry, this.country, this.budget, this.currency, this.interestedServices, this.priority, this.sourceName, this.sourceId, this.assignedToName, this.assignedToId, this.status, this.expectedCloseDate, this.probability, this.dealValue, this.notes, this.attachmentsCount, this.createdAt, this.updatedAt, this.createdBy);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "LeadDto.LeadDtoBuilder(id=" + this.id + ", leadNumber=" + this.leadNumber + ", contactName=" + this.contactName + ", contactDesignation=" + this.contactDesignation + ", contactEmail=" + this.contactEmail + ", contactPhone=" + this.contactPhone + ", contactWhatsapp=" + this.contactWhatsapp + ", contactLinkedin=" + this.contactLinkedin + ", companyName=" + this.companyName + ", companyWebsite=" + this.companyWebsite + ", industry=" + this.industry + ", country=" + this.country + ", budget=" + this.budget + ", currency=" + this.currency + ", interestedServices=" + java.util.Arrays.deepToString(this.interestedServices) + ", priority=" + this.priority + ", sourceName=" + this.sourceName + ", sourceId=" + this.sourceId + ", assignedToName=" + this.assignedToName + ", assignedToId=" + this.assignedToId + ", status=" + this.status + ", expectedCloseDate=" + this.expectedCloseDate + ", probability=" + this.probability + ", dealValue=" + this.dealValue + ", notes=" + this.notes + ", attachmentsCount=" + this.attachmentsCount + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ", createdBy=" + this.createdBy + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static LeadDto.LeadDtoBuilder builder() {
        return new LeadDto.LeadDtoBuilder();
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof LeadDto)) return false;
        final LeadDto other = (LeadDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getAttachmentsCount() != other.getAttachmentsCount()) return false;
        final java.lang.Object this$probability = this.getProbability();
        final java.lang.Object other$probability = other.getProbability();
        if (this$probability == null ? other$probability != null : !this$probability.equals(other$probability)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$leadNumber = this.getLeadNumber();
        final java.lang.Object other$leadNumber = other.getLeadNumber();
        if (this$leadNumber == null ? other$leadNumber != null : !this$leadNumber.equals(other$leadNumber)) return false;
        final java.lang.Object this$contactName = this.getContactName();
        final java.lang.Object other$contactName = other.getContactName();
        if (this$contactName == null ? other$contactName != null : !this$contactName.equals(other$contactName)) return false;
        final java.lang.Object this$contactDesignation = this.getContactDesignation();
        final java.lang.Object other$contactDesignation = other.getContactDesignation();
        if (this$contactDesignation == null ? other$contactDesignation != null : !this$contactDesignation.equals(other$contactDesignation)) return false;
        final java.lang.Object this$contactEmail = this.getContactEmail();
        final java.lang.Object other$contactEmail = other.getContactEmail();
        if (this$contactEmail == null ? other$contactEmail != null : !this$contactEmail.equals(other$contactEmail)) return false;
        final java.lang.Object this$contactPhone = this.getContactPhone();
        final java.lang.Object other$contactPhone = other.getContactPhone();
        if (this$contactPhone == null ? other$contactPhone != null : !this$contactPhone.equals(other$contactPhone)) return false;
        final java.lang.Object this$contactWhatsapp = this.getContactWhatsapp();
        final java.lang.Object other$contactWhatsapp = other.getContactWhatsapp();
        if (this$contactWhatsapp == null ? other$contactWhatsapp != null : !this$contactWhatsapp.equals(other$contactWhatsapp)) return false;
        final java.lang.Object this$contactLinkedin = this.getContactLinkedin();
        final java.lang.Object other$contactLinkedin = other.getContactLinkedin();
        if (this$contactLinkedin == null ? other$contactLinkedin != null : !this$contactLinkedin.equals(other$contactLinkedin)) return false;
        final java.lang.Object this$companyName = this.getCompanyName();
        final java.lang.Object other$companyName = other.getCompanyName();
        if (this$companyName == null ? other$companyName != null : !this$companyName.equals(other$companyName)) return false;
        final java.lang.Object this$companyWebsite = this.getCompanyWebsite();
        final java.lang.Object other$companyWebsite = other.getCompanyWebsite();
        if (this$companyWebsite == null ? other$companyWebsite != null : !this$companyWebsite.equals(other$companyWebsite)) return false;
        final java.lang.Object this$industry = this.getIndustry();
        final java.lang.Object other$industry = other.getIndustry();
        if (this$industry == null ? other$industry != null : !this$industry.equals(other$industry)) return false;
        final java.lang.Object this$country = this.getCountry();
        final java.lang.Object other$country = other.getCountry();
        if (this$country == null ? other$country != null : !this$country.equals(other$country)) return false;
        final java.lang.Object this$budget = this.getBudget();
        final java.lang.Object other$budget = other.getBudget();
        if (this$budget == null ? other$budget != null : !this$budget.equals(other$budget)) return false;
        final java.lang.Object this$currency = this.getCurrency();
        final java.lang.Object other$currency = other.getCurrency();
        if (this$currency == null ? other$currency != null : !this$currency.equals(other$currency)) return false;
        if (!java.util.Arrays.deepEquals(this.getInterestedServices(), other.getInterestedServices())) return false;
        final java.lang.Object this$priority = this.getPriority();
        final java.lang.Object other$priority = other.getPriority();
        if (this$priority == null ? other$priority != null : !this$priority.equals(other$priority)) return false;
        final java.lang.Object this$sourceName = this.getSourceName();
        final java.lang.Object other$sourceName = other.getSourceName();
        if (this$sourceName == null ? other$sourceName != null : !this$sourceName.equals(other$sourceName)) return false;
        final java.lang.Object this$sourceId = this.getSourceId();
        final java.lang.Object other$sourceId = other.getSourceId();
        if (this$sourceId == null ? other$sourceId != null : !this$sourceId.equals(other$sourceId)) return false;
        final java.lang.Object this$assignedToName = this.getAssignedToName();
        final java.lang.Object other$assignedToName = other.getAssignedToName();
        if (this$assignedToName == null ? other$assignedToName != null : !this$assignedToName.equals(other$assignedToName)) return false;
        final java.lang.Object this$assignedToId = this.getAssignedToId();
        final java.lang.Object other$assignedToId = other.getAssignedToId();
        if (this$assignedToId == null ? other$assignedToId != null : !this$assignedToId.equals(other$assignedToId)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$expectedCloseDate = this.getExpectedCloseDate();
        final java.lang.Object other$expectedCloseDate = other.getExpectedCloseDate();
        if (this$expectedCloseDate == null ? other$expectedCloseDate != null : !this$expectedCloseDate.equals(other$expectedCloseDate)) return false;
        final java.lang.Object this$dealValue = this.getDealValue();
        final java.lang.Object other$dealValue = other.getDealValue();
        if (this$dealValue == null ? other$dealValue != null : !this$dealValue.equals(other$dealValue)) return false;
        final java.lang.Object this$notes = this.getNotes();
        final java.lang.Object other$notes = other.getNotes();
        if (this$notes == null ? other$notes != null : !this$notes.equals(other$notes)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$updatedAt = this.getUpdatedAt();
        final java.lang.Object other$updatedAt = other.getUpdatedAt();
        if (this$updatedAt == null ? other$updatedAt != null : !this$updatedAt.equals(other$updatedAt)) return false;
        final java.lang.Object this$createdBy = this.getCreatedBy();
        final java.lang.Object other$createdBy = other.getCreatedBy();
        if (this$createdBy == null ? other$createdBy != null : !this$createdBy.equals(other$createdBy)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof LeadDto;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getAttachmentsCount();
        final java.lang.Object $probability = this.getProbability();
        result = result * PRIME + ($probability == null ? 43 : $probability.hashCode());
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $leadNumber = this.getLeadNumber();
        result = result * PRIME + ($leadNumber == null ? 43 : $leadNumber.hashCode());
        final java.lang.Object $contactName = this.getContactName();
        result = result * PRIME + ($contactName == null ? 43 : $contactName.hashCode());
        final java.lang.Object $contactDesignation = this.getContactDesignation();
        result = result * PRIME + ($contactDesignation == null ? 43 : $contactDesignation.hashCode());
        final java.lang.Object $contactEmail = this.getContactEmail();
        result = result * PRIME + ($contactEmail == null ? 43 : $contactEmail.hashCode());
        final java.lang.Object $contactPhone = this.getContactPhone();
        result = result * PRIME + ($contactPhone == null ? 43 : $contactPhone.hashCode());
        final java.lang.Object $contactWhatsapp = this.getContactWhatsapp();
        result = result * PRIME + ($contactWhatsapp == null ? 43 : $contactWhatsapp.hashCode());
        final java.lang.Object $contactLinkedin = this.getContactLinkedin();
        result = result * PRIME + ($contactLinkedin == null ? 43 : $contactLinkedin.hashCode());
        final java.lang.Object $companyName = this.getCompanyName();
        result = result * PRIME + ($companyName == null ? 43 : $companyName.hashCode());
        final java.lang.Object $companyWebsite = this.getCompanyWebsite();
        result = result * PRIME + ($companyWebsite == null ? 43 : $companyWebsite.hashCode());
        final java.lang.Object $industry = this.getIndustry();
        result = result * PRIME + ($industry == null ? 43 : $industry.hashCode());
        final java.lang.Object $country = this.getCountry();
        result = result * PRIME + ($country == null ? 43 : $country.hashCode());
        final java.lang.Object $budget = this.getBudget();
        result = result * PRIME + ($budget == null ? 43 : $budget.hashCode());
        final java.lang.Object $currency = this.getCurrency();
        result = result * PRIME + ($currency == null ? 43 : $currency.hashCode());
        result = result * PRIME + java.util.Arrays.deepHashCode(this.getInterestedServices());
        final java.lang.Object $priority = this.getPriority();
        result = result * PRIME + ($priority == null ? 43 : $priority.hashCode());
        final java.lang.Object $sourceName = this.getSourceName();
        result = result * PRIME + ($sourceName == null ? 43 : $sourceName.hashCode());
        final java.lang.Object $sourceId = this.getSourceId();
        result = result * PRIME + ($sourceId == null ? 43 : $sourceId.hashCode());
        final java.lang.Object $assignedToName = this.getAssignedToName();
        result = result * PRIME + ($assignedToName == null ? 43 : $assignedToName.hashCode());
        final java.lang.Object $assignedToId = this.getAssignedToId();
        result = result * PRIME + ($assignedToId == null ? 43 : $assignedToId.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $expectedCloseDate = this.getExpectedCloseDate();
        result = result * PRIME + ($expectedCloseDate == null ? 43 : $expectedCloseDate.hashCode());
        final java.lang.Object $dealValue = this.getDealValue();
        result = result * PRIME + ($dealValue == null ? 43 : $dealValue.hashCode());
        final java.lang.Object $notes = this.getNotes();
        result = result * PRIME + ($notes == null ? 43 : $notes.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $updatedAt = this.getUpdatedAt();
        result = result * PRIME + ($updatedAt == null ? 43 : $updatedAt.hashCode());
        final java.lang.Object $createdBy = this.getCreatedBy();
        result = result * PRIME + ($createdBy == null ? 43 : $createdBy.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public java.lang.String toString() {
        return "LeadDto(id=" + this.getId() + ", leadNumber=" + this.getLeadNumber() + ", contactName=" + this.getContactName() + ", contactDesignation=" + this.getContactDesignation() + ", contactEmail=" + this.getContactEmail() + ", contactPhone=" + this.getContactPhone() + ", contactWhatsapp=" + this.getContactWhatsapp() + ", contactLinkedin=" + this.getContactLinkedin() + ", companyName=" + this.getCompanyName() + ", companyWebsite=" + this.getCompanyWebsite() + ", industry=" + this.getIndustry() + ", country=" + this.getCountry() + ", budget=" + this.getBudget() + ", currency=" + this.getCurrency() + ", interestedServices=" + java.util.Arrays.deepToString(this.getInterestedServices()) + ", priority=" + this.getPriority() + ", sourceName=" + this.getSourceName() + ", sourceId=" + this.getSourceId() + ", assignedToName=" + this.getAssignedToName() + ", assignedToId=" + this.getAssignedToId() + ", status=" + this.getStatus() + ", expectedCloseDate=" + this.getExpectedCloseDate() + ", probability=" + this.getProbability() + ", dealValue=" + this.getDealValue() + ", notes=" + this.getNotes() + ", attachmentsCount=" + this.getAttachmentsCount() + ", createdAt=" + this.getCreatedAt() + ", updatedAt=" + this.getUpdatedAt() + ", createdBy=" + this.getCreatedBy() + ")";
    }
}
