// Generated by delombok at Fri Jul 24 16:18:05 IST 2026
package com.ripplenexus.salespilot.lead.presentation.dto;

import com.ripplenexus.salespilot.lead.domain.Lead;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;

public class UpdateLeadRequest {
    private String contactName;
    private String contactDesignation;
    private String contactEmail;
    private String contactPhone;
    private String contactWhatsapp;
    private String contactLinkedin;
    private String companyName;
    private String companyWebsite;
    private String industry;
    private String country;
    private BigDecimal budget;
    private String[] interestedServices;
    private Lead.LeadPriority priority;
    private UUID sourceId;
    private UUID assignedToId;
    private Lead.LeadStatus status;
    private LocalDate expectedCloseDate;
    private Integer probability;
    private String notes;

    public String getContactName() {
        return contactName;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    public String getContactDesignation() {
        return contactDesignation;
    }

    public void setContactDesignation(String contactDesignation) {
        this.contactDesignation = contactDesignation;
    }

    public String getContactEmail() {
        return contactEmail;
    }

    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }

    public String getContactPhone() {
        return contactPhone;
    }

    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }

    public String getContactWhatsapp() {
        return contactWhatsapp;
    }

    public void setContactWhatsapp(String contactWhatsapp) {
        this.contactWhatsapp = contactWhatsapp;
    }

    public String getContactLinkedin() {
        return contactLinkedin;
    }

    public void setContactLinkedin(String contactLinkedin) {
        this.contactLinkedin = contactLinkedin;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getCompanyWebsite() {
        return companyWebsite;
    }

    public void setCompanyWebsite(String companyWebsite) {
        this.companyWebsite = companyWebsite;
    }

    public String getIndustry() {
        return industry;
    }

    public void setIndustry(String industry) {
        this.industry = industry;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public BigDecimal getBudget() {
        return budget;
    }

    public void setBudget(BigDecimal budget) {
        this.budget = budget;
    }

    public String[] getInterestedServices() {
        return interestedServices;
    }

    public void setInterestedServices(String[] interestedServices) {
        this.interestedServices = interestedServices;
    }

    public Lead.LeadPriority getPriority() {
        return priority;
    }

    public void setPriority(Lead.LeadPriority priority) {
        this.priority = priority;
    }

    public UUID getSourceId() {
        return sourceId;
    }

    public void setSourceId(UUID sourceId) {
        this.sourceId = sourceId;
    }

    public UUID getAssignedToId() {
        return assignedToId;
    }

    public void setAssignedToId(UUID assignedToId) {
        this.assignedToId = assignedToId;
    }

    public Lead.LeadStatus getStatus() {
        return status;
    }

    public void setStatus(Lead.LeadStatus status) {
        this.status = status;
    }

    public LocalDate getExpectedCloseDate() {
        return expectedCloseDate;
    }

    public void setExpectedCloseDate(LocalDate expectedCloseDate) {
        this.expectedCloseDate = expectedCloseDate;
    }

    public Integer getProbability() {
        return probability;
    }

    public void setProbability(Integer probability) {
        this.probability = probability;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    @java.lang.SuppressWarnings("all")
    
    public UpdateLeadRequest() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof UpdateLeadRequest)) return false;
        final UpdateLeadRequest other = (UpdateLeadRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$probability = this.getProbability();
        final java.lang.Object other$probability = other.getProbability();
        if (this$probability == null ? other$probability != null : !this$probability.equals(other$probability)) return false;
        final java.lang.Object this$contactName = this.getContactName();
        final java.lang.Object other$contactName = other.getContactName();
        if (this$contactName == null ? other$contactName != null : !this$contactName.equals(other$contactName)) return false;
        final java.lang.Object this$contactDesignation = this.getContactDesignation();
        final java.lang.Object other$contactDesignation = other.getContactDesignation();
        if (this$contactDesignation == null ? other$contactDesignation != null : !this$contactDesignation.equals(other$contactDesignation)) return false;
        final java.lang.Object this$contactEmail = this.getContactEmail();
        final java.lang.Object other$contactEmail = other.getContactEmail();
        if (this$contactEmail == null ? other$contactEmail != null : !this$contactEmail.equals(other$contactEmail)) return false;
        final java.lang.Object this$contactPhone = this.getContactPhone();
        final java.lang.Object other$contactPhone = other.getContactPhone();
        if (this$contactPhone == null ? other$contactPhone != null : !this$contactPhone.equals(other$contactPhone)) return false;
        final java.lang.Object this$contactWhatsapp = this.getContactWhatsapp();
        final java.lang.Object other$contactWhatsapp = other.getContactWhatsapp();
        if (this$contactWhatsapp == null ? other$contactWhatsapp != null : !this$contactWhatsapp.equals(other$contactWhatsapp)) return false;
        final java.lang.Object this$contactLinkedin = this.getContactLinkedin();
        final java.lang.Object other$contactLinkedin = other.getContactLinkedin();
        if (this$contactLinkedin == null ? other$contactLinkedin != null : !this$contactLinkedin.equals(other$contactLinkedin)) return false;
        final java.lang.Object this$companyName = this.getCompanyName();
        final java.lang.Object other$companyName = other.getCompanyName();
        if (this$companyName == null ? other$companyName != null : !this$companyName.equals(other$companyName)) return false;
        final java.lang.Object this$companyWebsite = this.getCompanyWebsite();
        final java.lang.Object other$companyWebsite = other.getCompanyWebsite();
        if (this$companyWebsite == null ? other$companyWebsite != null : !this$companyWebsite.equals(other$companyWebsite)) return false;
        final java.lang.Object this$industry = this.getIndustry();
        final java.lang.Object other$industry = other.getIndustry();
        if (this$industry == null ? other$industry != null : !this$industry.equals(other$industry)) return false;
        final java.lang.Object this$country = this.getCountry();
        final java.lang.Object other$country = other.getCountry();
        if (this$country == null ? other$country != null : !this$country.equals(other$country)) return false;
        final java.lang.Object this$budget = this.getBudget();
        final java.lang.Object other$budget = other.getBudget();
        if (this$budget == null ? other$budget != null : !this$budget.equals(other$budget)) return false;
        if (!java.util.Arrays.deepEquals(this.getInterestedServices(), other.getInterestedServices())) return false;
        final java.lang.Object this$priority = this.getPriority();
        final java.lang.Object other$priority = other.getPriority();
        if (this$priority == null ? other$priority != null : !this$priority.equals(other$priority)) return false;
        final java.lang.Object this$sourceId = this.getSourceId();
        final java.lang.Object other$sourceId = other.getSourceId();
        if (this$sourceId == null ? other$sourceId != null : !this$sourceId.equals(other$sourceId)) return false;
        final java.lang.Object this$assignedToId = this.getAssignedToId();
        final java.lang.Object other$assignedToId = other.getAssignedToId();
        if (this$assignedToId == null ? other$assignedToId != null : !this$assignedToId.equals(other$assignedToId)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$expectedCloseDate = this.getExpectedCloseDate();
        final java.lang.Object other$expectedCloseDate = other.getExpectedCloseDate();
        if (this$expectedCloseDate == null ? other$expectedCloseDate != null : !this$expectedCloseDate.equals(other$expectedCloseDate)) return false;
        final java.lang.Object this$notes = this.getNotes();
        final java.lang.Object other$notes = other.getNotes();
        if (this$notes == null ? other$notes != null : !this$notes.equals(other$notes)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof UpdateLeadRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $probability = this.getProbability();
        result = result * PRIME + ($probability == null ? 43 : $probability.hashCode());
        final java.lang.Object $contactName = this.getContactName();
        result = result * PRIME + ($contactName == null ? 43 : $contactName.hashCode());
        final java.lang.Object $contactDesignation = this.getContactDesignation();
        result = result * PRIME + ($contactDesignation == null ? 43 : $contactDesignation.hashCode());
        final java.lang.Object $contactEmail = this.getContactEmail();
        result = result * PRIME + ($contactEmail == null ? 43 : $contactEmail.hashCode());
        final java.lang.Object $contactPhone = this.getContactPhone();
        result = result * PRIME + ($contactPhone == null ? 43 : $contactPhone.hashCode());
        final java.lang.Object $contactWhatsapp = this.getContactWhatsapp();
        result = result * PRIME + ($contactWhatsapp == null ? 43 : $contactWhatsapp.hashCode());
        final java.lang.Object $contactLinkedin = this.getContactLinkedin();
        result = result * PRIME + ($contactLinkedin == null ? 43 : $contactLinkedin.hashCode());
        final java.lang.Object $companyName = this.getCompanyName();
        result = result * PRIME + ($companyName == null ? 43 : $companyName.hashCode());
        final java.lang.Object $companyWebsite = this.getCompanyWebsite();
        result = result * PRIME + ($companyWebsite == null ? 43 : $companyWebsite.hashCode());
        final java.lang.Object $industry = this.getIndustry();
        result = result * PRIME + ($industry == null ? 43 : $industry.hashCode());
        final java.lang.Object $country = this.getCountry();
        result = result * PRIME + ($country == null ? 43 : $country.hashCode());
        final java.lang.Object $budget = this.getBudget();
        result = result * PRIME + ($budget == null ? 43 : $budget.hashCode());
        result = result * PRIME + java.util.Arrays.deepHashCode(this.getInterestedServices());
        final java.lang.Object $priority = this.getPriority();
        result = result * PRIME + ($priority == null ? 43 : $priority.hashCode());
        final java.lang.Object $sourceId = this.getSourceId();
        result = result * PRIME + ($sourceId == null ? 43 : $sourceId.hashCode());
        final java.lang.Object $assignedToId = this.getAssignedToId();
        result = result * PRIME + ($assignedToId == null ? 43 : $assignedToId.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $expectedCloseDate = this.getExpectedCloseDate();
        result = result * PRIME + ($expectedCloseDate == null ? 43 : $expectedCloseDate.hashCode());
        final java.lang.Object $notes = this.getNotes();
        result = result * PRIME + ($notes == null ? 43 : $notes.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public java.lang.String toString() {
        return "UpdateLeadRequest(contactName=" + this.getContactName() + ", contactDesignation=" + this.getContactDesignation() + ", contactEmail=" + this.getContactEmail() + ", contactPhone=" + this.getContactPhone() + ", contactWhatsapp=" + this.getContactWhatsapp() + ", contactLinkedin=" + this.getContactLinkedin() + ", companyName=" + this.getCompanyName() + ", companyWebsite=" + this.getCompanyWebsite() + ", industry=" + this.getIndustry() + ", country=" + this.getCountry() + ", budget=" + this.getBudget() + ", interestedServices=" + java.util.Arrays.deepToString(this.getInterestedServices()) + ", priority=" + this.getPriority() + ", sourceId=" + this.getSourceId() + ", assignedToId=" + this.getAssignedToId() + ", status=" + this.getStatus() + ", expectedCloseDate=" + this.getExpectedCloseDate() + ", probability=" + this.getProbability() + ", notes=" + this.getNotes() + ")";
    }
}
