// Generated by delombok at Fri Jul 24 16:18:06 IST 2026
package com.ripplenexus.salespilot.pipeline.presentation;

import com.ripplenexus.salespilot.core.dto.ApiResponse;
import com.ripplenexus.salespilot.pipeline.application.PipelineService;
import com.ripplenexus.salespilot.pipeline.domain.PipelineEntry;
import com.ripplenexus.salespilot.pipeline.domain.PipelineStage;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;
import java.util.List;
import java.util.UUID;

@RestController
@RequestMapping("/pipeline")
public class PipelineController {
    private final PipelineService pipelineService;

    @GetMapping("/stages")
    @PreAuthorize("hasAnyRole(\'ADMIN\', \'SALES_MANAGER\', \'SALES_EXEC\')")
    public ResponseEntity<ApiResponse<List<PipelineStage>>> getStages() {
        return ResponseEntity.ok(ApiResponse.success(pipelineService.getStages()));
    }

    @GetMapping("/entries")
    @PreAuthorize("hasAnyRole(\'ADMIN\', \'SALES_MANAGER\', \'SALES_EXEC\')")
    public ResponseEntity<ApiResponse<List<PipelineEntry>>> getEntries(@org.springframework.security.core.annotation.AuthenticationPrincipal com.ripplenexus.salespilot.auth.domain.User currentUser) {
        return ResponseEntity.ok(ApiResponse.success(pipelineService.getEntries(currentUser)));
    }

    @PutMapping("/entries/{leadId}/stage")
    @PreAuthorize("hasAnyRole(\'ADMIN\', \'SALES_MANAGER\', \'SALES_EXEC\')")
    public ResponseEntity<ApiResponse<Void>> updateStage(@PathVariable UUID leadId, @jakarta.validation.Valid @RequestBody UpdateStageRequest request, @org.springframework.security.core.annotation.AuthenticationPrincipal com.ripplenexus.salespilot.auth.domain.User currentUser) {
        pipelineService.updateLeadStage(leadId, request.getStageId(), request.getPosition(), currentUser);
        return ResponseEntity.ok(ApiResponse.success(null));
    }


    public static class UpdateStageRequest {
        @jakarta.validation.constraints.NotNull(message = "Stage ID cannot be null")
        private UUID stageId;
        @jakarta.validation.constraints.Min(value = 0, message = "Position cannot be negative")
        private int position;

        public UUID getStageId() {
            return stageId;
        }

        public void setStageId(UUID stageId) {
            this.stageId = stageId;
        }

        public int getPosition() {
            return position;
        }

        public void setPosition(int position) {
            this.position = position;
        }

        @java.lang.SuppressWarnings("all")
        
        public UpdateStageRequest() {
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof PipelineController.UpdateStageRequest)) return false;
            final PipelineController.UpdateStageRequest other = (PipelineController.UpdateStageRequest) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (this.getPosition() != other.getPosition()) return false;
            final java.lang.Object this$stageId = this.getStageId();
            final java.lang.Object other$stageId = other.getStageId();
            if (this$stageId == null ? other$stageId != null : !this$stageId.equals(other$stageId)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof PipelineController.UpdateStageRequest;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            result = result * PRIME + this.getPosition();
            final java.lang.Object $stageId = this.getStageId();
            result = result * PRIME + ($stageId == null ? 43 : $stageId.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "PipelineController.UpdateStageRequest(stageId=" + this.getStageId() + ", position=" + this.getPosition() + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public PipelineController(final PipelineService pipelineService) {
        this.pipelineService = pipelineService;
    }
}
