// Generated by delombok at Fri Jul 24 16:18:04 IST 2026
package com.ripplenexus.salespilot.employee.application;

import com.ripplenexus.salespilot.auth.domain.Role;
import com.ripplenexus.salespilot.auth.domain.User;
import com.ripplenexus.salespilot.auth.infrastructure.RoleRepository;
import com.ripplenexus.salespilot.auth.infrastructure.UserRepository;
import com.ripplenexus.salespilot.core.dto.PageResponse;
import com.ripplenexus.salespilot.core.email.EmailService;
import com.ripplenexus.salespilot.core.exception.BusinessException;
import com.ripplenexus.salespilot.core.exception.DuplicateResourceException;
import com.ripplenexus.salespilot.core.exception.ResourceNotFoundException;
import com.ripplenexus.salespilot.employee.domain.Department;
import com.ripplenexus.salespilot.employee.domain.Employee;
import com.ripplenexus.salespilot.commission.domain.CommissionRule;
import com.ripplenexus.salespilot.commission.domain.EmployeeCommissionPlan;
import com.ripplenexus.salespilot.commission.infrastructure.CommissionPlanRepository;
import com.ripplenexus.salespilot.commission.infrastructure.CommissionRuleRepository;
import com.ripplenexus.salespilot.employee.infrastructure.DepartmentRepository;
import com.ripplenexus.salespilot.employee.infrastructure.EmployeeRepository;
import com.ripplenexus.salespilot.employee.presentation.dto.CreateEmployeeRequest;
import com.ripplenexus.salespilot.employee.presentation.dto.EmployeeDto;
import com.ripplenexus.salespilot.employee.presentation.dto.KycSubmissionRequest;
import com.ripplenexus.salespilot.employee.presentation.dto.AdminUpdateEmployeeRequest;
import com.ripplenexus.salespilot.employee.presentation.dto.UpdateEmployeeProfileRequest;
import jakarta.transaction.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import java.security.SecureRandom;
import java.time.YearMonth;
import java.util.Set;
import java.util.UUID;

@Service
@Transactional
public class EmployeeService {
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(EmployeeService.class);
    private static final java.util.Random RANDOM = new java.security.SecureRandom();
    private final EmployeeRepository employeeRepository;
    private final UserRepository userRepository;
    private final RoleRepository roleRepository;
    private final DepartmentRepository departmentRepository;
    private final CommissionRuleRepository commissionRuleRepository;
    private final CommissionPlanRepository commissionPlanRepository;
    private final PasswordEncoder passwordEncoder;
    private final EmailService emailService;

    public EmployeeDto createEmployee(CreateEmployeeRequest request) {
        if (userRepository.existsByEmail(request.getWorkEmail())) {
            throw new DuplicateResourceException("An employee with email " + request.getWorkEmail() + " already exists.");
        }
        // Generate temporary password
        String tempPassword = generateTempPassword();
        // Create user account
        Role role = roleRepository.findByName(request.getRole()).orElseThrow(() -> new ResourceNotFoundException("Role", request.getRole()));
        User user = new User();
        user.setEmail(request.getWorkEmail());
        user.setPasswordHash(passwordEncoder.encode(tempPassword));
        user.setActive(true);
        user.setEmailVerified(false);
        user.setRoles(Set.of(role));
        userRepository.save(user);
        // Build employee
        Employee employee = new Employee();
        employee.setUser(user);
        employee.setEmployeeNumber(generateEmployeeNumber());
        employee.setFirstName(request.getFirstName());
        employee.setLastName(request.getLastName());
        employee.setWorkEmail(request.getWorkEmail());
        employee.setPersonalEmail(request.getPersonalEmail());
        employee.setPhone(request.getPhone());
        employee.setWhatsapp(request.getWhatsapp());
        employee.setDesignation(request.getDesignation());
        employee.setJoiningDate(request.getJoiningDate());
        employee.setStatus(Employee.EmploymentStatus.ACTIVE);
        employee.setSalary(request.getSalary());
        employee.setNotes(request.getNotes());
        if (request.getDepartmentId() != null) {
            Department dept = departmentRepository.findById(request.getDepartmentId()).orElseThrow(() -> new ResourceNotFoundException("Department", request.getDepartmentId()));
            employee.setDepartment(dept);
        }
        if (request.getManagerId() != null) {
            Employee manager = employeeRepository.findById(request.getManagerId()).orElseThrow(() -> new ResourceNotFoundException("Manager", request.getManagerId()));
            employee.setManager(manager);
        }
        employee = employeeRepository.save(employee);
        // Assign default 10% commission rule
        CommissionRule rule = commissionRuleRepository.findByName("Default 10% Commission").orElseGet(() -> {
            CommissionRule newRule = new CommissionRule();
            newRule.setName("Default 10% Commission");
            newRule.setType(CommissionRule.CommissionType.PERCENTAGE);
            newRule.setPercentage(java.math.BigDecimal.valueOf(10.0));
            newRule.setActive(true);
            return commissionRuleRepository.save(newRule);
        });
        EmployeeCommissionPlan plan = new EmployeeCommissionPlan();
        plan.setEmployee(employee);
        plan.setRule(rule);
        plan.setEffectiveFrom(java.time.LocalDate.now());
        plan.setActive(true);
        commissionPlanRepository.save(plan);
        // Send welcome email asynchronously
        emailService.sendWelcomeEmail(request.getWorkEmail(), request.getFirstName(), tempPassword);
        log.info("Employee created: {} ({})", employee.getFullName(), employee.getEmployeeNumber());
        return EmployeeDto.from(employee);
    }

    public EmployeeDto updateAdminDetails(UUID id, AdminUpdateEmployeeRequest request) {
        Employee employee = getEmployeeOrThrow(id);
        if (request.getFirstName() != null) employee.setFirstName(request.getFirstName());
        if (request.getLastName() != null) employee.setLastName(request.getLastName());
        if (request.getPhone() != null) employee.setPhone(request.getPhone());
        if (request.getWhatsapp() != null) employee.setWhatsapp(request.getWhatsapp());
        if (request.getDesignation() != null) employee.setDesignation(request.getDesignation());
        if (request.getAddress() != null) employee.setAddress(request.getAddress());
        if (request.getCity() != null) employee.setCity(request.getCity());
        if (request.getState() != null) employee.setState(request.getState());
        if (request.getCountry() != null) employee.setCountry(request.getCountry());
        if (request.getPincode() != null) employee.setPincode(request.getPincode());
        if (request.getNotes() != null) employee.setNotes(request.getNotes());
        if (request.getStatus() != null) employee.setStatus(request.getStatus());
        if (request.getSalary() != null) employee.setSalary(request.getSalary());
        if (request.getPerformanceRating() != null) employee.setPerformanceRating(request.getPerformanceRating());
        if (request.getTerritories() != null) employee.setTerritories(request.getTerritories());
        if (request.getIndustries() != null) employee.setIndustries(request.getIndustries());
        if (request.getServices() != null) employee.setServices(request.getServices());
        if (request.getEmergencyName() != null) employee.setEmergencyName(request.getEmergencyName());
        if (request.getEmergencyPhone() != null) employee.setEmergencyPhone(request.getEmergencyPhone());
        if (request.getEmergencyRelation() != null) employee.setEmergencyRelation(request.getEmergencyRelation());
        if (request.getDepartmentId() != null) {
            Department dept = departmentRepository.findById(request.getDepartmentId()).orElseThrow(() -> new ResourceNotFoundException("Department", request.getDepartmentId()));
            employee.setDepartment(dept);
        }
        if (request.getManagerId() != null) {
            if (request.getManagerId().equals(id)) {
                throw new BusinessException("An employee cannot be their own manager.");
            }
            Employee manager = employeeRepository.findById(request.getManagerId()).orElseThrow(() -> new ResourceNotFoundException("Manager", request.getManagerId()));
            employee.setManager(manager);
        }
        employeeRepository.save(employee);
        log.info("Employee admin details updated: {}", employee.getEmployeeNumber());
        return EmployeeDto.from(employee);
    }

    public EmployeeDto updateProfile(UUID id, UpdateEmployeeProfileRequest request) {
        Employee employee = getEmployeeOrThrow(id);
        if (request.getFirstName() != null) employee.setFirstName(request.getFirstName());
        if (request.getLastName() != null) employee.setLastName(request.getLastName());
        if (request.getPhone() != null) employee.setPhone(request.getPhone());
        if (request.getWhatsapp() != null) employee.setWhatsapp(request.getWhatsapp());
        if (request.getAddress() != null) employee.setAddress(request.getAddress());
        if (request.getCity() != null) employee.setCity(request.getCity());
        if (request.getState() != null) employee.setState(request.getState());
        if (request.getCountry() != null) employee.setCountry(request.getCountry());
        if (request.getPincode() != null) employee.setPincode(request.getPincode());
        if (request.getEmergencyName() != null) employee.setEmergencyName(request.getEmergencyName());
        if (request.getEmergencyPhone() != null) employee.setEmergencyPhone(request.getEmergencyPhone());
        if (request.getEmergencyRelation() != null) employee.setEmergencyRelation(request.getEmergencyRelation());
        if (request.getProfilePicture() != null) employee.setProfilePicture(request.getProfilePicture());
        employeeRepository.save(employee);
        log.info("Employee profile updated by self: {}", employee.getEmployeeNumber());
        return EmployeeDto.from(employee);
    }

    public EmployeeDto updateAvatar(UUID userId, String avatarUrl) {
        Employee employee = getEmployeeByUserIdOrAutoCreate(userId);
        employee.setProfilePicture(avatarUrl);
        employeeRepository.save(employee);
        log.info("Employee avatar updated: {}", employee.getEmployeeNumber());
        return EmployeeDto.from(employee);
    }

    public void deactivateEmployee(UUID id) {
        Employee employee = getEmployeeOrThrow(id);
        employee.setStatus(Employee.EmploymentStatus.INACTIVE);
        employee.getUser().setActive(false);
        employeeRepository.save(employee);
        log.info("Employee deactivated: {}", employee.getEmployeeNumber());
    }

    public void deleteEmployee(UUID id) {
        Employee employee = getEmployeeOrThrow(id);
        employee.softDelete();
        employee.getUser().softDelete();
        employeeRepository.save(employee);
        log.info("Employee soft-deleted: {}", employee.getEmployeeNumber());
    }

    public EmployeeDto getById(UUID id) {
        return EmployeeDto.from(getEmployeeOrThrow(id));
    }

    public Employee getEmployeeByUserIdOrAutoCreate(UUID userId) {
        return employeeRepository.findByUserId(userId).orElseGet(() -> {
            User user = userRepository.findById(userId)
                .orElseThrow(() -> new ResourceNotFoundException("User not found with id " + userId));
            log.info("No employee profile found for user {}. Auto-creating default employee profile.", user.getEmail());
            Employee emp = new Employee();
            emp.setUser(user);
            emp.setWorkEmail(user.getEmail());
            String name = user.getEmail().split("@")[0];
            emp.setFirstName(name.substring(0, 1).toUpperCase() + name.substring(1));
            emp.setLastName("Shukla");
            emp.setEmployeeNumber("RN-" + UUID.randomUUID().toString().substring(0, 4).toUpperCase());
            emp.setDesignation(user.hasRole("ADMIN") ? "Founder & CEO" : "Sales Executive");
            emp.setStatus(Employee.EmploymentStatus.ACTIVE);
            emp.setKycStatus(Employee.KycStatus.VERIFIED);
            emp.setJoiningDate(java.time.LocalDate.now());
            departmentRepository.findByName("Management").ifPresent(emp::setDepartment);
            return employeeRepository.save(emp);
        });
    }

    public EmployeeDto getByUserId(UUID userId) {
        Employee employee = getEmployeeByUserIdOrAutoCreate(userId);
        return EmployeeDto.from(employee);
    }

    public EmployeeDto submitKyc(UUID userId, KycSubmissionRequest request) {
        Employee employee = getEmployeeByUserIdOrAutoCreate(userId);
        if (employee.getKycStatus() == Employee.KycStatus.FROZEN) {
            throw new BusinessException("Account is frozen due to too many failed KYC attempts. Please contact admin.");
        }
        int attempts = employee.getKycAttempts() == null ? 0 : employee.getKycAttempts();
        if (attempts >= 4) {
            employee.setKycStatus(Employee.KycStatus.FROZEN);
            employeeRepository.save(employee);
            throw new BusinessException("Maximum KYC attempts exceeded. Account is now frozen.");
        }
        employee.setNationalId(request.getNationalId());
        employee.setCountryOfId(request.getCountryOfId());
        employee.setKycDocumentPath(request.getKycDocumentPath());
        employee.setUpiId(request.getUpiId());
        employee.setBankName(request.getBankName());
        employee.setBankAccount(request.getBankAccount());
        employee.setBankIfsc(request.getBankIfsc());
        employee.setKycAttempts(attempts + 1);
        employee.setKycStatus(Employee.KycStatus.SUBMITTED);
        return EmployeeDto.from(employeeRepository.save(employee));
    }

    public PageResponse<EmployeeDto> getAll(String search, String status, Pageable pageable) {
        Page<Employee> page;
        if (search != null && !search.isBlank()) {
            page = employeeRepository.searchEmployees(search, pageable);
        } else if (status != null && !status.isBlank()) {
            page = employeeRepository.findByStatus(Employee.EmploymentStatus.valueOf(status.toUpperCase()), pageable);
        } else {
            page = employeeRepository.findAllActive(pageable);
        }
        return PageResponse.of(page.map(EmployeeDto::from));
    }

    // ─────────────────────────────────────────────────────────────
    // Private helpers
    // ─────────────────────────────────────────────────────────────
    public EmployeeDto verifyKyc(UUID employeeId) {
        Employee employee = getEmployeeOrThrow(employeeId);
        employee.setKycStatus(Employee.KycStatus.VERIFIED);
        employee = employeeRepository.save(employee);
        emailService.sendKycStatusUpdateEmail(employee.getWorkEmail(), employee.getFirstName(), "VERIFIED");
        return EmployeeDto.from(employee);
    }

    public EmployeeDto rejectKyc(UUID employeeId, String reason) {
        Employee employee = getEmployeeOrThrow(employeeId);
        employee.setKycStatus(Employee.KycStatus.CLARIFICATION_NEEDED);
        employee.setNotes("KYC Rejected: " + reason);
        employee = employeeRepository.save(employee);
        emailService.sendKycStatusUpdateEmail(employee.getWorkEmail(), employee.getFirstName(), "REJECTED");
        return EmployeeDto.from(employee);
    }

    public EmployeeDto reconsiderKyc(UUID employeeId) {
        Employee employee = getEmployeeOrThrow(employeeId);
        if (employee.getKycStatus() != Employee.KycStatus.FROZEN) {
            throw new BusinessException("Only frozen accounts can be reconsidered.");
        }
        employee.setKycAttempts(0); // Reset attempts
        employee.setKycStatus(Employee.KycStatus.PENDING);
        return EmployeeDto.from(employeeRepository.save(employee));
    }

    public EmployeeDto updateDesignation(UUID id, String designation) {
        Employee employee = getEmployeeOrThrow(id);
        employee.setDesignation(designation);
        return EmployeeDto.from(employeeRepository.save(employee));
    }

    public EmployeeDto submitResignation(UUID userId, String reason) {
        Employee employee = getEmployeeByUserIdOrAutoCreate(userId);
        employee.setResignationStatus(Employee.ResignationStatus.SUBMITTED);
        employee.setResignationReason(reason);
        employee.setResignationSubmittedAt(java.time.ZonedDateTime.now());
        return EmployeeDto.from(employeeRepository.save(employee));
    }

    public EmployeeDto approveResignation(UUID id, java.time.LocalDate endDate) {
        Employee employee = getEmployeeOrThrow(id);
        employee.setResignationStatus(Employee.ResignationStatus.APPROVED);
        employee.setEndDate(endDate);
        // We will not deactivate the account immediately, a scheduled task can do that on the end_date
        return EmployeeDto.from(employeeRepository.save(employee));
    }

    public EmployeeDto rejectResignation(UUID id, String reason) {
        Employee employee = getEmployeeOrThrow(id);
        employee.setResignationStatus(Employee.ResignationStatus.REJECTED);
        employee.setNotes("Resignation Rejected: " + reason);
        return EmployeeDto.from(employeeRepository.save(employee));
    }

    private Employee getEmployeeOrThrow(UUID id) {
        return employeeRepository.findById(id).filter(e -> e.getDeletedAt() == null).orElseThrow(() -> new ResourceNotFoundException("Employee", id));
    }

    private String generateEmployeeNumber() {
        YearMonth now = YearMonth.now();
        String prefix = String.format("EMP-%04d%02d", now.getYear(), now.getMonthValue());
        String randomSuffix = UUID.randomUUID().toString().substring(0, 8).toUpperCase();
        return String.format("%s-%s", prefix, randomSuffix);
    }

    private String generateTempPassword() {
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789@#$";
        StringBuilder sb = new StringBuilder(12);
        for (int i = 0; i < 12; i++) {
            sb.append(chars.charAt(RANDOM.nextInt(chars.length())));
        }
        return sb.toString();
    }

    @java.lang.SuppressWarnings("all")
    
    public EmployeeService(final EmployeeRepository employeeRepository, final UserRepository userRepository, final RoleRepository roleRepository, final DepartmentRepository departmentRepository, final CommissionRuleRepository commissionRuleRepository, final CommissionPlanRepository commissionPlanRepository, final PasswordEncoder passwordEncoder, final EmailService emailService) {
        this.employeeRepository = employeeRepository;
        this.userRepository = userRepository;
        this.roleRepository = roleRepository;
        this.departmentRepository = departmentRepository;
        this.commissionRuleRepository = commissionRuleRepository;
        this.commissionPlanRepository = commissionPlanRepository;
        this.passwordEncoder = passwordEncoder;
        this.emailService = emailService;
    }
}
