// Generated by delombok at Fri Jul 24 16:18:01 IST 2026
package com.ripplenexus.salespilot.auth.domain;

import com.ripplenexus.salespilot.core.domain.BaseEntity;
import jakarta.persistence.*;

import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "roles")
@com.fasterxml.jackson.annotation.JsonIgnoreProperties({"hibernateLazyInitializer", "handler", "permissions", "users"})
public class Role extends BaseEntity {
    @Column(name = "name", nullable = false, unique = true)
    private String name;
    @Column(name = "description")
    private String description;
    @Column(name = "is_system", nullable = false)
    private boolean isSystem = false;
    @ManyToMany(fetch = FetchType.LAZY)
    @org.hibernate.annotations.Fetch(org.hibernate.annotations.FetchMode.SUBSELECT)
    @JoinTable(name = "role_permissions", joinColumns = @JoinColumn(name = "role_id"), inverseJoinColumns = @JoinColumn(name = "permission_id"))
    private Set<Permission> permissions;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean isSystem() {
        return isSystem;
    }

    public void setSystem(boolean system) {
        isSystem = system;
    }

    public Set<Permission> getPermissions() {
        return permissions;
    }

    public void setPermissions(Set<Permission> permissions) {
        this.permissions = permissions;
    }

    @java.lang.SuppressWarnings("all")
    
    private static Set<Permission> $default$permissions() {
        return new HashSet<>();
    }


    @java.lang.SuppressWarnings("all")
    
    public static class RoleBuilder {
        @java.lang.SuppressWarnings("all")
        
        private String name;
        @java.lang.SuppressWarnings("all")
        
        private String description;
        @java.lang.SuppressWarnings("all")
        
        private boolean isSystem;
        @java.lang.SuppressWarnings("all")
        
        private boolean permissions$set;
        @java.lang.SuppressWarnings("all")
        
        private Set<Permission> permissions$value;

        @java.lang.SuppressWarnings("all")
        
        RoleBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Role.RoleBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Role.RoleBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Role.RoleBuilder isSystem(final boolean isSystem) {
            this.isSystem = isSystem;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Role.RoleBuilder permissions(final Set<Permission> permissions) {
            this.permissions$value = permissions;
            permissions$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Role build() {
            Set<Permission> permissions$value = this.permissions$value;
            if (!this.permissions$set) permissions$value = Role.$default$permissions();
            return new Role(this.name, this.description, this.isSystem, permissions$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Role.RoleBuilder(name=" + this.name + ", description=" + this.description + ", isSystem=" + this.isSystem + ", permissions$value=" + this.permissions$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static Role.RoleBuilder builder() {
        return new Role.RoleBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Role() {
        this.permissions = Role.$default$permissions();
    }

    @java.lang.SuppressWarnings("all")
    
    public Role(final String name, final String description, final boolean isSystem, final Set<Permission> permissions) {
        this.name = name;
        this.description = description;
        this.isSystem = isSystem;
        this.permissions = permissions;
    }
}
