// Generated by delombok at Fri Jul 24 16:18:01 IST 2026
package com.ripplenexus.salespilot.auth.domain;

import com.ripplenexus.salespilot.core.domain.BaseEntity;
import jakarta.persistence.*;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import java.time.Instant;
import java.util.Collection;
import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;

@Entity
@Table(name = "users")
public class User extends BaseEntity implements UserDetails {
    @Column(name = "email", nullable = false, unique = true)
    private String email;
    @Column(name = "password_hash", nullable = false)
    private String passwordHash;
    @Column(name = "is_active", nullable = false)
    private boolean isActive = true;
    @Column(name = "is_email_verified", nullable = false)
    private boolean isEmailVerified = false;
    @Column(name = "last_login_at")
    private Instant lastLoginAt;
    @Column(name = "otp_code", length = 10)
    private String otpCode;
    @Column(name = "otp_expiry")
    private Instant otpExpiry;
    @Column(name = "otp_enabled", nullable = false)
    private boolean otpEnabled = true;
    @Column(name = "password_reset_token")
    private String passwordResetToken;
    @Column(name = "password_reset_token_expiry")
    private Instant passwordResetTokenExpiry;
    @Column(name = "email_verify_token")
    private String emailVerifyToken;
    @Column(name = "failed_login_attempts")
    private int failedLoginAttempts = 0;
    @Column(name = "locked_until")
    private Instant lockedUntil;
    @ManyToMany(fetch = FetchType.LAZY)
    @org.hibernate.annotations.Fetch(org.hibernate.annotations.FetchMode.SUBSELECT)
    @JoinTable(name = "user_roles", joinColumns = @JoinColumn(name = "user_id"), inverseJoinColumns = @JoinColumn(name = "role_id"))
    private Set<Role> roles;

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    public boolean isActive() {
        return isActive;
    }

    public void setActive(boolean active) {
        isActive = active;
    }

    public boolean isEmailVerified() {
        return isEmailVerified;
    }

    public void setEmailVerified(boolean emailVerified) {
        isEmailVerified = emailVerified;
    }

    public Instant getLastLoginAt() {
        return lastLoginAt;
    }

    public void setLastLoginAt(Instant lastLoginAt) {
        this.lastLoginAt = lastLoginAt;
    }

    public String getOtpCode() {
        return otpCode;
    }

    public void setOtpCode(String otpCode) {
        this.otpCode = otpCode;
    }

    public Instant getOtpExpiry() {
        return otpExpiry;
    }

    public void setOtpExpiry(Instant otpExpiry) {
        this.otpExpiry = otpExpiry;
    }

    public boolean isOtpEnabled() {
        return otpEnabled;
    }

    public void setOtpEnabled(boolean otpEnabled) {
        this.otpEnabled = otpEnabled;
    }

    public String getPasswordResetToken() {
        return passwordResetToken;
    }

    public void setPasswordResetToken(String passwordResetToken) {
        this.passwordResetToken = passwordResetToken;
    }

    public Instant getPasswordResetTokenExpiry() {
        return passwordResetTokenExpiry;
    }

    public void setPasswordResetTokenExpiry(Instant passwordResetTokenExpiry) {
        this.passwordResetTokenExpiry = passwordResetTokenExpiry;
    }

    public String getEmailVerifyToken() {
        return emailVerifyToken;
    }

    public void setEmailVerifyToken(String emailVerifyToken) {
        this.emailVerifyToken = emailVerifyToken;
    }

    public int getFailedLoginAttempts() {
        return failedLoginAttempts;
    }

    public void setFailedLoginAttempts(int failedLoginAttempts) {
        this.failedLoginAttempts = failedLoginAttempts;
    }

    public Instant getLockedUntil() {
        return lockedUntil;
    }

    public void setLockedUntil(Instant lockedUntil) {
        this.lockedUntil = lockedUntil;
    }

    public Set<Role> getRoles() {
        return roles;
    }

    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        Set<GrantedAuthority> authorities = new HashSet<>();
        roles.forEach(role -> {
            authorities.add(new SimpleGrantedAuthority("ROLE_" + role.getName()));
            role.getPermissions().forEach(permission -> authorities.add(new SimpleGrantedAuthority(permission.getName())));
        });
        return authorities;
    }

    @Override
    public String getPassword() {
        return passwordHash;
    }

    @Override
    public String getUsername() {
        return email;
    }

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return lockedUntil == null || Instant.now().isAfter(lockedUntil);
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return isActive && getDeletedAt() == null;
    }

    public boolean hasRole(String roleName) {
        return roles.stream().anyMatch(r -> r.getName().equals(roleName));
    }

    @java.lang.SuppressWarnings("all")
    
    private static Set<Role> $default$roles() {
        return new HashSet<>();
    }


    @java.lang.SuppressWarnings("all")
    
    public static class UserBuilder {
        @java.lang.SuppressWarnings("all")
        
        private String email;
        @java.lang.SuppressWarnings("all")
        
        private String passwordHash;
        @java.lang.SuppressWarnings("all")
        
        private boolean isActive;
        @java.lang.SuppressWarnings("all")
        
        private boolean isEmailVerified;
        @java.lang.SuppressWarnings("all")
        
        private Instant lastLoginAt;
        @java.lang.SuppressWarnings("all")
        
        private String otpCode;
        @java.lang.SuppressWarnings("all")
        
        private Instant otpExpiry;
        @java.lang.SuppressWarnings("all")
        
        private String passwordResetToken;
        @java.lang.SuppressWarnings("all")
        
        private Instant passwordResetTokenExpiry;
        @java.lang.SuppressWarnings("all")
        
        private String emailVerifyToken;
        @java.lang.SuppressWarnings("all")
        
        private int failedLoginAttempts;
        @java.lang.SuppressWarnings("all")
        
        private Instant lockedUntil;
        @java.lang.SuppressWarnings("all")
        
        private boolean roles$set;
        @java.lang.SuppressWarnings("all")
        
        private Set<Role> roles$value;

        @java.lang.SuppressWarnings("all")
        
        UserBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder email(final String email) {
            this.email = email;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder passwordHash(final String passwordHash) {
            this.passwordHash = passwordHash;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder isActive(final boolean isActive) {
            this.isActive = isActive;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder isEmailVerified(final boolean isEmailVerified) {
            this.isEmailVerified = isEmailVerified;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder lastLoginAt(final Instant lastLoginAt) {
            this.lastLoginAt = lastLoginAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder otpCode(final String otpCode) {
            this.otpCode = otpCode;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder otpExpiry(final Instant otpExpiry) {
            this.otpExpiry = otpExpiry;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder passwordResetToken(final String passwordResetToken) {
            this.passwordResetToken = passwordResetToken;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder passwordResetTokenExpiry(final Instant passwordResetTokenExpiry) {
            this.passwordResetTokenExpiry = passwordResetTokenExpiry;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder emailVerifyToken(final String emailVerifyToken) {
            this.emailVerifyToken = emailVerifyToken;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder failedLoginAttempts(final int failedLoginAttempts) {
            this.failedLoginAttempts = failedLoginAttempts;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder lockedUntil(final Instant lockedUntil) {
            this.lockedUntil = lockedUntil;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder roles(final Set<Role> roles) {
            this.roles$value = roles;
            roles$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public User build() {
            Set<Role> roles$value = this.roles$value;
            if (!this.roles$set) roles$value = User.$default$roles();
            return new User(this.email, this.passwordHash, this.isActive, this.isEmailVerified, this.lastLoginAt, this.otpCode, this.otpExpiry, this.passwordResetToken, this.passwordResetTokenExpiry, this.emailVerifyToken, this.failedLoginAttempts, this.lockedUntil, roles$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "User.UserBuilder(email=" + this.email + ", passwordHash=" + this.passwordHash + ", isActive=" + this.isActive + ", isEmailVerified=" + this.isEmailVerified + ", lastLoginAt=" + this.lastLoginAt + ", otpCode=" + this.otpCode + ", otpExpiry=" + this.otpExpiry + ", passwordResetToken=" + this.passwordResetToken + ", passwordResetTokenExpiry=" + this.passwordResetTokenExpiry + ", emailVerifyToken=" + this.emailVerifyToken + ", failedLoginAttempts=" + this.failedLoginAttempts + ", lockedUntil=" + this.lockedUntil + ", roles$value=" + this.roles$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static User.UserBuilder builder() {
        return new User.UserBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public User() {
        this.roles = User.$default$roles();
    }

    @java.lang.SuppressWarnings("all")
    
    public User(final String email, final String passwordHash, final boolean isActive, final boolean isEmailVerified, final Instant lastLoginAt, final String otpCode, final Instant otpExpiry, final String passwordResetToken, final Instant passwordResetTokenExpiry, final String emailVerifyToken, final int failedLoginAttempts, final Instant lockedUntil, final Set<Role> roles) {
        this.email = email;
        this.passwordHash = passwordHash;
        this.isActive = isActive;
        this.isEmailVerified = isEmailVerified;
        this.lastLoginAt = lastLoginAt;
        this.otpCode = otpCode;
        this.otpExpiry = otpExpiry;
        this.passwordResetToken = passwordResetToken;
        this.passwordResetTokenExpiry = passwordResetTokenExpiry;
        this.emailVerifyToken = emailVerifyToken;
        this.failedLoginAttempts = failedLoginAttempts;
        this.lockedUntil = lockedUntil;
        this.roles = roles;
    }
}
