// Generated by delombok at Fri Jul 24 16:18:07 IST 2026
package com.ripplenexus.salespilot.settings.domain;

import jakarta.persistence.*;


@Entity
@Table(name = "settings")
@EntityListeners(org.springframework.data.jpa.domain.support.AuditingEntityListener.class)
public class SystemSetting {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private java.util.UUID id;
    @Column(name = "key", nullable = false, unique = true)
    private String key;
    @Column(name = "value", columnDefinition = "TEXT")
    private String value;
    @Column(name = "description")
    private String description;
    @Column(name = "category", nullable = false)
    private String category;
    @Column(name = "is_public", nullable = false)
    private Boolean isPublic;
    @org.springframework.data.annotation.CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private java.time.Instant createdAt;
    @org.springframework.data.annotation.LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private java.time.Instant updatedAt;
    @org.springframework.data.annotation.LastModifiedBy
    @Column(name = "updated_by")
    private String updatedBy;

    public java.util.UUID getId() {
        return id;
    }

    public void setId(java.util.UUID id) {
        this.id = id;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Boolean getIsPublic() {
        return isPublic;
    }

    public void setIsPublic(Boolean isPublic) {
        this.isPublic = isPublic;
    }

    public java.time.Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.time.Instant createdAt) {
        this.createdAt = createdAt;
    }

    public java.time.Instant getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.time.Instant updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @java.lang.SuppressWarnings("all")
    
    private static String $default$category() {
        return "general";
    }

    @java.lang.SuppressWarnings("all")
    
    private static Boolean $default$isPublic() {
        return false;
    }


    @java.lang.SuppressWarnings("all")
    
    public static class SystemSettingBuilder {
        @java.lang.SuppressWarnings("all")
        
        private java.util.UUID id;
        @java.lang.SuppressWarnings("all")
        
        private String key;
        @java.lang.SuppressWarnings("all")
        
        private String value;
        @java.lang.SuppressWarnings("all")
        
        private String description;
        @java.lang.SuppressWarnings("all")
        
        private boolean category$set;
        @java.lang.SuppressWarnings("all")
        
        private String category$value;
        @java.lang.SuppressWarnings("all")
        
        private boolean isPublic$set;
        @java.lang.SuppressWarnings("all")
        
        private Boolean isPublic$value;
        @java.lang.SuppressWarnings("all")
        
        private java.time.Instant createdAt;
        @java.lang.SuppressWarnings("all")
        
        private java.time.Instant updatedAt;
        @java.lang.SuppressWarnings("all")
        
        private String updatedBy;

        @java.lang.SuppressWarnings("all")
        
        SystemSettingBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public SystemSetting.SystemSettingBuilder id(final java.util.UUID id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public SystemSetting.SystemSettingBuilder key(final String key) {
            this.key = key;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public SystemSetting.SystemSettingBuilder value(final String value) {
            this.value = value;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public SystemSetting.SystemSettingBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public SystemSetting.SystemSettingBuilder category(final String category) {
            this.category$value = category;
            category$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public SystemSetting.SystemSettingBuilder isPublic(final Boolean isPublic) {
            this.isPublic$value = isPublic;
            isPublic$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public SystemSetting.SystemSettingBuilder createdAt(final java.time.Instant createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public SystemSetting.SystemSettingBuilder updatedAt(final java.time.Instant updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public SystemSetting.SystemSettingBuilder updatedBy(final String updatedBy) {
            this.updatedBy = updatedBy;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public SystemSetting build() {
            String category$value = this.category$value;
            if (!this.category$set) category$value = SystemSetting.$default$category();
            Boolean isPublic$value = this.isPublic$value;
            if (!this.isPublic$set) isPublic$value = SystemSetting.$default$isPublic();
            return new SystemSetting(this.id, this.key, this.value, this.description, category$value, isPublic$value, this.createdAt, this.updatedAt, this.updatedBy);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "SystemSetting.SystemSettingBuilder(id=" + this.id + ", key=" + this.key + ", value=" + this.value + ", description=" + this.description + ", category$value=" + this.category$value + ", isPublic$value=" + this.isPublic$value + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ", updatedBy=" + this.updatedBy + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static SystemSetting.SystemSettingBuilder builder() {
        return new SystemSetting.SystemSettingBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public SystemSetting() {
        this.category = SystemSetting.$default$category();
        this.isPublic = SystemSetting.$default$isPublic();
    }

    @java.lang.SuppressWarnings("all")
    
    public SystemSetting(final java.util.UUID id, final String key, final String value, final String description, final String category, final Boolean isPublic, final java.time.Instant createdAt, final java.time.Instant updatedAt, final String updatedBy) {
        this.id = id;
        this.key = key;
        this.value = value;
        this.description = description;
        this.category = category;
        this.isPublic = isPublic;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.updatedBy = updatedBy;
    }
}
