// Generated by delombok at Fri Jul 24 16:18:04 IST 2026
package com.ripplenexus.salespilot.deal.presentation.dto;

import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotNull;
import java.math.BigDecimal;

public class CloseDealRequest {
    @NotNull(message = "Deal value is required")
    @DecimalMin(value = "0.01", message = "Deal value must be positive")
    private BigDecimal dealValue;
    private String currency = "INR";
    private String invoiceNumber;
    private boolean paymentReceived = false;
    private String paymentMethod;
    private String notes;

    public BigDecimal getDealValue() {
        return dealValue;
    }

    public void setDealValue(BigDecimal dealValue) {
        this.dealValue = dealValue;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    public void setInvoiceNumber(String invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
    }

    public boolean isPaymentReceived() {
        return paymentReceived;
    }

    public void setPaymentReceived(boolean paymentReceived) {
        this.paymentReceived = paymentReceived;
    }

    public String getPaymentMethod() {
        return paymentMethod;
    }

    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    @java.lang.SuppressWarnings("all")
    
    public CloseDealRequest() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CloseDealRequest)) return false;
        final CloseDealRequest other = (CloseDealRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isPaymentReceived() != other.isPaymentReceived()) return false;
        final java.lang.Object this$dealValue = this.getDealValue();
        final java.lang.Object other$dealValue = other.getDealValue();
        if (this$dealValue == null ? other$dealValue != null : !this$dealValue.equals(other$dealValue)) return false;
        final java.lang.Object this$currency = this.getCurrency();
        final java.lang.Object other$currency = other.getCurrency();
        if (this$currency == null ? other$currency != null : !this$currency.equals(other$currency)) return false;
        final java.lang.Object this$invoiceNumber = this.getInvoiceNumber();
        final java.lang.Object other$invoiceNumber = other.getInvoiceNumber();
        if (this$invoiceNumber == null ? other$invoiceNumber != null : !this$invoiceNumber.equals(other$invoiceNumber)) return false;
        final java.lang.Object this$paymentMethod = this.getPaymentMethod();
        final java.lang.Object other$paymentMethod = other.getPaymentMethod();
        if (this$paymentMethod == null ? other$paymentMethod != null : !this$paymentMethod.equals(other$paymentMethod)) return false;
        final java.lang.Object this$notes = this.getNotes();
        final java.lang.Object other$notes = other.getNotes();
        if (this$notes == null ? other$notes != null : !this$notes.equals(other$notes)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CloseDealRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isPaymentReceived() ? 79 : 97);
        final java.lang.Object $dealValue = this.getDealValue();
        result = result * PRIME + ($dealValue == null ? 43 : $dealValue.hashCode());
        final java.lang.Object $currency = this.getCurrency();
        result = result * PRIME + ($currency == null ? 43 : $currency.hashCode());
        final java.lang.Object $invoiceNumber = this.getInvoiceNumber();
        result = result * PRIME + ($invoiceNumber == null ? 43 : $invoiceNumber.hashCode());
        final java.lang.Object $paymentMethod = this.getPaymentMethod();
        result = result * PRIME + ($paymentMethod == null ? 43 : $paymentMethod.hashCode());
        final java.lang.Object $notes = this.getNotes();
        result = result * PRIME + ($notes == null ? 43 : $notes.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public java.lang.String toString() {
        return "CloseDealRequest(dealValue=" + this.getDealValue() + ", currency=" + this.getCurrency() + ", invoiceNumber=" + this.getInvoiceNumber() + ", paymentReceived=" + this.isPaymentReceived() + ", paymentMethod=" + this.getPaymentMethod() + ", notes=" + this.getNotes() + ")";
    }
}
