// Generated by delombok at Fri Jul 24 16:18:00 IST 2026
package com.ripplenexus.salespilot.activity.domain;

import com.ripplenexus.salespilot.core.domain.BaseEntity;
import com.ripplenexus.salespilot.employee.domain.Employee;
import com.ripplenexus.salespilot.lead.domain.Lead;
import jakarta.persistence.*;

import java.time.Instant;

@Entity
@Table(name = "activities")
public class Activity extends BaseEntity {
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "lead_id")
    private Lead lead;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "performed_by", nullable = false)
    private Employee employee;
    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false)
    private ActivityType type;
    @Column(name = "title", nullable = false)
    private String title;
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;
    @Column(name = "performed_at", nullable = false)
    private Instant activityDate;


    public enum ActivityType {
        EMAIL, CALL, MEETING, NOTE, SYSTEM_EVENT, STAGE_CHANGE;
    }

    public Lead getLead() {
        return lead;
    }

    public void setLead(Lead lead) {
        this.lead = lead;
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public ActivityType getType() {
        return type;
    }

    public void setType(ActivityType type) {
        this.type = type;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Instant getActivityDate() {
        return activityDate;
    }

    public void setActivityDate(Instant activityDate) {
        this.activityDate = activityDate;
    }

    @java.lang.SuppressWarnings("all")
    
    private static Instant $default$activityDate() {
        return Instant.now();
    }


    @java.lang.SuppressWarnings("all")
    
    public static class ActivityBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Lead lead;
        @java.lang.SuppressWarnings("all")
        
        private Employee employee;
        @java.lang.SuppressWarnings("all")
        
        private ActivityType type;
        @java.lang.SuppressWarnings("all")
        
        private String title;
        @java.lang.SuppressWarnings("all")
        
        private String description;
        @java.lang.SuppressWarnings("all")
        
        private boolean activityDate$set;
        @java.lang.SuppressWarnings("all")
        
        private Instant activityDate$value;

        @java.lang.SuppressWarnings("all")
        
        ActivityBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Activity.ActivityBuilder lead(final Lead lead) {
            this.lead = lead;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Activity.ActivityBuilder employee(final Employee employee) {
            this.employee = employee;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Activity.ActivityBuilder type(final ActivityType type) {
            this.type = type;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Activity.ActivityBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Activity.ActivityBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Activity.ActivityBuilder activityDate(final Instant activityDate) {
            this.activityDate$value = activityDate;
            activityDate$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Activity build() {
            Instant activityDate$value = this.activityDate$value;
            if (!this.activityDate$set) activityDate$value = Activity.$default$activityDate();
            return new Activity(this.lead, this.employee, this.type, this.title, this.description, activityDate$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Activity.ActivityBuilder(lead=" + this.lead + ", employee=" + this.employee + ", type=" + this.type + ", title=" + this.title + ", description=" + this.description + ", activityDate$value=" + this.activityDate$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static Activity.ActivityBuilder builder() {
        return new Activity.ActivityBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Activity() {
        this.activityDate = Activity.$default$activityDate();
    }

    @java.lang.SuppressWarnings("all")
    
    public Activity(final Lead lead, final Employee employee, final ActivityType type, final String title, final String description, final Instant activityDate) {
        this.lead = lead;
        this.employee = employee;
        this.type = type;
        this.title = title;
        this.description = description;
        this.activityDate = activityDate;
    }
}
