// Generated by delombok at Fri Jul 24 16:18:00 IST 2026
package com.ripplenexus.salespilot.activity.domain;

import com.ripplenexus.salespilot.core.domain.BaseEntity;
import com.ripplenexus.salespilot.employee.domain.Employee;
import com.ripplenexus.salespilot.lead.domain.Lead;
import jakarta.persistence.*;

import java.time.Instant;

@Entity
@Table(name = "followups")
public class FollowUp extends BaseEntity {
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "lead_id")
    private Lead lead;
    @Column(name = "company_id")
    private java.util.UUID companyId;
    @Column(name = "contact_id")
    private java.util.UUID contactId;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assigned_to")
    private Employee assignedTo;
    @Column(name = "type", nullable = false)
    private String type;
    @Column(name = "title", nullable = false)
    private String title;
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;
    @Column(name = "scheduled_at", nullable = false)
    private Instant scheduledAt;
    @Column(name = "completed_at")
    private Instant completedAt;
    @Column(name = "is_completed", nullable = false)
    private Boolean isCompleted;
    @Column(name = "is_overdue", nullable = false)
    private Boolean isOverdue;
    @Column(name = "is_recurring", nullable = false)
    private Boolean isRecurring;
    @Column(name = "recurrence_rule")
    private String recurrenceRule;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "next_followup_id")
    private FollowUp nextFollowup;
    @Column(name = "reminder_sent", nullable = false)
    private Boolean reminderSent;

    public Lead getLead() {
        return lead;
    }

    public void setLead(Lead lead) {
        this.lead = lead;
    }

    public java.util.UUID getCompanyId() {
        return companyId;
    }

    public void setCompanyId(java.util.UUID companyId) {
        this.companyId = companyId;
    }

    public java.util.UUID getContactId() {
        return contactId;
    }

    public void setContactId(java.util.UUID contactId) {
        this.contactId = contactId;
    }

    public Employee getAssignedTo() {
        return assignedTo;
    }

    public void setAssignedTo(Employee assignedTo) {
        this.assignedTo = assignedTo;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Instant getScheduledAt() {
        return scheduledAt;
    }

    public void setScheduledAt(Instant scheduledAt) {
        this.scheduledAt = scheduledAt;
    }

    public Instant getCompletedAt() {
        return completedAt;
    }

    public void setCompletedAt(Instant completedAt) {
        this.completedAt = completedAt;
    }

    public Boolean getIsCompleted() {
        return isCompleted;
    }

    public void setIsCompleted(Boolean isCompleted) {
        this.isCompleted = isCompleted;
    }

    public Boolean getIsOverdue() {
        return isOverdue;
    }

    public void setIsOverdue(Boolean isOverdue) {
        this.isOverdue = isOverdue;
    }

    public Boolean getIsRecurring() {
        return isRecurring;
    }

    public void setIsRecurring(Boolean isRecurring) {
        this.isRecurring = isRecurring;
    }

    public String getRecurrenceRule() {
        return recurrenceRule;
    }

    public void setRecurrenceRule(String recurrenceRule) {
        this.recurrenceRule = recurrenceRule;
    }

    public FollowUp getNextFollowup() {
        return nextFollowup;
    }

    public void setNextFollowup(FollowUp nextFollowup) {
        this.nextFollowup = nextFollowup;
    }

    public Boolean getReminderSent() {
        return reminderSent;
    }

    public void setReminderSent(Boolean reminderSent) {
        this.reminderSent = reminderSent;
    }

    @java.lang.SuppressWarnings("all")
    
    private static String $default$type() {
        return "CALL";
    }

    @java.lang.SuppressWarnings("all")
    
    private static Boolean $default$isCompleted() {
        return false;
    }

    @java.lang.SuppressWarnings("all")
    
    private static Boolean $default$isOverdue() {
        return false;
    }

    @java.lang.SuppressWarnings("all")
    
    private static Boolean $default$isRecurring() {
        return false;
    }

    @java.lang.SuppressWarnings("all")
    
    private static Boolean $default$reminderSent() {
        return false;
    }


    @java.lang.SuppressWarnings("all")
    
    public static class FollowUpBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Lead lead;
        @java.lang.SuppressWarnings("all")
        
        private java.util.UUID companyId;
        @java.lang.SuppressWarnings("all")
        
        private java.util.UUID contactId;
        @java.lang.SuppressWarnings("all")
        
        private Employee assignedTo;
        @java.lang.SuppressWarnings("all")
        
        private boolean type$set;
        @java.lang.SuppressWarnings("all")
        
        private String type$value;
        @java.lang.SuppressWarnings("all")
        
        private String title;
        @java.lang.SuppressWarnings("all")
        
        private String notes;
        @java.lang.SuppressWarnings("all")
        
        private Instant scheduledAt;
        @java.lang.SuppressWarnings("all")
        
        private Instant completedAt;
        @java.lang.SuppressWarnings("all")
        
        private boolean isCompleted$set;
        @java.lang.SuppressWarnings("all")
        
        private Boolean isCompleted$value;
        @java.lang.SuppressWarnings("all")
        
        private boolean isOverdue$set;
        @java.lang.SuppressWarnings("all")
        
        private Boolean isOverdue$value;
        @java.lang.SuppressWarnings("all")
        
        private boolean isRecurring$set;
        @java.lang.SuppressWarnings("all")
        
        private Boolean isRecurring$value;
        @java.lang.SuppressWarnings("all")
        
        private String recurrenceRule;
        @java.lang.SuppressWarnings("all")
        
        private FollowUp nextFollowup;
        @java.lang.SuppressWarnings("all")
        
        private boolean reminderSent$set;
        @java.lang.SuppressWarnings("all")
        
        private Boolean reminderSent$value;

        @java.lang.SuppressWarnings("all")
        
        FollowUpBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public FollowUp.FollowUpBuilder lead(final Lead lead) {
            this.lead = lead;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public FollowUp.FollowUpBuilder companyId(final java.util.UUID companyId) {
            this.companyId = companyId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public FollowUp.FollowUpBuilder contactId(final java.util.UUID contactId) {
            this.contactId = contactId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public FollowUp.FollowUpBuilder assignedTo(final Employee assignedTo) {
            this.assignedTo = assignedTo;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public FollowUp.FollowUpBuilder type(final String type) {
            this.type$value = type;
            type$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public FollowUp.FollowUpBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public FollowUp.FollowUpBuilder notes(final String notes) {
            this.notes = notes;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public FollowUp.FollowUpBuilder scheduledAt(final Instant scheduledAt) {
            this.scheduledAt = scheduledAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public FollowUp.FollowUpBuilder completedAt(final Instant completedAt) {
            this.completedAt = completedAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public FollowUp.FollowUpBuilder isCompleted(final Boolean isCompleted) {
            this.isCompleted$value = isCompleted;
            isCompleted$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public FollowUp.FollowUpBuilder isOverdue(final Boolean isOverdue) {
            this.isOverdue$value = isOverdue;
            isOverdue$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public FollowUp.FollowUpBuilder isRecurring(final Boolean isRecurring) {
            this.isRecurring$value = isRecurring;
            isRecurring$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public FollowUp.FollowUpBuilder recurrenceRule(final String recurrenceRule) {
            this.recurrenceRule = recurrenceRule;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public FollowUp.FollowUpBuilder nextFollowup(final FollowUp nextFollowup) {
            this.nextFollowup = nextFollowup;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public FollowUp.FollowUpBuilder reminderSent(final Boolean reminderSent) {
            this.reminderSent$value = reminderSent;
            reminderSent$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public FollowUp build() {
            String type$value = this.type$value;
            if (!this.type$set) type$value = FollowUp.$default$type();
            Boolean isCompleted$value = this.isCompleted$value;
            if (!this.isCompleted$set) isCompleted$value = FollowUp.$default$isCompleted();
            Boolean isOverdue$value = this.isOverdue$value;
            if (!this.isOverdue$set) isOverdue$value = FollowUp.$default$isOverdue();
            Boolean isRecurring$value = this.isRecurring$value;
            if (!this.isRecurring$set) isRecurring$value = FollowUp.$default$isRecurring();
            Boolean reminderSent$value = this.reminderSent$value;
            if (!this.reminderSent$set) reminderSent$value = FollowUp.$default$reminderSent();
            return new FollowUp(this.lead, this.companyId, this.contactId, this.assignedTo, type$value, this.title, this.notes, this.scheduledAt, this.completedAt, isCompleted$value, isOverdue$value, isRecurring$value, this.recurrenceRule, this.nextFollowup, reminderSent$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "FollowUp.FollowUpBuilder(lead=" + this.lead + ", companyId=" + this.companyId + ", contactId=" + this.contactId + ", assignedTo=" + this.assignedTo + ", type$value=" + this.type$value + ", title=" + this.title + ", notes=" + this.notes + ", scheduledAt=" + this.scheduledAt + ", completedAt=" + this.completedAt + ", isCompleted$value=" + this.isCompleted$value + ", isOverdue$value=" + this.isOverdue$value + ", isRecurring$value=" + this.isRecurring$value + ", recurrenceRule=" + this.recurrenceRule + ", nextFollowup=" + this.nextFollowup + ", reminderSent$value=" + this.reminderSent$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static FollowUp.FollowUpBuilder builder() {
        return new FollowUp.FollowUpBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public FollowUp() {
        this.type = FollowUp.$default$type();
        this.isCompleted = FollowUp.$default$isCompleted();
        this.isOverdue = FollowUp.$default$isOverdue();
        this.isRecurring = FollowUp.$default$isRecurring();
        this.reminderSent = FollowUp.$default$reminderSent();
    }

    @java.lang.SuppressWarnings("all")
    
    public FollowUp(final Lead lead, final java.util.UUID companyId, final java.util.UUID contactId, final Employee assignedTo, final String type, final String title, final String notes, final Instant scheduledAt, final Instant completedAt, final Boolean isCompleted, final Boolean isOverdue, final Boolean isRecurring, final String recurrenceRule, final FollowUp nextFollowup, final Boolean reminderSent) {
        this.lead = lead;
        this.companyId = companyId;
        this.contactId = contactId;
        this.assignedTo = assignedTo;
        this.type = type;
        this.title = title;
        this.notes = notes;
        this.scheduledAt = scheduledAt;
        this.completedAt = completedAt;
        this.isCompleted = isCompleted;
        this.isOverdue = isOverdue;
        this.isRecurring = isRecurring;
        this.recurrenceRule = recurrenceRule;
        this.nextFollowup = nextFollowup;
        this.reminderSent = reminderSent;
    }
}
