// Generated by delombok at Fri Jul 24 16:18:00 IST 2026
package com.ripplenexus.salespilot.activity.domain;

import com.ripplenexus.salespilot.core.domain.BaseEntity;
import com.ripplenexus.salespilot.employee.domain.Employee;
import com.ripplenexus.salespilot.lead.domain.Lead;
import jakarta.persistence.*;

import java.time.Instant;

@Entity
@Table(name = "meetings")
public class Meeting extends BaseEntity {
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "lead_id")
    private Lead lead;
    @Column(name = "company_id")
    private java.util.UUID companyId;
    @Column(name = "contact_id")
    private java.util.UUID contactId;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "organizer_id")
    private Employee organizer;
    @Column(name = "type", nullable = false)
    private String type;
    @Column(name = "title", nullable = false)
    private String title;
    @Column(name = "agenda", columnDefinition = "TEXT")
    private String agenda;
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;
    @Column(name = "outcome", columnDefinition = "TEXT")
    private String outcome;
    @Column(name = "next_action", columnDefinition = "TEXT")
    private String nextAction;
    @Column(name = "scheduled_at", nullable = false)
    private Instant scheduledAt;
    @Column(name = "duration_minutes", nullable = false)
    private Integer durationMinutes;
    @Column(name = "location")
    private String location;
    @Column(name = "meeting_url")
    private String meetingUrl;
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private MeetingStatus status;


    public enum MeetingStatus {
        SCHEDULED, IN_PROGRESS, COMPLETED, CANCELLED, POSTPONED;
    }

    public Lead getLead() {
        return lead;
    }

    public void setLead(Lead lead) {
        this.lead = lead;
    }

    public java.util.UUID getCompanyId() {
        return companyId;
    }

    public void setCompanyId(java.util.UUID companyId) {
        this.companyId = companyId;
    }

    public java.util.UUID getContactId() {
        return contactId;
    }

    public void setContactId(java.util.UUID contactId) {
        this.contactId = contactId;
    }

    public Employee getOrganizer() {
        return organizer;
    }

    public void setOrganizer(Employee organizer) {
        this.organizer = organizer;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAgenda() {
        return agenda;
    }

    public void setAgenda(String agenda) {
        this.agenda = agenda;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public String getOutcome() {
        return outcome;
    }

    public void setOutcome(String outcome) {
        this.outcome = outcome;
    }

    public String getNextAction() {
        return nextAction;
    }

    public void setNextAction(String nextAction) {
        this.nextAction = nextAction;
    }

    public Instant getScheduledAt() {
        return scheduledAt;
    }

    public void setScheduledAt(Instant scheduledAt) {
        this.scheduledAt = scheduledAt;
    }

    public Integer getDurationMinutes() {
        return durationMinutes;
    }

    public void setDurationMinutes(Integer durationMinutes) {
        this.durationMinutes = durationMinutes;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getMeetingUrl() {
        return meetingUrl;
    }

    public void setMeetingUrl(String meetingUrl) {
        this.meetingUrl = meetingUrl;
    }

    public MeetingStatus getStatus() {
        return status;
    }

    public void setStatus(MeetingStatus status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    
    private static String $default$type() {
        return "ONLINE";
    }

    @java.lang.SuppressWarnings("all")
    
    private static Integer $default$durationMinutes() {
        return 60;
    }

    @java.lang.SuppressWarnings("all")
    
    private static MeetingStatus $default$status() {
        return MeetingStatus.SCHEDULED;
    }


    @java.lang.SuppressWarnings("all")
    
    public static class MeetingBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Lead lead;
        @java.lang.SuppressWarnings("all")
        
        private java.util.UUID companyId;
        @java.lang.SuppressWarnings("all")
        
        private java.util.UUID contactId;
        @java.lang.SuppressWarnings("all")
        
        private Employee organizer;
        @java.lang.SuppressWarnings("all")
        
        private boolean type$set;
        @java.lang.SuppressWarnings("all")
        
        private String type$value;
        @java.lang.SuppressWarnings("all")
        
        private String title;
        @java.lang.SuppressWarnings("all")
        
        private String agenda;
        @java.lang.SuppressWarnings("all")
        
        private String notes;
        @java.lang.SuppressWarnings("all")
        
        private String outcome;
        @java.lang.SuppressWarnings("all")
        
        private String nextAction;
        @java.lang.SuppressWarnings("all")
        
        private Instant scheduledAt;
        @java.lang.SuppressWarnings("all")
        
        private boolean durationMinutes$set;
        @java.lang.SuppressWarnings("all")
        
        private Integer durationMinutes$value;
        @java.lang.SuppressWarnings("all")
        
        private String location;
        @java.lang.SuppressWarnings("all")
        
        private String meetingUrl;
        @java.lang.SuppressWarnings("all")
        
        private boolean status$set;
        @java.lang.SuppressWarnings("all")
        
        private MeetingStatus status$value;

        @java.lang.SuppressWarnings("all")
        
        MeetingBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Meeting.MeetingBuilder lead(final Lead lead) {
            this.lead = lead;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Meeting.MeetingBuilder companyId(final java.util.UUID companyId) {
            this.companyId = companyId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Meeting.MeetingBuilder contactId(final java.util.UUID contactId) {
            this.contactId = contactId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Meeting.MeetingBuilder organizer(final Employee organizer) {
            this.organizer = organizer;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Meeting.MeetingBuilder type(final String type) {
            this.type$value = type;
            type$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Meeting.MeetingBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Meeting.MeetingBuilder agenda(final String agenda) {
            this.agenda = agenda;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Meeting.MeetingBuilder notes(final String notes) {
            this.notes = notes;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Meeting.MeetingBuilder outcome(final String outcome) {
            this.outcome = outcome;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Meeting.MeetingBuilder nextAction(final String nextAction) {
            this.nextAction = nextAction;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Meeting.MeetingBuilder scheduledAt(final Instant scheduledAt) {
            this.scheduledAt = scheduledAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Meeting.MeetingBuilder durationMinutes(final Integer durationMinutes) {
            this.durationMinutes$value = durationMinutes;
            durationMinutes$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Meeting.MeetingBuilder location(final String location) {
            this.location = location;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Meeting.MeetingBuilder meetingUrl(final String meetingUrl) {
            this.meetingUrl = meetingUrl;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Meeting.MeetingBuilder status(final MeetingStatus status) {
            this.status$value = status;
            status$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Meeting build() {
            String type$value = this.type$value;
            if (!this.type$set) type$value = Meeting.$default$type();
            Integer durationMinutes$value = this.durationMinutes$value;
            if (!this.durationMinutes$set) durationMinutes$value = Meeting.$default$durationMinutes();
            MeetingStatus status$value = this.status$value;
            if (!this.status$set) status$value = Meeting.$default$status();
            return new Meeting(this.lead, this.companyId, this.contactId, this.organizer, type$value, this.title, this.agenda, this.notes, this.outcome, this.nextAction, this.scheduledAt, durationMinutes$value, this.location, this.meetingUrl, status$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Meeting.MeetingBuilder(lead=" + this.lead + ", companyId=" + this.companyId + ", contactId=" + this.contactId + ", organizer=" + this.organizer + ", type$value=" + this.type$value + ", title=" + this.title + ", agenda=" + this.agenda + ", notes=" + this.notes + ", outcome=" + this.outcome + ", nextAction=" + this.nextAction + ", scheduledAt=" + this.scheduledAt + ", durationMinutes$value=" + this.durationMinutes$value + ", location=" + this.location + ", meetingUrl=" + this.meetingUrl + ", status$value=" + this.status$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static Meeting.MeetingBuilder builder() {
        return new Meeting.MeetingBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Meeting() {
        this.type = Meeting.$default$type();
        this.durationMinutes = Meeting.$default$durationMinutes();
        this.status = Meeting.$default$status();
    }

    @java.lang.SuppressWarnings("all")
    
    public Meeting(final Lead lead, final java.util.UUID companyId, final java.util.UUID contactId, final Employee organizer, final String type, final String title, final String agenda, final String notes, final String outcome, final String nextAction, final Instant scheduledAt, final Integer durationMinutes, final String location, final String meetingUrl, final MeetingStatus status) {
        this.lead = lead;
        this.companyId = companyId;
        this.contactId = contactId;
        this.organizer = organizer;
        this.type = type;
        this.title = title;
        this.agenda = agenda;
        this.notes = notes;
        this.outcome = outcome;
        this.nextAction = nextAction;
        this.scheduledAt = scheduledAt;
        this.durationMinutes = durationMinutes;
        this.location = location;
        this.meetingUrl = meetingUrl;
        this.status = status;
    }
}
