// Generated by delombok at Fri Jul 24 16:18:06 IST 2026
package com.ripplenexus.salespilot.meeting.presentation.dto;

import jakarta.validation.constraints.Future;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.time.Instant;
import java.util.UUID;

public class CreateMeetingRequest {
    @NotBlank(message = "Title is required")
    private String title;
    private UUID leadId;
    private UUID companyId;
    @NotNull(message = "Meeting type is required")
    private String type; // ONLINE, OFFLINE, PHONE_CALL
    @NotNull(message = "Scheduled time is required")
    @Future(message = "Scheduled time must be in the future")
    private Instant scheduledAt;
    private Integer durationMinutes = 60;
    private String location;
    private String agenda;
    private boolean autoGenerateLink = true;

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public UUID getLeadId() {
        return leadId;
    }

    public void setLeadId(UUID leadId) {
        this.leadId = leadId;
    }

    public UUID getCompanyId() {
        return companyId;
    }

    public void setCompanyId(UUID companyId) {
        this.companyId = companyId;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Instant getScheduledAt() {
        return scheduledAt;
    }

    public void setScheduledAt(Instant scheduledAt) {
        this.scheduledAt = scheduledAt;
    }

    public Integer getDurationMinutes() {
        return durationMinutes;
    }

    public void setDurationMinutes(Integer durationMinutes) {
        this.durationMinutes = durationMinutes;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getAgenda() {
        return agenda;
    }

    public void setAgenda(String agenda) {
        this.agenda = agenda;
    }

    public boolean isAutoGenerateLink() {
        return autoGenerateLink;
    }

    public void setAutoGenerateLink(boolean autoGenerateLink) {
        this.autoGenerateLink = autoGenerateLink;
    }

    @java.lang.SuppressWarnings("all")
    
    public CreateMeetingRequest() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CreateMeetingRequest)) return false;
        final CreateMeetingRequest other = (CreateMeetingRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isAutoGenerateLink() != other.isAutoGenerateLink()) return false;
        final java.lang.Object this$durationMinutes = this.getDurationMinutes();
        final java.lang.Object other$durationMinutes = other.getDurationMinutes();
        if (this$durationMinutes == null ? other$durationMinutes != null : !this$durationMinutes.equals(other$durationMinutes)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$leadId = this.getLeadId();
        final java.lang.Object other$leadId = other.getLeadId();
        if (this$leadId == null ? other$leadId != null : !this$leadId.equals(other$leadId)) return false;
        final java.lang.Object this$companyId = this.getCompanyId();
        final java.lang.Object other$companyId = other.getCompanyId();
        if (this$companyId == null ? other$companyId != null : !this$companyId.equals(other$companyId)) return false;
        final java.lang.Object this$type = this.getType();
        final java.lang.Object other$type = other.getType();
        if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
        final java.lang.Object this$scheduledAt = this.getScheduledAt();
        final java.lang.Object other$scheduledAt = other.getScheduledAt();
        if (this$scheduledAt == null ? other$scheduledAt != null : !this$scheduledAt.equals(other$scheduledAt)) return false;
        final java.lang.Object this$location = this.getLocation();
        final java.lang.Object other$location = other.getLocation();
        if (this$location == null ? other$location != null : !this$location.equals(other$location)) return false;
        final java.lang.Object this$agenda = this.getAgenda();
        final java.lang.Object other$agenda = other.getAgenda();
        if (this$agenda == null ? other$agenda != null : !this$agenda.equals(other$agenda)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CreateMeetingRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isAutoGenerateLink() ? 79 : 97);
        final java.lang.Object $durationMinutes = this.getDurationMinutes();
        result = result * PRIME + ($durationMinutes == null ? 43 : $durationMinutes.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $leadId = this.getLeadId();
        result = result * PRIME + ($leadId == null ? 43 : $leadId.hashCode());
        final java.lang.Object $companyId = this.getCompanyId();
        result = result * PRIME + ($companyId == null ? 43 : $companyId.hashCode());
        final java.lang.Object $type = this.getType();
        result = result * PRIME + ($type == null ? 43 : $type.hashCode());
        final java.lang.Object $scheduledAt = this.getScheduledAt();
        result = result * PRIME + ($scheduledAt == null ? 43 : $scheduledAt.hashCode());
        final java.lang.Object $location = this.getLocation();
        result = result * PRIME + ($location == null ? 43 : $location.hashCode());
        final java.lang.Object $agenda = this.getAgenda();
        result = result * PRIME + ($agenda == null ? 43 : $agenda.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    
    public java.lang.String toString() {
        return "CreateMeetingRequest(title=" + this.getTitle() + ", leadId=" + this.getLeadId() + ", companyId=" + this.getCompanyId() + ", type=" + this.getType() + ", scheduledAt=" + this.getScheduledAt() + ", durationMinutes=" + this.getDurationMinutes() + ", location=" + this.getLocation() + ", agenda=" + this.getAgenda() + ", autoGenerateLink=" + this.isAutoGenerateLink() + ")";
    }
}
